nestjs/docs.nestjs.com

content/techniques/sessions.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
=> docs(sessions): fix typo: req should be request

content/techniques/task-scheduling.md
```
[ x] Bugfix
[ ] Feature
[ x] Docs
```
`* 10 * * * *` does not mean `every hour, at the start of the 10th minute`, but `every seconds during the 10th minute of an hour`
`0 10 * * * *` actually means `every hour, at the start of the 10th minute`
```
[ ] Yes
[ x] No
```
=> fix(task-scheduling): update to wrong cron example

content/recipes/hot-reload.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: #1847
N/A
```
[ ] Yes
[x] No
```
This PR, update the documents in the `hot-reload` recipe after this number #1847
P.s. NestJS ♥️
=> docs(hot-reload): update

content/controllers.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: #1854
N/A
```
[ ] Yes
[x] No
```
This PR, updated description for decorator redirect
=> chore(controllers): updated decorator redirect

content/cli/libraries.md, content/cli/workspaces.md, content/components.md, content/first-steps.md, content/modules.md
=> chore(): update components.md

content/techniques/performance.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
It just shows the content of the file.
You can now see the filename as well.
```
[ ] Yes
[x] No
```
Docs page: https://docs.nestjs.com/techniques/performance#adapter
=> docs: added filename for fastify adapter example

content/openapi/introduction.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Currently the example just shows the content.
You can now see the filename additionally which makes it easier to identify the file to change / update.
```
[ ] Yes
[x] No
```
Docs page: https://docs.nestjs.com/openapi/introduction#bootstrap
=> docs: added filename for OpenAPI bootstrap example

content/recipes/sql-sequelize.md, content/techniques/sql.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: #1872
Updateds sequelize v6.x
```
[ ] Yes
[x] No
```
This PR, update on Sequelize v6.x in the model declaration.
=> docs(sequelize): updateds sequelize v6.x

content/security/authentication.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
=> Fix typo in authentication.md

content/techniques/configuration.md
Removed a paragraph that seems to have been added by accident.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Configuration documentation contains a typo.
The typo has been removed
```
[ ] Yes
[x] No
```
=> docs(configuration): fix aml typo

content/fundamentals/lifecycle-events.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
A parentheses was deleted in #1218.
Restored the parentheses.
```
[ ] Yes
[x] No
```
=> docs: Fix typo

src/app/homepage/pages/techniques/cookies/cookies.component.ts
See also #1901
```
[x] Bugfix
[ ] Feature
[ ] Docs
```
```
[ ] Yes
[x] No
```
=> fix: fix selector for cookies technique

content/recipes/sql-sequelize.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, update the indentation
=> docs(sequelize): fix indentation

content/microservices/kafka.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
=> chore(docs): fix typo

content/techniques/mvc.md
```
[x] Bugfix
[ ] Feature
[x] Docs
```
No need to install fastify package since it should have been installed with `FastifyAdapter` but `fastify-static` package is required to serve static content.
Changed package name to fastify static to make example working.
```
[ ] Yes
[x] No
```
=> docs(mvc): fixed required package for using with fastify

content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
[x ] Docs
```
```
[ ] Yes
[x] No
```
=> docs: fix code snippet

content/fundamentals/dynamic-modules.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
=> Typo perhaps

content/controllers.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
=> Fix inline code spacing

content/techniques/serialization.md
* use transform correctly like the example https://github.com/nestjs/nest/blob/25a92ccce101e3339b5c88a3615f2984b0ef5556/sample/21-serializer/src/entities/user.entity.ts#L17-L18
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
```
[ ] Yes
[X] No
```
=> docs(serialization): update transform usage

content/first-steps.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The name of the directory that the docs say will be created doesn't match the name in the CLI command shown.
The description of the directory now matches the command shown. It also matches the format a bit later (shown with `src/`).
```
[ ] Yes
[X] No
```
=> docs(): update first-steps.md

content/security/encryption-hashing.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
=> docs(encryption): Added missing scrypt import

content/security/helmet.md
There is a not-used parenthesis in the security/helmet.md file.
The not-used parenthesis was removed from the security/helmet.md file.
=> docs(): remove not used parenthesis

content/discover/who-uses.json
- [ x ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[ x ] Docs
```
Forward Digital does not appear on the who uses list
Forward Digital appears on the who uses list
```
[ ] Yes
[ x ] No
```
=> docs(who-uses): Add Forward Digital to who-uses.json

content/fundamentals/dependency-injection.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
[] Other... Please describe:
```
```
[ ] Yes
[x] No
```
=> Fix a grammatical error from "in to" to "into"

content/recipes/prisma.md
```
[ ] Bugfix
[ ] Feature
[x ] Docs
```
Issue Number: For example, this behaviour has probably tripped up a number of people  https://github.com/nestjs/nest/issues/7005
This change will hopefully spare people a few hours trying to figure out why their enableShutdownHooks isn't working as expected when using prisma, since its not obvious that prisma would be the source of the issue. 
```
[ ] Yes
[x ] No
```
=> Prisma recipe fix

content/techniques/caching.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
not accurate description of get cache method
reflects more the true return of the function.
```
[ ] Yes
[x] No
```
=> docs(caching): update get cache method description

content/techniques/file-upload.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, small improvement in the multiple files example.
=> docs(file-upload): improvement

content/techniques/queues.md
Hi, Hope you're doing good.
Adding a simple 'await' where it's needed. :)
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
=> docs(queue): add missing await.

content/security/rate-limiting.md
fixed a small typo.
- [x ] Docs
- [x ] No
=> docs(typo): fixed a small typo

content/techniques/validation.md
=> docs(techniques): fix typo in validation.md

content/microservices/nats.md
the client connection options have changed, and the current example does not work
The current documentations shows the old configurations options for the NATS client. Following this will cause a runtime error where the application is unable to connect to the NATS server.
The starter examples are updated to use the new config options.
=> docs: update nats microservice docs for 8.0

content/faq/serverless.md
=> docs(serverless): fix typo

content/microservices/basics.md
app.listen() Expected 0 arguments, but got 1.
=> Remove unnecessary argument from app.listen()

content/security/authentication.md
Issue Number: #1969 
The JwtModule is removed from exports in auth/auth.module.ts
=> fix(content): remove JwtModule from exports

content/recipes/router-module.md
Issue Number: https://github.com/nestjs/nest/issues/7612
Update router module
This PR, update router module(see issue  https://github.com/nestjs/nest/issues/7612), as code snippet is incorrect.
=> docs(recipe): update router module

content/openapi/other-features.md
Even though the example code snippet is purely demonstrative, the `DogsModule` variable would not be found, and the code would not work.
Assuming all other relevant files are in place (`./app.module`, `./cats/cats.module`, `./dogs/dogs.module`, etc), the code will execute and work.
=> Minor Code Snippet Correction of OpenAPI > Other Features > Multiple specifications

content/graphql/quick-start.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: 
#1836
N/A
```
[ ] Yes
[x] No
```
This PR, Added warning in case you use `apollo-server-fastify` package with GraphQL
=> docs(graphql): added warning

content/recipes/terminus.md
The health check code example does not contain the needed imports. 
The health check code example contains the needed imports. 
It might be handy to have the imports for the ease of the tutorial.
=> docs(terminus): add imports to Terminus health check code example

content/graphql/quick-start.md
Issue Number: #1981
Closes #1981
=> docs(graphql/getting-started): remove graphql-tools dependency from installation instructions

content/openapi/introduction.md
Issue Number: #1982
Update setup options for fastify
This PR, update setup options for fastify (see issue #1982)
=> docs(openapi): update setup options for fastify

content/microservices/basics.md, content/microservices/custom-transport.md
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
Related to ([Nest#5710](https://github.com/nestjs/nest/pull/5710))
Currently no docs on how to extend the `ClientProxy` with new functionality
There are now docs showing how the `ClientProxy` can be extended on a basic level
```
[ ] Yes
[X] No
```
=> docs(microservice): add documentation for new custom client proxy

content/discover/who-uses.json
=> docs(who-uses): Add rozetka logo

content/graphql/quick-start.md
=> docs(graphql): fix typo

content/recipes/sql-typeorm.md
Unused Repository on TypeORM Docs
Removed Repository from photoProviders
=> docs(typeorm): Remove unused Repository from photoProviders

content/cli/usages.md
It shows an usage example like the other nest generate commands.
=> docs: add example for nest add and nest info

content/cli/overview.md, content/cli/workspaces.md
=> docs: replace remaining tslint mentions by eslint equivalents

content/faq/serverless.md
Replace "," with "." in CPU clock speed below benchmark table. 
Fixes: #2015
Issue Number: #2015
=> docs(faq): fixed minor typo

content/microservices/mqtt.md
High-latency isn't likely to be the desired product of optimization 🐢
=> Replace "high-latency" with "low latency"

content/middlewares.md
no file name provided
added file name for the global middleware example.
=> docs(middleware): add file name for global middleware example

content/security/rate-limiting.md
=> docs(security): add rate limit example behind proxies

content/controllers.md
Add a hint section bellow the DTO description about the whitelist option from the ValidationPipe.
=> docs(controller): Add whitelist info bellow DTO explanation

content/graphql/complexity.md
example compatible with apollo-server-express v3 
apollo-server-express v3 requires plugin code to be async, which is now reflected in the Complexity example in the docs
=> made example compatible with apollo-server-express v3

content/recipes/prisma.md
The link bring us to a wrong page: https://docs.nestjs.com/#issues-with-enableShutdownHooks
Fix the link to navigate to https://docs.nestjs.com/recipes/prisma#issues-with-enableshutdownhooks
=> docs(prisma): Fix broken link

content/recipes/prisma.md
=> docs(prisma): Typo

content/migration.md
=> Add terminus v8 migration guide

content/techniques/validation.md
Some options of `class-validator` are missing in the document.
Add more class validator options in the document.
=> docs(validation): add more class validator options

content/security/rate-limiting.md
=> docs(security): add community storage provider redis

content/recipes/terminus.md
Added warning for Http Health Indicator
This PR, added warning for Http Health Indicator
=> docs(terminus): added warning for Http Health Indicator

content/fundamentals/unit-testing.md
Issue Number: fix #2049
Doc clarification.
=> Clarify "Overriding globally registered enhancers"

content/graphql/resolvers-map.md
- https://github.com/nestjs/docs.nestjs.com/issues/2041
- Fix graphql object types sample
=> docs(graphql): Fix GraphQL object types sample

content/techniques/caching.md
It is not documented.
Issue Number: https://github.com/nestjs/nest/issues/8051 https://github.com/nestjs/nest/pull/8126
Added basically the same text from the Configuration example https://docs.nestjs.com/techniques/configuration#use-module-globally
=> docs(cache): add info about using the module globally

src/app/common/social-wrapper/social-wrapper.component.html, src/app/homepage/header/header.component.html, src/app/homepage/header/header.component.scss
On the header of the website, we have two accessibility issues : 
* the burger menu (on the top left), is not accessible via the keyboard
* The social media icons do not have text alternatives
* the burger menu (on the top left), is accessible via the keyboard
* The social media icons have text alternatives
=> Improve Accessibilty of the header

content/microservices/grpc.md
=> docs: fix typo grpc.md

content/faq/errors.md
No explanation about the dependency "dependency"
We now have a small explanation about what dependency "dependency" means.
=> feat:  add mention of `dependency` dependency errors

content/graphql/quick-start.md
- [ x] Docs
graphql@16 will break the server and is not compatible with the @nestjs/graphql module
Add a fixed version of graphql to graphql@^15 
- [ x] No
=> Add graphql version ^15

content/exception-filters.md
There aren't examples in the docs regarding using the `HttpAdapter` interface to write a platform-agnostic code
<details>
<summary>current version</summary>
</details>
I think the ['catch everything' interceptor example](https://docs.nestjs.com/exception-filters#catch-everything) is a good case on how we can write a platform-agnostic code. And also because the old code is almost equal to the [first example](https://docs.nestjs.com/exception-filters#catch-everything) so there wasn't much learning of the capabilities of NestJS (like being platform-agnostic) after reading both examples in there. Thus I changed it to:
=> doc: replace 'catch everything' example with a platform-agnostic one

content/fundamentals/unit-testing.md
No docs about the new [auto-mocking feature](https://github.com/nestjs/nest/pull/6277) 
We have docs :page_with_curl:
=> feat: add new documentation around auto-mocking capabilities

content/faq/serverless.md
Issue Number: https://github.com/nestjs/nest/issues/8639
Without additional config changes to `terser-webpack-plugin`, the production build for serverless doesn't work properly.
This PR adds the necessary configuration to the docs.
=> Add terser config to Serverless

content/microservices/redis.md
We are not yet Redis 4 compatible please see https://github.com/nestjs/nest/issues/8710
Issue Number: https://github.com/nestjs/nest/issues/8710
=> docs(redis): use Redis v3

content/discover/who-uses.json
Issue Number: No issue number related to this MR
=> docs(who-uses): Added dyrector.io to the list

content/techniques/http-module.md
=> docs(http-module): fix configService method

LICENSE
Update license 2022
This PR, update license 2022
=> docs(license): update license

content/middlewares.md
i removed .ts extensions because it cose error `An import path cannot end with a '.ts' extension. Consider importing './cats/cats.controller' instead.ts(2691)`
=> fix: .ts extension

content/microservices/rabbitmq.md
amqp-connection-manager was updated to version 4.0.0 3 days ago. It is not working well in case when connection is refused. Warning/error logs are absent. 
Version 3.9.0 of amqp-connection-manager is ok
=> Breaking change

content/microservices/rabbitmq.md
Reverts nestjs/docs.nestjs.com#2157
=> Revert "Breaking change"

src/app/homepage/newsletter/services/newsletter.service.ts
Remove method `empty()` because deprecated with RxJS version 6.x, I replaced it with the `EMPTY` constant.
This PR, remove method `empty()` because deprecated with RxJS version 6.x, I replaced it with the `EMPTY` constant.
=> chore(): improvement

content/websockets/gateways.md
Some external links to socket.io are invalid.
Fixed broken links.
=> docs(websockets): fix invalid links

content/security/helmet.md
Doc contains incorrect information about the number of middleware functions contained in the helmet library
Issue Number: #2165
Fixed doc info about number of middleware functions contained in the helmet library
=> Docs: change the number of middleware functions contained in helmet lib

content/graphql/federation.md
Added links for graphql federation examples 
- [code-first](https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first)
- [schema-first](https://github.com/nestjs/nest/tree/master/sample/32-graphql-federation-schema-first)
This PR,  added links for graphql federation examples.
=> docs(graphql): added links for graphql federation examples

content/interceptors.md
=> docs(interceptors): Adhere throwError usage to new method signature

content/security/rate-limiting.md
=> docs(rate-limiting): broken fastify reference link

content/security/helmet.md
=> docs(helmet): broken fastify reference link

content/guards.md, content/interceptors.md, content/pipes.md
Issue Number: (https://github.com/nestjs/docs.nestjs.com/issues/2202)
=> docs(guards, interceptors, pipes): wording fix

content/graphql/quick-start.md
=> docs(graphql): fix installation instructions typo

content/fundamentals/circular-dependency.md
After spending a couple of hours debugging an issue with circular dependencies and Scope.REQUEST, I had some conversations over Discord and it was agreed that adding the following clarification will be helpful.
=> Clarify circular dependency usage with Scope.REQUEST

content/websockets/adapter.md
Issue Number: #9158
This PR, update for extend socket.io( see [PR](https://github.com/nestjs/nest/pull/9158)), since the `socket.io-redis` package has been renamed to `@socket.io/redis-adapter`.
This PR, update for extend socket.io( see [PR](https://github.com/nestjs/nest/pull/9158)), since the `socket.io-redis` package has been renamed to `@socket.io/redis-adapter`.
=> docs(websockets): update for extend socket.io

content/exception-filters.md
There is a typo in the [exception filters](https://docs.nestjs.com/faq/http-adapter#in-context-strategy) page. 
Change reference name: `HttpServer` -> `HttpAdapter`
[Cross reference](https://docs.nestjs.com/faq/http-adapter#in-context-strategy)
=> docs(exception-filters): fix typo

content/first-steps.md
There is no mention on how to start server such that it reloads itself on file changes in **First Step Guide**.
Mentioned the use of:
```bash
$ npm run start:dev
```
For easy reloading of server
=> Docs: Mentioning npm run start:dev command in first steps guide

content/fundamentals/dependency-injection.md
No documentation regarding the _optional dependencies in factory providers_ feature added here: https://github.com/nestjs/nest/pull/9227
<details>
<summary>currently</summary>
</details>
=> docs(fundamentals): add docs on optional dependencies

src/app/homepage/header/header.component.html, src/app/homepage/header/header.component.scss, src/app/homepage/homepage.component.scss, src/app/homepage/menu/menu.component.scss, src/app/shared/components/toc/toc.component.scss
=> chore(): add top banner

src/app/homepage/header/header.component.scss
The top-bar text is not visible at dimension 280 x 653
=> docs: fix topbar responsiveness

content/discover/who-uses.json
Added PolygonSoftware to list of contributors, a software StartUp and University SpinOff from Switzerland and official sponsor of NestJS through OpenCollective.com
=> docs(who-uses): add PolygonSoftware

content/websockets/gateways.md
=> docs: Adjust grammatical errors in gateways.md

README.md
Update logo readme
This PR, update logo readme 
A little proposal, what do you think about it?
Not more beautiful just the logo(vedi screenshot)?
=> docs(): update logo readme

content/discover/who-uses.json
Who uses the Nest.js page in docs now contains [With](https://bewith.io).
=> docs(who-uses): add bewith.io to the list

content/websockets/adapter.md
=> docs(websockets): update adapter.md

content/fundamentals/unit-testing.md
Issue Number: closes #2258
Enhances one code snippet of unit testing page to clarify that `ModuleMocker` comes from `jest-mock` package
=> docs(fundamentals): clarify the source of `ModuleMocker` class

content/components.md
Add a link for IoC and one small grammatical change.
N/A
Docs change
=> docs(components.md): add IoC link and determiner

content/security/rate-limiting.md
Improvements in the customization section for rate-limiting 
This PR, introduces improvements in the customization section for speed limiting, as the customization part lacked a "practical" example to better understand the operation, otherwise you must always see the readme of the `@nestjs/throttler` package.
=> docs(rate-limiting): improvements in the customization section

content/techniques/cookies.md, content/techniques/sessions.md
Fastify plugin registration happens asynchronously and should be awaited.
Closes #2265
=> docs: fastify plugin registration should be awaited

content/techniques/caching.md, content/techniques/cookies.md, content/techniques/mongo.md, content/techniques/sessions.md, content/techniques/validation.md
=> docs: add links to dependencies

content/graphql/interfaces.md
---
Everything is mentioned here: https://github.com/nestjs/docs.nestjs.com/issues/2092
=> docs(graphql): `interface resolvers` section

content/cli/usages.md
Issue Number: [#2281](https://github.com/nestjs/docs.nestjs.com/issues/2281)
Fixed table format.
=> refactor: broken table in the nest update options

content/recipes/prisma.md
MongoDB has full, non-preview support, and CockroachDB is in preview version.
Source: https://www.prisma.io/ (Hero element)
```text
Prisma currently supports PostgreSQL, MySQL, SQL Server, SQLite and MongoDB (preview).
```
```text
Prisma currently supports PostgreSQL, MySQL, SQL Server, SQLite, MongoDB and CockroachDB (Preview).
```
=> docs: update Prisma docs with supported databases

content/microservices/basics.md
=> docs(microservices): add `await` on `app.listen()`

content/recipes/terminus.md
Issue Number: https://github.com/nestjs/terminus/issues/1831
Better description
=> docs(terminus): more explicit guide for HTTPHealthIndicator

content/techniques/queues.md
The sample shows a for loop doing something and then reporting job progress. The loop ends at 100 and on each iteration 10 is added to the progress. That will lead to a progress report greater than 100.
From 1 to 100 add 1 to the progress on each iteration
=> docs(queues): fix consumer snippet progress sample

content/graphql/scalars.md
Adding documentation on how to register a custom scalar. This is different from the existing documentation that merely describes how to _override_ a built-in scalar. Fwiw, some of this is covered already in the "schema-first" section, but being there, I did not realize how relevant it was until I spent a lot of time doing outside research and troubleshooting. This adds more clarity for those choosing the "code-first" approach.
=> docs: how to build or import a custom scalar

content/microservices/kafka.md
Issue Number: #7259
Update Documentation to introduced changes for producerOnlyMode
PR for the changes: https://github.com/nestjs/nest/pull/9457
=> docs(microservices) Update kafka microservices on optional consumers

content/techniques/sql.md
=> docs(): update to the latest version of typeorm

content/techniques/validation.md
Fix the description of the following properties:
skipUndefinedProperties
skipNullProperties
skipMissingProperties
=> docs(validation): Correct description of some options listed in validatorOptions table

content/faq/raw-body.md, src/app/homepage/menu/menu.component.ts, src/app/homepage/pages/faq/faq.module.ts, src/app/homepage/pages/faq/raw-body/raw-body.component.ts
Issue Number: #2310 
This PR adds a section in `FAQ` on how to enable the raw body option and how to use it on your controllers.
The text is very barebones. It's just an initial commit to get things started. If necessary, we could add recipes on how to use this technique to validate Stripe or Shopify webhooks.
=> docs(faq): add raw body option usage to faq

content/openapi/introduction.md, content/security/helmet.md, content/techniques/compression.md, content/techniques/cookies.md, content/techniques/mvc.md
Issue Number: 
https://github.com/nestjs/nest/issues/9542
Renamed fastify plugins:
- `@fastify/cookie`
- `@fastify/compress`
- `@fastify/swagger`
- `@fastify/helmet`
- `@fastify/static`
=> docs(techniques): renamed fastify plugins

content/openapi/introduction.md, content/security/helmet.md, content/techniques/compression.md, content/techniques/cookies.md, content/techniques/mvc.md
Reverts nestjs/docs.nestjs.com#2296
=> Revert "docs(techniques): renamed fastify plugins"

content/microservices/kafka.md
=> docs(v9): add kafka retriable exception section

content/faq/hybrid-application.md, content/microservices/redis.md
=> docs(v9): update redis transporter to use ioredis

content/openapi/introduction.md, content/security/helmet.md, content/techniques/compression.md, content/techniques/cookies.md, content/techniques/mvc.md
Issue Number: 
https://github.com/nestjs/nest/issues/9542
https://github.com/nestjs/docs.nestjs.com/pull/2296
https://github.com/nestjs/docs.nestjs.com/pull/2348
Renamed fastify plugins:
- `@fastify/cookie`
- `@fastify/compress`
- `@fastify/swagger`
- `@fastify/helmet`
- `@fastify/static`
Add the label `status blocked` until the next major version of NestJS is released (v9) 😻
=> docs(): renamed fastify plugins

content/fundamentals/provider-scopes.md
INQUIRER usage is undocumented.
Issue Number: #937
Added usage example and brief description.
=> docs(provider-scopes): add documentation for `INQUIRER` scope

content/migration.md, content/openapi/introduction.md
=> docs(): update migration guide, list breaking changes

content/microservices/grpc.md
Update ServerUnaryCall generic to reflect breaking changes from `@grpc/grpc-js`.
```
export declare type ServerUnaryCall<RequestType, ResponseType> = ServerSurfaceCall & {
request: RequestType;
};
```
N/A
=> docs(microservices/grpc): fix ServerUnaryCall generics

content/cli/overview.md
Issue Number: in favor of https://github.com/nestjs/nest-cli/pull/1699
No docs on `update` command
=> docs: drop `update` command from cli page

package-lock.json, package.json
Update version `@angular/flex-layout` 14.x
=> chore(deps): update version @angular/flex-layout

content/openapi/introduction.md
https://github.com/nestjs/swagger/pull/1886
According to this PR https://github.com/nestjs/swagger/pull/1886 , SwaggerCustomOptions are identical for both routing platforms.
=> docs(openapi): remove fastify options part

content/first-steps.md
follow the https://docs.nestjs.com/migration-guide#nodejs
indicates that Nest supports nodejs v12+
=> docs(first-steps): update nodejs minimum version to v12

content/security/helmet.md
This fixes the issue mentioned here: https://github.com/nestjs/docs.nestjs.com/issues/2395
=> Adjust instructions for NestJS 9

content/techniques/mongo.md
In npm 5.0+, the save flag is the default option
=> docs(mongo) :  update install code syntax

content/fundamentals/dynamic-modules.md
=> Fix typo `facilities`

content/recipes/terminus.md
=> docs(terminus): add disk, memory and http.responseCheck

content/cli/usages.md
=> docs(usages): fix minor typo on CLI options

content/security/helmet.md
Docs are outdated, don't work with `helmet` 5+.
Docs correctly show how to use `helmet` 5+.
See changelog: https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#500---2022-01-02
=> docs(security): update import statement to helmet version 5

content/microservices/kafka.md
Issue Number: [9949](https://github.com/nestjs/nest/issues/9949) (of nestjs itself)
=> docs (microservices): add documentation for KafkaContext.heartbeat usage

content/fundamentals/dependency-injection.md
I changed "can resolves" to "can resolve"
=> Fixed typo on the custom providers page

content/fundamentals/dynamic-modules.md
remove additional x from exxample
N/A
N/A
Just a minor typo to fix
=> chore(fundamentals): fix typo

content/techniques/streaming-files.md
Mention the `@Header()` decorator as an alternative to `res.set`
=> docs(techniques): enhance `StreamableFile` code snippet

content/techniques/mongo.md
We don't mention the use of `@InjectModel()` with a connection name
Issue Number: https://github.com/nestjs/mongoose/issues/1460
We mention that with a named connection and `@InjectModel()` you need to specify the connection name
=> feat: add doucmentation on injecting a model with a named connection

content/modules.md
=> Delete redundant question mark

content/graphql/quick-start.md
Currently the installation guide is indicating incorrect package versions or even missing dependencies to be installed
By following the guide for using Nest with GraphQL, Fastify and Mercurius, the developer should be able to run the project without getting an error or alert about missing dependencies
=> docs(graphql): add correct dependencies to use with fastify and mercurius

content/recipes/prisma.md
fix preview link to supported databases
fix docs (add a link to prisma.md)
=> docs(recipes): add link to prisma preview databases

content/techniques/task-scheduling.md
@nestjs/schedule library dependency node-crone changed to cron to reflect correct dependency name
- [x ] Docs
Correct library name
- [x ] No
=> docs(Task scheduling): Updates @nestjs/schedule dependency name

content/graphql/federation.md
=> Fix typo on graphql/federation page

content/techniques/sql.md
InjectConnection and getConnectionToken are marked as deprecated now and replaced with DataSource equivalents, but the docs were not changed yet
=> Replace inject connection with dataSource

content/techniques/sessions.md
=> docs(session): update fastify secure session import

content/security/csrf.md
Update package `csrf` for `fastify` see here: https://github.com/fastify/csrf-protection
=> docs(security): update package csrf for fastify

content/security/authorization.md
Plural nouns are bound to a singular verb conjugation.
Grammar fixed.
=> docs(security/authorization): fix small grammar error

content/recipes/cqrs.md
Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/2476
Add some hint about event handler usage
=> docs(cqrs): add some hint about event handler usage

content/recipes/mongodb.md
Adding an example of referring to mongodb recipes may be helpful to people using NestJS for the first time. 😻
=> docs(recipes): added link for example mongodb

content/techniques/mongo.md
Update documentation to show that we are targeting the `CatsModule` when using multiple databases
=> FIx Documentation

content/fundamentals/unit-testing.md
=> docs(unit-testing): added missing results declaration

content/graphql/federation.md
=> docs(graphql): add federation 2 doc

content/techniques/file-upload.md
add more details about file type detection by FileTypeValidator
Issue Number: #2497
=> docs: clarify FileTypeValidator warning

content/cli/workspaces.md
new field `flat` is undocumented
document `flat` field for `generateOptions`
https://github.com/nestjs/nest-cli/pull/1805
=> docs(workspaces): document flat field for generateOptions

content/recipes/sql-typeorm.md
update name of magic string used to correctly reflect code it is referencing
N/A
N/A
N/A
=> update name of magic string used

content/discover/who-uses.json
We use Nestjs and want to be listed at /discover
EverShop is listed at /discover
=> docs(who-uses): adding evershop.io

content/exception-filters.md
add docs explaining how to use the new `options` object containing both the `cause` and `description`.
Issue Number: NestJS [#10392](https://github.com/nestjs/nest/issues/10392#event-7752369498)
=> docs(exception-filters): docs for error options

content/faq/errors.md
Reverts nestjs/docs.nestjs.com#2532
=> Revert "docs(faq): update unknown dependency error msg"

content/security/csrf.md
The express CSRF package is suggested.
The express CSRF package is deprecated.
=> docs(csrf): mark express package as deprecated

content/pipes.md
Removed the types for joi package(`@types/joi`) why is deprecated see [here](https://www.npmjs.com/package/@types/joi)
=> docs(overview): removed the types for joi package

content/faq/raw-body.md
The example contains syntax error
This pr fixes the syntax error by adding the missing comma
=> docs(raw-body): add comma before options

content/techniques/http-module.md
=> docs(techniques): Update http-module.md

content/faq/raw-body.md
=> docs(faq): mention body parser on 'raw body' feature

content/exception-filters.md
The indentation in the code example is off.
Fixed indentation in the code example.
=> docs(exception-filters.md): fix indentation for HttpException error options example

content/recipes/repl.md
Missing information about running REPL in watch mode and preserving it's history between reloads.
Issue Number: https://github.com/nestjs/nest/issues/10476
There is new section `Watch mode` in REPL's docs describing how to run in watch mode and how to preserve the history.
=> docs(repl): watch mode

content/discover/who-uses.json
E-Design is listed at /discover
=> docs(who-uses): adding e-design.ca

content/faq/errors.md
=> docs(faq): update unknown dependency error msg

content/faq/request-lifecycle.md
- [] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
=> docs(faq): Capitalize @usePipes decorator

content/cli/libraries.md, content/cli/workspaces.md
Proposal:
- Added the `$` symbol in some code snippets regarding terminal commands, bringing them in line with the rest of the documentation, on the following pages:
- `content/cli/workspaces.md`
- `content/cli/libraries.md`
=> docs(cli): update snippets code

content/exception-filters.md
=> docs(exception-filters): fix grammar

content/exception-filters.md, content/faq/request-lifecycle.md
Add documentation to caveat when using catch all filter
Adding documentation around Catch Everything filter
=> docs Update exception-filters docs with caveats when using Catch All filter

content/controllers.md
Docs fail to call out important fact regarding route definition order, when defining route parameters. 
The importance of route parameter order is now called out.
=> docs(controllers): add warning about route parameter ordering

content/fundamentals/provider-scopes.md
Emphasizes that, for durable providers, the `REQUEST`/`CONTEXT` will not be defined
=> docs(fundamentals): minor adjustments to clarify the behavior of durable providers

content/security/helmet.md
The suggested configs for CSP didn't work for me. However, after some adjustments, what I'm suggesting as change worked for me.
=> Fix: correct config for csp

content/techniques/task-scheduling.md
Issue Number: https://github.com/nestjs/schedule/issues/1053
Update the docs for according to the new PR I created.
https://github.com/nestjs/schedule/pull/1100
=> docs(task-scheduling): Update new disabled flag on cron job

content/pipes.md
=> docs(pipes): Add more detail for Joi Schema reference section

content/fundamentals/unit-testing.md
Issue Number: closes https://github.com/nestjs/nest/issues/10159
Add mention on limitation on auto mocking REQUEST and INQUIRER providers
---
Also, mention the limitation of `.overrideProvider` on unique tokens exported by `@nestjs/core`
=> docs(fundamentals): add mention on limitation of auto mocking & overrideProvider

content/techniques/logger.md
updated code snippets in the section logger 
In the code snippets changed `ApplicationModule` in `AppModule`
=> chore(techniques): updated code snippets in the section logger

content/fundamentals/lifecycle-events.md
Added info about execution order of `onModuleInit()` and `onApplicationBootstrap()`.
=> docs(onmoduleinit): add info about onmoduleinit execution order

content/microservices/custom-transport.md
Issue Number: [Issue](https://github.com/nestjs/nest/issues/10240)
Added in mention of the RxJS stream behaviour when using a interceptors and a custom transport strategy.
=> docs(microservices): add mention of rxjs when using interceptors

content/recipes/terminus.md
Added mikroorm health indicator for terminus  ❤️ 😻
see this PR https://github.com/nestjs/terminus/commit/fe66c6768e6c8d5d0ae07c695937baf5db9b2977
=> docs(): add mikroorm health indicator

content/openapi/cli-plugin.md
Closes #1959
Issue Number: #1959 
Added docs to address the issue as mentioned in issue description
=> docs(openapi): handle mapped-types and add build steps

content/security/rate-limiting.md
no file name provided
file name provided
=> docs(rate-limiting): add file name

content/discover/who-uses.json
We use Nest on couple services at https://tarken.ag :smiley_cat:
=> docs(who-uses): add tarken.ag

content/security/helmet.md
The hint says to change the import to what it already is.
Removed the hint.
=> docs(helmet): Remove redundant hint

content/graphql/quick-start.md
Proposals:
- Added link for `graphql-mercurius` example.
- Removed dependencie `fastify` for mercurius installation, since you just need to install `@nestjs/platform-fastify`, for more information see `package.json` of this [example](https://github.com/nestjs/nest/blob/master/sample/33-graphql-mercurius/package.json)
=> docs(graphql): update mercurius integration

src/app/homepage/menu/menu.component.ts
=> docs(techniques): make `configuration` to be the first item in the list

package-lock.json, package.json
When I resolved the conflicts in this PR #1996, I must have forgotten to remove it, 😅 although it is strange that because I removed it in the previous commit. 
Sorry 🙏🏻
=> chore(): remove dependencie tslint

content/fundamentals/provider-scopes.md
- [X ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
there is syntax error in documentation for the durable provider.
update with correct working example.
=> typo in durable providers example

content/recipes/terminus.md
It throws an error that `axios` can't be found
It doesn't show the error
=> docs(terminus): include axios as a package to install

content/middlewares.md, content/techniques/performance.md
Proposal:
- Added an example and a warning to specify how the middleware works in `fastify`, given that it has been discussed many times in the Discord channel, I thought I'd document it 🙌
=> docs(): update middlewares for fastify

content/security/rate-limiting.md
=> Fix a typo in security/rate-limiting.md

content/fundamentals/dynamic-modules.md
=> docs: added missing imports in `dynamic-modules.md`

content/devtools/overview.md
that devtools looks awesome btw :cat:
=> docs(devtools): fix minor markdown syntax typo

content/techniques/sql.md
The documentation and the code was merged.
https://docs.nestjs.com/techniques/database#typeorm-transactions
=> docs(techniques): Fix Database page content

content/cli/overview.md
Proposals:
- Renamed the link for `npx` because the repository is archived now and integrated on the `npm cli`. 
- Added hint for using nestjs cli without using it globally, lately many users on discord encountered errors in the cli is not installing it globally solved the problem, so I think documenting it can help people.
=> docs(cli): update overview

content/techniques/sql.md
Codeblock will not overlap with the text
Fixes the issue that the codeblock is including other text
=> fix(docs/techniques/database): fix codeblock in section subscribers on page database

content/graphql/quick-start.md
Updated small parts of the documentation for Apollo v4
=> docs(graphql): update quick-start.md

content/faq/hybrid-application.md, content/microservices/basics.md, content/microservices/kafka.md, content/microservices/nats.md
- provide `MicroserviceOptions` type explicitly in code examples
=> docs: provide option types for microservice in examples

src/index.html
Proposal:
- Updated version for `font-awesome` to 5.15.4  
- Thanks to the use of v5.15.4 of `font-awesome`, the icon discord has been updated (See screenshot)
Before:
After:
=> chore(): update icon for discord channel

content/techniques/versioning.md
=> docs(versioning): add closing curly brace

content/techniques/sql.md
- The type return of the function `findOne` of UsersService is incorrect.  The function return is `Promise<User>` but `this.usersRepository.findOneBy({ id })` returns a `User` or `null` if no user with the matching id is found. This raises an error when I try to follow along the documentation
- Also, the parameter `id` of the `remove` function for UsersService is a `string` which is inconsistent with all the other functions of UsersService where the parameter `id` is a `number`
- The type return of the function `findOne` of UsersService is `Promise<User | null>`
- The parameter `id` of the `remove` function for UsersService is a `number`
This is my first contribution …
=> docs(database): fix TypeScript error for UsersService

content/techniques/serialization.md
mention this behavior: https://github.com/nestjs/nest/pull/7911
=> docs(techniques): add mention on streamable files responses when using built-in serialization

content/recipes/terminus.md
The code snippet in terminus has some missing imports
It adds missing imports
=> docs(terminus): add missing imports

content/cli/usages.md
Issue Number: https://github.com/nestjs/nest-cli/issues/1683
=> docs: add spec-file-suffix option to cli usage docs

content/microservices/kafka.md
```ts
const originalMessage = context.getMessage();
const { topic, partition, offset } = originalMessage;
```
```ts
const originalMessage = context.getMessage();
const { headers, partition, timestamp } = originalMessage;
```
```ts
const { offset } = context.getMessage();
const partition = context.getPartition();
const topic = context.getTopic();
```
```ts
const originalMessage = context.getMessage();
const partition = context.getPartition();
const { headers, timestamp } = originalMessage;
```
=> docs: Fix kafka get message

content/discover/who-uses.json
[remato.com](https://remato.com) is not listed on the "Who is using Nest" page.
[remato.com](https://remato.com) is listed on the "Who is using Nest" page.
=> docs(who-uses): add remato.com

content/recipes/swc.md
=> docs(swc) add vitest integration section

content/security/helmet.md
The Apollo Sandbox does not render **at all** (due to CSP errors seen in the Dev Tools) when the Sandbox is configured [according to the NestJS docs](https://docs.nestjs.com/graphql/quick-start#apollo-sandbox) and when `helmet` is being used in its default configuration.
The Sandbox renders correctly.
=> Update helmet.md to work with Apollo v4 and Apollo Sandbox

README.md
=> Remove some irrelevant markdown tags from readme

content/recipes/automock.md
`TestBed.create(Service).mock(Dependency)` returns `Override<Dependency>` which has method `using` not `use`
Updated the code example
=> docs(automock): fix typo in code example

content/controllers.md
=> nest g controller cats -> nest g controller [name]

content/cli/workspaces.md
Adds docs for https://github.com/nestjs/nest-cli/pull/2070
=> docs(workspaces): add manual restart option to global compiler options

content/introduction.md
[Comment in Issue #2057](https://github.com/nestjs/nest-cli/issues/2057#issuecomment-1537117486)
[Invitation for PR](https://github.com/nestjs/nest-cli/issues/2057#issuecomment-1549083356)
=> docs: correct hint's description of --strict flag

content/fundamentals/circular-dependency.md
=> docs(changes): show second example for Module forward reference section

content/discover/who-uses.json
Adding a new company to the who uses documentation.
We use Nest.js at @rembergtech and are really happy.
=> docs(who-uses): add remberg

content/first-steps.md, content/fundamentals/unit-testing.md, content/microservices/redis.md, content/migration.md, content/techniques/configuration.md
=> docs: v10 changes

content/techniques/task-scheduling.md
=> docs(grammar): correct grammar error

content/recipes/terminus.md
In `Recipes > Health checks`
Omitted `import Dependencies` for TypeScript.
So I just add this
=> docs(terminus): added `import { Dependencies }` for TypeScript

content/techniques/cookies.md
This PR adds code formatting for `req.cookies` in cookies docs.
=> fix(docs): added formatting for req.cookies

content/recipes/swc.md
Currently, the example code for Jest + SWC setup leads to errors (found and resolved by [GabrielGasp](https://github.com/GabrielGasp))
Issue Number: https://github.com/nestjs/nest/issues/11804
=> docs(swc): change jest + swc example setup

content/discover/who-uses.json
No link in "discover" to a company which is a big fan of NestJS
Adding link to the company: digando.com
=> docs(who-uses): add digando.com

content/first-steps.md
Issue Number: #2474
Linting and formatting documented
=> Document code linting and formatting

content/openapi/other-features.md
PR: https://github.com/nestjs/swagger/pull/2176
=> docs(openapi): add descriptions about adding global parameters

content/recipes/terminus.md
- [] Other... Please describe:
Proposal:
With the new version of Terminus( v10 ) a new Health Indicator for Prisma has been added, see here: https://github.com/nestjs/terminus/blob/master/lib/health-indicator/database/prisma.health.ts#L37
N/A
=> docs(terminus): added prisma health indicator

content/discover/who-uses.json
Novu.co is not listed in discover companies section
Novu.co **is** listed in discover companies section
=> docs(who-uses): add novu.co

content/recipes/async-local-storage.md
In the code examples included in the Async Local Storage documentation, 'this' keyword is missing.
Added 'this' keyword
=> docs(recipes): add missing 'this' keyword

content/techniques/sql.md
better to use is instead of TypeORM it's
=> [docs] typo fix

content/openapi/introduction.md
Update the documentation based on https://github.com/nestjs/swagger/pull/2505
=> docs(@nestjs/swagger): add `patchDocumentOnRequest` option based on https://github.com/nestjs/swagger/pull/2505

content/recipes/swc.md
Tiny fix for an example. The `ReadonlyVisitor` is not exported from the package root, so it and its dependencies are not pulled in accidentally for regular users.
=> docs(recipes/swc): fix import path

content/techniques/cookies.md
https://docs.nestjs.com/controllers#appendix-library-specific-approach is used in techniques/cookies.md and is not a valid anchor.
https://docs.nestjs.com/controllers#library-specific-approach points to the correct section
=> docs(link): Correct invalid anchor in link in cookies.md

content/security/rate-limiting.md
- [x ] Docs
Small typo in the security/rate-limiting.md page
Typo fixed.
- [x ] No
=> docs(typo): Fixes typo in rate-limiting.md

content/exception-filters.md
Isn't that clear that exception filters should not be used in services
=> docs: clarify on where exception filters can be used

content/recipes/swc.md, package-lock.json
=> docs(swc): Adds precision on managing nest circular deps

content/openapi/cli-plugin.md
=> docs(cli-plugin.md): Clarify role of Swagger plugin and class-validator in validation.

content/faq/multiple-servers.md
Issue Number: 2804
https://github.com/nestjs/docs.nestjs.com/issues/2804
Documentation about shutting down the HTTP server when starting one ourselves
=> document shutdown of http server

content/faq/request-lifecycle.md
Grouped request lifecycle by nest concept, such like: guard, interceptors
Adjust the structure of the nest request lifecycle based on the core concepts of nest to make it easier to understand
=> docs(request-lifecycle.md): update request lifecycle

content/techniques/performance.md
Issue Number: https://github.com/nestjs/nest/issues/11815
Documentation for the fastify route config feature
=> docs(fastify): fastify route config docs

content/techniques/task-scheduling.md
Proposal:
- Removed `@types/cron` dependency from required dependencies, because deprecated see here: https://www.npmjs.com/package/@types/cron 
See also this PR here: https://github.com/nestjs/schedule/pull/1374 😉
=> docs(task-scheduling): updated the required dependencies

content/controllers.md
Docs says that to redirect an HTTP request you must return a JSON object with a shape.
Docs says that to redirect an HTTP request you must return an interface that already exists at the framework, as proposed at PR12350 of Nest.
=> feat: update redirection docs for pr12350 on nest

content/security/rate-limiting.md
Docs are still for throttler v4
Docs are now for [throttler v5](https://github.com/nestjs/throttler/pull/1565) :tada:
I mean, v5 does, but those are all documented and that's literally what this PR is for. It does not break the docs site though :wink:
=> feat: update throttler for v5

content/openapi/operations.md
=> docs: update operations.md

content/techniques/configuration.md
No docs for the new `ConditionalModule` from `@nestjs/config`
Docs exist!
=> feat: docs for the conditional module

content/recipes/swc.md
Just an update to the dependency name
=> Update swc.md: @vitest/coverage-c8 to @vitest/coverage-v8

content/techniques/cookies.md
AvvioError: Plugin did not start in time: '() => cookie_1.default'.
Everything works fine
=> docs(cookies): fix @fastify/cookie code example

content/security/authorization.md
Current CASL links in old v5 version
New CASL links in v6 version
=> docs: Update casl.js.org linmks to v6

content/techniques/queues.md
=> Update queues.md - fix JS logic

content/security/rate-limiting.md
Noticed a missing comma in the rate-limiting docs for [Multiple Throttler Defintions](https://docs.nestjs.com/security/rate-limiting#multiple-throttler-definitions) code block. Fixed some other grammar issues as well. 
Typo fixes
=> fixed typos

content/security/cors.md
precise which package is used for cors for fastify-based nestjs apps
=> Update cors.md - add precision about fastify

content/discover/who-uses.json
=> Added aqreach.com website link in who-uses.json

content/techniques/logger.md
`fatal` log level is missing in docs
docs contains `fatal` log level
=> docs(logger): add fatal log level

content/techniques/performance.md
Document `@RouteConstraints` feature introduced in: https://github.com/nestjs/nest/releases/tag/v10.3.0
=> docs(fastify): Document `@RouteConstraints`

content/cli/usages.md, content/recipes/crud-generator.md
=> Update Docs to mention that CRUD Generation is a TS Only feature

content/techniques/http-module.md
=> chore: fix http-module.md grammar

content/faq/serverless.md
Serverless Express has moved to @codegenie/serverless-express.
=> Update "serverless-express" with the updated package

content/guards.md, content/pipes.md
=> docs: fix typos

content/components.md
=> Updated Angular's documentation link to Angular's new dev docs.

content/security/authentication.md
=> docs(authentication): Add missing typescript types

content/faq/serverless.md
=> docs(faq/serverless): fix 'in place' word

content/fundamentals/lazy-loading-modules.md, content/modules.md
- I have added new Angular redirections to different pages & added Angular links to some word instances.
=> New Angular links + formatting.

content/introduction.md
=> New angular website

content/devtools/ci-cd.md
=> docs(devtools/ci-cd): add 'manage-api-keys' link

content/discover/who-uses.json
Added Tesseract Pro to the list of companies using NestJS
=> docs: Added Tesseract Pro to list of companies using NestJS

content/microservices/basics.md
At this time the table containing the available options for the tcp transporter is not complete. The source code must be consulted to find the actual options.
All the available options are now listed with links to the interfaces to implement for `serializer` and `deserializer`.
=> docs(microservices): add to the table all available tcp options

content/fundamentals/provider-scopes.md
Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/2945
=> docs(fundamentals): clarify that injecting request provider makes the consumer request-scoped

content/microservices/kafka.md
This PR corrects a very minor typo on the Kafka - Microservices page.
=> Correct Kafka package typo

content/recipes/mikroorm.md
Updates the docs to match the current stable of MikroORM.
=> docs: update MikroORM recipe based on its v6 changes

content/openapi/introduction.md
=> docs: improve documentation about Swagger setup options

content/openapi/cli-plugin.md
=> added info to see about ts s metadata reflect

content/techniques/configuration.md
The example code for PORT validation in the configuration schema allows to accept any numeric value without enforcing constraints on valid port numbers.
The example code for PORT validation in the configuration schema is improved to only accept valid port numbers within the range of 0 to 65535.
Note: `@IsPort` from class-validator only works with string.
=> docs: improve configuration schema validation example

content/discover/who-uses.json
remove duplication - ibm appears twice
=> fix: remove duplication in who-uses

content/recipes/async-local-storage.md
=> docs(async-local-storage): fix anchor link

content/microservices/rabbitmq.md
- add missing docs for consumerTag.
- read more url fixes for queueOptions and socketOptions.
=> consumerTag description on rmq microservice configs 

content/techniques/logger.md
=> docs (logger): add missing Injectable decorator to custom logger service class

content/modules.md
Fixes #2976 
By making this adjustment, Connection provider is properly exported from exports array.
=> docs(modules): add missing exports array

content/recipes/terminus.md
=> Added link reference to Kubernetes

content/techniques/configuration.md
=> docs(Configuration): added missing imports in the documentation

content/discover/who-uses.json
Shows Kwanso URL on Discover Page
=> docs(discover): add kwanso url to discover page

content/guards.md
=> docs(guards): remove unecessary the

content/discover/who-uses.json
Added CMDN to the list of companies using NestJS
=> docs: Added CMDN to list of companies using NestJS

content/components.md
=> fix: add comment clarifying statement

content/exception-filters.md
Issue Number: #3017
The removed paragraph sort of duplicates what's already said above:
> Typically, you'll create fully customized exception filters crafted to fulfill your application requirements. However, there might be use-cases when you would like to simply extend the built-in default global exception filter, and override the behavior based on certain factors.
=> fix: remove redundant paragraph

content/techniques/logger.md
=> docs(): add importing injectable module

content/graphql/quick-start.md
Link in the GraphQL docs was outdated. It has been fixed in this PR
Updated graphQL yoga link to point to the correct repo.
=> Fixed link for graphQL yoga

content/security/authentication.md
N/A
This PR, fix hint blockquote color, see screenshot:
=> docs(authentication): blockquote hint color

content/guards.md
=> docs: tiny typo

src/app/app-routing.module.ts
Solves https://github.com/nestjs/docs.nestjs.com/issues/3031
=> fix: reload page on same url

content/techniques/streaming-files.md
Issue Number: closes #2938
see https://deploy-preview-3052--docs-nestjs.netlify.app/techniques/streaming-files#example
=> docs(techniques): add mention about available options of `StreamableFile`

content/application-context.md
no mention on how to use `app.select` over dynamic modules 
https://deploy-preview-3053--docs-nestjs.netlify.app/standalone-applications
=> docs: mention about accessing dynamic modules on standalone mode

content/recipes/repl.md
=> fix app module path in repl.md

content/techniques/mongo.md
=> fix(mongo): use correct semantics for an array field

content/discover/who-uses.json
=> docs: add new company to who-uses

content/fundamentals/provider-scopes.md
The sentence `Singleton scope is used by default, and need not be declared.` improved for for clarity and correctness.
=> docs(injection scopes): fix typo

content/discover/who-uses.json
- [x ] Docs
Updated user list
- [x ] No
=> Add DevITjobs

content/openapi/cli-plugin.md
=> docs(@nestjs/swagger): fix a typo

content/fundamentals/dependency-injection.md
at our Discord a person asked about the `OptionsProvider` as they thought that this provider is built-in one
a minor change that should help on clarifying that the class-based provider is just an example
=> docs(fundamentals): improve factory provider example code snippet

content/openapi/introduction.md
Update SwaggerCustomOptions.explorer description
Enhances the usage description for SwaggerCustomOptions.explorer.
This content references the "Load swagger from url" section in swagger-ui-express.
Update docs
Like Springdoc GroupedOpenApi
=> docs: Update SwaggerCustomOptions.explorer description

content/security/rate-limiting.md
Issue Number: #3094 
Updates the code displayed for the Websocket ThrottlerGuard implementation using `@nestjs/throttler` v6.
This has been in `@nestjs/throttler` for a while, as shown [here](https://github.com/nestjs/throttler/commit/7e990a38a57caeae456f7924ac3c7bed50237a31).
=> docs: update websockets throttler guard example

content/graphql/subscriptions.md
I have changed the return type to `Comment`.
=> docs(graphql/subscriptions): fix return type in sample code

content/fundamentals/unit-testing.md
=> docs(unit-testing): remove unnecessary types

content/security/rate-limiting.md
=> docs(Storages) ThrottlerStorage Community Redis repository url changed

content/introduction.md
Issue Number: attempt to close #1759
https://deploy-preview-3059--docs-nestjs.netlify.app/
=> docs: add mention how to create a bare minimum nestjs app from scratch

content/techniques/mongo.md
added a small section on how to start a new session using the connection object
=> docs(techniques/mongo): added sessions section

content/recipes/passport.md
=> Docs(passport): Passport-Local GraphQL Guard added

content/security/csrf.md
this version shows how to use csrf-csrf package for CSRF protection instead of the deprecated csurf package
=> docs(csrf): replace csurf with csrf-csrf

content/recipes/passport.md
Explains how to populate `authInfo` object during jwt validation.
Explains how to populate `authInfo` object during jwt validation.
=> docs(passport.md): explains express authInfo populate procedure 

content/recipes/prisma.md
The changes made in the new version of the markdown add information about configuring Microsoft SQL Server and Azure SQL Server for use with the Prisma ORM (Object-relational mapping) system. Here's a detailed explanation:
The summary section of the collapsible details section is updated from "Expand if you're using PostgreSQL or MySQL" to "Expand if you're using PostgreSQL, MySQL, MsSQL or Azure SQL". This change reflects the expanded scope of the content.
After the sections on PostgreSQL and MySQL, a new section is added on "Microsoft SQL Server / Azure SQL Server". This provides specific information about configuring these additional database systems for use with Prisma.
In the new section, code snippets are provided for the schema.prisma and .env files similar to the ones given for …
=> doc(prisma): add prsima connection to mssql and azure sql

content/techniques/mongo.md
Issue Number: [nestjs/mongoose:#2096](https://github.com/nestjs/mongoose/pull/2096)
Added the new `onConnectionCreate` option to the docs.
N/A
=> chore: added mongoose connection events

content/microservices/basics.md
There is no info for `registerAsync` which is more useful than `register` method in real applications
Add an example of `registerAsync` method.
=> docs: add registerAsync to microservices client section

content/techniques/mongo.md
Currently in the docs is no description how to use nestjs/mongoose with subdocuments.
Chapter is included now
=> docs: Added a chapter for subdocuments

content/openapi/other-features.md
[nest swagger issues](https://github.com/nestjs/swagger/issues/1810)
=> docs: update swagger-other-features docs

content/techniques/serialization.md
This serves to add docs for https://github.com/nestjs/nest/pull/10087 
It was a useful decorator I found whilst browsing the source code! Thought it would be great to add this in the main docs as it allowed for terser code.
=> docs(serialization): add serialize options docs

content/openapi/decorators.md
Support class decorator ApiParam and ApiQuery for Controller
PR Reference: https://github.com/nestjs/docs.nestjs.com/pull/1917
Support of Class Decorator ApiParam and ApiQuery for controllers
@nestjs/swagger PR: https://github.com/nestjs/swagger/pull/2213
=> feat(@nestjs/swagger): Support class decorator ApiParam and ApiQuery

content/recipes/necord.md
Recently, my MR was merged after along time and it has small problems with imports and wording. Also it need to fix one of api changes in Necord
Added:
- Imports
- File names
Fixed:
- Usage of `Values` was replaced with `SelectedStrings `
=> docs(recipes/necord): improve imports and wording

content/microservices/basics.md
Spelling mistake is fix in  microservice basic content (`docs.nestjs.com/content/microservices/basics.md`)
"When" spelling is wrong here.
Spelling is fix.
=> docs(documentation): Fix spelling mistake

src/index.html
=> chore(docs): set og:image to load from the https URL

content/graphql/interfaces.md
This took me a while to figure out why it is not working and I think it makes sense to document this.
=> docs(graphql): add hint for inheritResolversFromInterfaces to interface resolvers

content/deployment.md
Fixed grammatical typo in deployment.md
=> docs(deployment): Fixed type on deployment.md for mau

content/techniques/logger.md
=> Fix formatting of static method call

content/modules.md
There is a missing "s'' at the last word of the "Feature modules" paragraph [here](https://docs.nestjs.com/modules#feature-modules)
The "s" for plural has been added.
=> docs(overview/modules): english typo fix

content/techniques/file-upload.md
=> docs(validations/files): Add example for custom file validator

content/recipes/swc.md
=> Fix PluginMetadataGenerator import

content/recipes/prisma.md
The examples on the Prisma Recipe Note specifically the `REST` and `GraphQL` are wrong
Update the links to point to the current folders in the repo
=> docs(prisma): update prisma example links

content/websockets/adapter.md
Issue Number: https://github.com/nestjs/nest/pull/14127
=> docs(ws): add usage for setMessageParser method

content/techniques/sql.md
Updated sequelize docs reference links to version 6 docs
=> docs: update sequelize reference links to v6

content/openapi/cli-plugin.md
docs (openapi): add jest version info earlier
Add informing sentence to OpenAPI CLI Plugin Integration that upcoming snippet is for jest@<29
fixes #3160
Issue Number: #3160
=> docs (openapi): add jest version info earlier

content/websockets/adapter.md
=> docs(websockets): update adapter.md to fix grammar

content/discover/who-uses.json
Add GoFirmex in who-uses.json
Add GoFirmex as a company using nestjs
Add GoFirmex in Docs as a company using nestjs.
=> Add GoFirmex in who-uses

content/discover/who-uses.json
Adds formation.tech URL on discover page
=> docs(who-uses): add formation.tech

content/application-context.md
On [Standalone applications](https://docs.nestjs.com/standalone-applications) page, some links are incorrect and point to 404
This PR fixes the broken links so that they now point to valid docs pages
=> docs(standalone-apps): fix broken links

content/recipes/swc.md
The current link for $schema no longer works <https://json.schemastore.org/swcrc>
<https://swc.rs/schema.json> is the new correct URL.
=> docs(swc): update $schema json link 

content/techniques/task-scheduling.md
docs for https://github.com/nestjs/schedule/pull/1870/files
=> docs(schedule): add waitForCompletion

content/techniques/caching.md
KeyvRedis must be instantiated with KeyV, without this : _reconnectStrategy_ does not work and some typings are buggy
=> fix(techniques): caching

content/techniques/caching.md
In the @nestjs/cache-manager documentation it says to use reset(); but the correct option to delete the cache would be clear();
Now the doc will have the correct information.
=> docs(caching): update documentation to reflect method name change from reset to clear

content/migration.md, content/techniques/caching.md
https://github.com/nestjs/cache-manager/issues/629
The `Keyv` structure breaking change is documented.
=> fix(migration): caching Keyv breaking change

content/graphql/quick-start.md
Fix Apollo Server Constructor API broken link.
=> Update quick-start.md fix Apollo Server Constructor API broken link.

content/openapi/introduction.md
=> docs(@nestjs/swagger): update document reference for json-api

content/migration.md
The current behaviour performs an incorrect check for marking a service as down.
This change makes this check consistent with the earlier example and fixes the same.
=> docs(migration): fix logic for health indicator example

content/graphql/cli-plugin.md, content/openapi/cli-plugin.md, content/recipes/swc.md
Fixes #3205
Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/3205
=> docs(plugins): Clarify how options are provided

content/recipes/serve-static.md
It adds the recent change introduced in serve static module to help user find informations without digging into the code
=> docs(recipes): update ServeStaticModule documentation to reflect recent change on implementation with fastify adapter

content/exception-filters.md
=> docs(overview): add missing decorator

content/techniques/validation.md
=> docs(techniques): fix wrong TS type

content/discover/who-uses.json
=> docs: add user org

content/techniques/compression.md
Fixes issue with compression. Added types for compression package to fix typescript issue
=> docs(compression): add types to compresson install script

content/microservices/kafka.md
Closes #14664(https://github.com/nestjs/nest/issues/14664)
This PR updates the Kafka section of the NestJS documentation to include a sample implementation of the KafkaMaxRetryExceptionFilter.
This filter enables retry logic for Kafka events, ensuring that after a configurable number of retries (e.g., 5 retries), the event is skipped. Additionally, it provides a mechanism to execute custom logic via a skipHandler before committing the offset, allowing subsequent events to be processed smoothly.
- Added a sample code snippet demonstrating the usage of KafkaMaxRetryExceptionFilter.
- Explained the mechanism and use cases in the documentation.
Please review and let me know if further modifications are needed.
What kind of change …
=> docs(microservices): Add sample for KafkaMaxRetryExceptionFilter

content/openapi/cli-plugin.md
Issue Number: https://github.com/nestjs/swagger/pull/3362
Add `esmCompatible` to the swagger plugin options.
=> docs(openapi): add esm compatible option for swagger plugin

content/recipes/mikroorm.md
There is a few typos in MikroORM.
Fixed typos to improve readability.
=> docs(mikroorm): fix minor typos

content/techniques/configuration.md
This PR just aims to make a sentence in the [Configuration article](https://docs.nestjs.com/techniques/configuration) more fluent/readable in English :)
=> docs(configuration): rephrase sentence for clearer English

content/techniques/validation.md
All the other options have a period at the end of their description 😄 , but this one was missing it.
=> docs(validation): add missing period

LICENSE
Proposal:
- Update copyright year 2025 🔥
=> chore(license): update copyright year 2025

content/techniques/caching.md
This PR just corrects a weird sentence :)
=> docs(caching): correct weird sentence

content/techniques/streaming-files.md
Use the right anchor in a link in the [Streaming files article](https://docs.nestjs.com/techniques/streaming-files)
=> docs(streaming-files): fix link

content/techniques/caching.md
`miliseconds` => `milliseconds`
=> docs(caching): fix typo

content/openapi/introduction.md, content/openapi/types-and-parameters.md
typos on openapi swagger docs https://docs.nestjs.com/openapi/introduction
`SwaggerModule#createDocument()`
`SwaggerModule.createDocument()`
=> docs: fix typos in openapi swagger

content/security/rate-limiting.md
=> docs(rate-limiting): correct decorator name and usage

src/app/homepage/homepage.component.html
👋 thanks for maintaining this awesome project!
=> doc: fix typo in Support us footer

content/techniques/compression.md
=> docs(fastify): note use of correct types for setting up compression

content/security/authorization.md
Fix the note about the CASL special word `manage` to follow the same pattern as `all`.
=> fix(authorization): fix formatting of warning notice in authorization.md

content/techniques/caching.md
- [ X ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
- [ X ] Docs
Caching documentation shows an example of Redis store configuration not working because of typing errors.
Issue Number: #14580 nestjs/nest
Caching documentation shows an example of a working Redis store configuration.
- [ X ] No
The issue has been resolved by @Shen120, this PR updates the documentation with the solution provided
=> fix: Caching/Using alternative Cache stores - issue #14580 nestjs/nest

content/graphql/resolvers-map.md
=> docs: fix typo in code snippet
