nestjs/docs.nestjs.com

- package-lock.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/recipes/mockgoose/mockgoose.component.html
- src/app/homepage/pages/recipes/mockgoose/mockgoose.component.spec.ts
- src/app/homepage/pages/recipes/mockgoose/mockgoose.component.ts
I used majority of text from:
https://docs.nestjs.com/recipes/mongodb
> E2E Testing MongoDB application with Mockgoose.

- src/app/homepage/pages/recipes/sql-sequelize/sql-sequelize.component.html
Hi there. Just fixing a few typos while going through this page!
> Sequelize: (fix) a few typos

- src/app/homepage/pages/controllers/controllers.component.ts
Change for HttpCode instead of HttpStatus in get statusCode()
> Update controllers.component.ts mistype

- src/app/homepage/pages/custom-decorators/custom-decorators.component.ts
There are a conflict between custom-decorator called User and UserEntity (interface) called User. Any reader would get an error when import User from custom-decorator and User from Entity (or interface).
> fix(custom-decorators): Conflict

- src/app/homepage/pages/microservices/exception-filters/exception-filters.component.spec.ts
- src/app/homepage/pages/microservices/guards/guards.component.spec.ts
- src/app/homepage/pages/microservices/interceptors/interceptors.component.spec.ts
- src/app/homepage/pages/microservices/pipes/pipes.component.spec.ts
- src/app/homepage/pages/websockets/exception-filters/exception-filters.component.spec.ts
- src/app/homepage/pages/websockets/guards/guards.component.spec.ts
- src/app/homepage/pages/websockets/interceptors/interceptors.component.spec.ts
- src/app/homepage/pages/websockets/pipes/pipes.component.spec.ts
A few test files were importing non-existing classes. This PR fixes that.
> docs(nestjs): fix imports in test files of homepage module

- src/app/homepage/pages/controllers/controllers.component.html
I fixed some typos in the docs and also made some improvements here and there
> Fixes and improvements controllers docs

- src/app/homepage/pages/controllers/controllers.component.html
I made some changes to the way some phrases were built up so they read a bit smoother.
Please let me know if there's something you don't like about what I've changed. I'd be happy to change them.
> Rephrases on controllers 

- src/app/homepage/pages/techniques/sql/sql.component.html
- src/app/homepage/pages/techniques/sql/sql.component.ts
This commit adds documentation about the multiple connections support for the TypeOrmModule.
See nestjs/typeorm#8
> docs(@nestjs/common): Update the TypeOrmModule documentation

- src/app/homepage/pages/pipes/pipes.component.html
- src/app/homepage/pages/pipes/pipes.component.ts
This PR updates the `ValidationPipe` documentation according to https://github.com/nestjs/nest/pull/383
Let me know if you'd like me to add a more detailed example.
> docs(@nestjs/common): Update the ValidationPipe documentation

- src/app/homepage/pages/first-steps/first-steps.component.html
Make the whole ES6 thing more clear to reduce issues.
> create warning for ES6

- src/app/homepage/homepage.component.ts
Close menu only when width changes.
closes #55
> feat: check if the width is the same

- src/app/homepage/pages/techniques/configuration/configuration.component.html
- src/app/homepage/pages/techniques/configuration/configuration.component.ts
> Added how to use the ConfigService (Injection) & Advanced Configuration

- src/app/homepage/homepage.component.html
Was impossible to navigate to support subpage due to the missing slash.
> Fix incorrect routing to support page

- src/app/homepage/pages/techniques/mongo/mongo.component.html
The old link provided doesn't match with the documentation.
> Fix link to example of nestjs/mongoose module

- src/app/homepage/pages/microservices/grpc/grpc.component.html
see my PR https://github.com/nestjs/nest/pull/895
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> detail for @grpc/proto-loader

- src/app/homepage/pages/websockets/gateways/gateways.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Hey! The source (`@nestjs/websockets`) is valid in `develop` but has been changed to `@nestjs/common` on `master`.
> bugfix(websockets): hint for types source

- src/app/homepage/pages/controllers/controllers.component.html
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs change
```
The terminology _parse_ is used to describe converting an object to a JSON string.
The terminology _serialize_ is used to describe converting an object to a JSON string.
```
[ ] Yes
[x] No
```
JavaScript objects are serialized to JSON when returned as the response. Like `JSON.parse` vs `JSON.stringify`. I chose serialized because it's the terminology the spec uses but encode also works if you prefer.
I'm also not sure how to align my commit message to the …
> Correct terminology regarding JSON

- src/app/homepage/pages/techniques/security/security.component.html
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Minor typo
```
```
[ ] Yes
[x] No
```
> docs(@nestjs): Fix typo in csurf installation

- src/app/homepage/pages/components/components.component.html
- src/app/homepage/pages/graphql/resolvers-map/resolvers-map.component.html
- src/app/homepage/pages/middlewares/middlewares.component.html
Change "a `@Injectable()` ..." to "an `@Injectable()` ...".
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: documentation
```
```
[ ] Yes
[x] No
```
> docs: fix a typo

- src/app/homepage/pages/techniques/caching/caching.component.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: documentation
```
Issue Number: #152
```
[ ] Yes
[X] No
```
> docs(@nestjs) fixed cache options 'max' description (Closes nestjs/docs.nestjs.com/issues/152)

- src/app/homepage/header/header.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Fixed the link to StackOverflow in the header

- src/app/homepage/pages/techniques/caching/caching.component.html
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #156
Missing infomation of `cache-manager` while it's necessary for the new `cache` module.
```
[ ] Yes
[x] No
```
> docs: add installation for caching #156

- src/app/homepage/pages/techniques/performance/performance.component.html
- src/app/homepage/pages/techniques/performance/performance.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/145
new notice and a small code snippet
```
[ ] Yes
[x] No
```
Some white-space and due to lint enforcing and stuff like that, but nothing was broken nor anything like that.
I assumed it wasn't problematic, so here it is.
> docs: fastify inside docker 

- src/app/homepage/pages/techniques/mvc/mvc.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Typo fix in mvc.component.ts

- src/app/homepage/pages/exception-filters/exception-filters.component.html
- src/app/homepage/pages/exception-filters/exception-filters.component.ts
```
[ ] Bugfix
[ ] Feature
```
Doc explains not to instanciate a filter extending base filter and to always use annotations to inject
you can use a base filter and instance it yourself to use it as a global filter
```
[ ] Yes
[x] No
```
> docs(exception-filters): add sample how to use global filter using base filter

- src/app/homepage/pages/guards/guards.component.html
Wording update.
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix authorization/authentication wording

- src/app/homepage/pages/recipes/prisma/prisma.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/1107
```
[ ] Yes
[x] No
```
> fix: Fix formatting issue in graphqlconfig

- src/app/homepage/header/header.component.html
```
[ ] Bugfix
[ ] Feature
[x] Doc
```
> fix: change nest url from kamilmysliwiec to nestjs gh org

- src/app/homepage/pages/recipes/prisma/prisma.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: Update Prisma recipe

- src/app/homepage/pages/discover/who-uses/who-uses.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: added new company

- src/app/homepage/pages/techniques/mvc/mvc.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix a type in documentation
```
> docs: add missing apostrophe for mvc example

- src/app/homepage/pages/techniques/compression/compression.component.html
```
[x] Bugfix
[ ] Feature
```
The url to  fastify-compress  is wrong
The url to  fastify-compress is ok
```
[ ] Yes
[x] No
```
> Fix broken url

- src/app/homepage/pages/techniques/sql/sql.component.ts
fix missing imports array in techniques/database docs
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation fix
```
> docs: fix missing imports array

- src/app/homepage/pages/graphql/quick-start/quick-start.component.html
change `GraphQlModule` to `GraphQLModule`.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Typo
```
```
[ ] Yes
[x] No
```
> docs: fix typo in GraphQLModule documentation

- src/app/homepage/pages/techniques/authentication/authentication.component.html
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe: Documentation
```
Added 'to'
```
[ ] Yes
[x ] No
```
> Grammar fix

- src/app/homepage/pages/controllers/controllers.component.ts
```
[ ] Bugfix
[ ] Feature
```
Code example use `@Query` decorator but is not import from `@nestjs/common`
The example works if try it
```
[ ] Yes
[x] No
```
> (docs): Update code snippet to fix example

- src/app/homepage/pages/interceptors/interceptors.component.html
The text is about interceptors but the paragraph was copied from the guards.
```
[x] Bugfix
[ ] Feature
```
Text says "guard"
Issue Number: -
Text says "interceptor"
```
[ ] Yes
[x] No
```
> docs: replace wrongly copied word

- src/app/homepage/footer/footer.component.html
```
[x] Bugfix
[ ] Feature
```
year++;
```
[ ] Yes
[x] No
```
> bugfix: update the year in footer

- src/app/app.module.ts
- src/app/common/directives/header-anchor.directive.ts
- src/app/homepage/homepage.component.scss
```
[ ] Bugfix
[x] Feature
```
No anchor headings.
Issue Number: #88 
Adding anchor headings.
```
[ ] Yes
[x] No
```
Started work on this, but want to check in as I go so see if you agree with the direction. I'll need to do one of the following...
- refactor pages into a `PagesModule` and declare the `HeaderAnchorDirective` only there (I prefer this one)
- change all `<h3>` and `<h4>` in docs to `<h3 headerAnchor>` or similar
...in order to get rid of `#` which appear in the sidebar and table of contents now.
Another issue …
> Make headers linkable (#88)

- src/app/homepage/pages/microservices/grpc/grpc.component.html
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/1269
Added description of new proto-loader option for grpc
```
[ ] Yes
[x] No
```
> docs: add docs for proto-loader option

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
[X ] Other... Please describe:
```
Fixed documentation code listing
```
[ ] Yes
[X ] No
```
> documentation fix configuration.md - added missing import

- src/app/common/animations/index.ts
- src/app/common/animations/open-close.animation.ts
- src/app/homepage/menu/menu-item/menu-item.component.html
- src/app/homepage/menu/menu-item/menu-item.component.scss
- src/app/homepage/menu/menu-item/menu-item.component.spec.ts
- src/app/homepage/menu/menu-item/menu-item.component.ts
Improve the look and feel of the page. The current behavior open the list immediately and it's a little bit uncomfortable for the eye
```
[ ] Bugfix
[x] Feature
```
This gif explains better than words
```
[ ] Yes
[x] No
```
> feature(page) add navbar open/close animation

- src/app/shared/components/toc/toc.component.ts
Making a smooth transition when navigation using the toc component
```
[ ] Bugfix
[X] Feature
```
Again this gif explains better than words
```
[ ] Yes
[x] No
```
> feature(page) improve toc scroll behavior

- content/first-steps.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs improvement
```
Incorrectly connected link
Fixed correct link.
```
[ ] Yes
[x] No
```
> docs: fix Fastify's url

- content/graphql/quick-start.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs improvement
```
It links to the old github.io domain.
It links to the new custom domain.
```
[ ] Yes
[x] No
```
> fix(docs): update TypeGraphQL docs URL

- content/recipes/cqrs.md
```
[ ] Bugfix
[ ] Feature
Spelling typo
```
```
[ ] Yes
[x] No
```
> docs(CQRS): Fixes typo

- content/recipes/terminus.md
- package-lock.json
```
[x] Bugfix
[ ] Feature
```
Some code examples of the nestjs/terminus integration are faulty.
Fixed the faulty code examples and added javascript code examples in addition
```
[ ] Yes
[ ] No
```
> Fix the terminus example code

- content/pipes.md
```
[x] Bugfix
[ ] Feature
```
Fixed wrong code snippet of using global pipes.
```
[ ] Yes
[x] No
```
> Fix code sample of using global pipes

- content/modules.md
@kamilmysliwiec Modules chapter proposed edits, for your review.
> docs(modules.md) - Edits to Modules chapter

- content/middlewares.md
@kamilmysliwiec Middleware chapter proposed edits, for your review.
> Middleware chapter edits

- content/fundamentals/dependency-injection.md
- content/interceptors.md
- content/techniques/configuration.md
- content/techniques/performance.md
```
[ ] Bugfix
[ ] Feature
```
Typos and grammatical fixes for docs
```
[ ] Yes
[x] No
```
> Typos and grammar fixes

- content/techniques/hot-reload.md
This appears to be needed to actually make it work.
```
[x] Bugfix
[ ] Feature
```
Following the current instructions gives an error about not being able to resolve 'ts-loader'.
This error goes away.
```
[ ] Yes
[ ] No
```
> docs: Add installing ts-loader to hot reload docs

- content/recipes/swagger.md
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Content update
```
```
[ ] Yes
[ ] No
```
> docs(swagger): use 3000 as port in example code snippets

- content/techniques/authentication.md
Add a notice to include the custom AuthGuard
```
[ ] Bugfix
[ ] Feature
```
I only added a notice that a custom `AuthGuard` must be added to the `@UseGuards()` decorated in order to use the latter.
```
[ ] Yes
[X] No
```
> docs(techniques/authentication): Inheritance

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> Add types dependency for dotnev

- content/techniques/validation.md
```
[ ] Bugfix
[ ] Feature
```
Mismatched names.
```
[ ] Yes
[x] No
```
> Change 'CreateCatDto' to 'CreateUserDto'

- content/exception-filters.md
- package-lock.json
@kamilmysliwiec Exception filters chapter proposed edits, for your review.
This replaces #351 due to issues with the previous fork.  See #351 for additional history/discussion of changes.
Once you have a look, I'll close #351.
> docs(exception-filters.md): Edits for clarity, grammar

- content/techniques/mvc.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation update
```
Issue Number: #290 
I provided an example of `Dynamic template rendering`, so the situation when the application logic must dynamically decide which template to render. 
```
[ ] Yes
[x] No
```
> Issue #290 - docs(mvc): mention @Res() usage

- content/interceptors.md
- package-lock.json
@kamilmysliwiec Interceptors chapter proposed edits, for your review.
> docs(interceptors.md) Edits for clarity and grammar

- src/app/homepage/footer/footer.component.scss
- src/app/homepage/header/header.component.scss
- src/app/homepage/homepage.component.scss
- src/app/homepage/menu/menu.component.scss
- src/app/shared/components/toc/toc.component.scss
```
[ ] Bugfix
[x] Feature
```
The docs are not friendly for printing. 
Print friendly doc pages :tada: 
[Documentation _ NestJS - A progressive Node.js web framework.pdf](https://github.com/nestjs/docs.nestjs.com/files/3123868/Documentation._.NestJS.-.A.progressive.Node.js.web.framework.pdf)
For the best experience make sure to tick the `More settings > Background graphics` on Chrome!
```
[ ] Yes
[x] No
```
Tested on Chrome (best experience) and Firefox
> feat(page): Print-friendly pages

- content/custom-decorators.md
@kamilmysliwiec Custom decorators chapter proposed edits, for your review.
Most edits are minor, however I made a change to the content and flow of the 'Passing data' section that you should take a closer look at.  I thought this might flow better and demonstrate the use of the passed data more clearly, but please let me know if you agree.  If not, I'll revert those changes.
> docs(custom-decorators.md) Edits for clarity and grammar

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
```
Unnecessary ternary operator condition for a boolean variable
Simplified code for techniques/configuration.md
```
[ ] Yes
[x] No
```
> Simplified code for techniques/configuration.md

- src/app/common/animations/open-close.animation.ts
```
[X] Bugfix
[ ] Feature
```
Currently, in the navbar, if you try to navigate the elements is stepping on the hidden elements too, making the navigation though keyboard SUPER annoying.
Now when you navigate with the keyboard you do not pass though all the hidden titles in the navbar. only the visible ones
```
[ ] Yes
[X] No
```
> fix(A11Y): improve accessibility (A11Y) on navbar items

- content/websockets/adapter.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: documentation fix
```
}
a **// Maybe this character is redundant**
bindMessageHandlers(
```
[ ] Yes
[x] No
```
> docs(websockets/adapter.md) remove unused code

- content/fundamentals/dependency-injection.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: nestjs/nest#2145
```
[ ] Yes
[x] No
```
> docs(dependency-injection.md): add doc for `useExisting` provider

- content/recipes/terminus.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: documentation fix
```
Comparator in sample is incorrect; if users copy-paste this sample, then it will not work correctly
Comparator in sample is correct; if users copy-paste this sample, then it will work correctly
```
[ ] Yes
[x] No
```
Now matches [working sample](https://github.com/nestjs/terminus/blob/master/sample/000-dogs-app/src/dog/dog.health.ts) after update
> docs(terminus.md) Fix comparator in sample

- content/faq/multiple-servers.md
Addressing https://github.com/nestjs/docs.nestjs.com/issues/405
> add Fastify HTTPS doc

- content/techniques/caching.md
```
[X] Bugfix
[ ] Feature
```
Issue Number: #429
Just fix a typo
```
[ ] Yes
[X] No
```
> Fix #429 typo in caching docs.

- content/cli/overview.md
Just a small typo fix in the docs :)
```
[ ] Bugfix
[ ] Feature
[-] Other... Please describe:
Small typo fix
```
No behaviour change - just doc update.
```
[ ] Yes
[-] No
```
> Fix small typo

- content/fundamentals/unit-testing.md
I might be missing something here, but failry certain this is supposed to be `createNestApplicaton()`
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Documentation fix
```
```
[ ] Yes
[X] No
```
> createNestInstance() -> createNestApplicaton()

- content/controllers.md
```
[ ] Bugfix
[ ] Feature
```
Ref: https://docs.nestjs.com/controllers#request-object
The message is a hint but the color(type) of the blockquote is warning.
Blockquote is of type info.
```
[ ] Yes
[X] No
```
> Fix blockquote type to be hint.

- content/modules.md
I had misunderstood this on the first read-through
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Doc clarification
```
```
[ ] Yes
[X] No
```
> Tweak syntax for clarity

- content/techniques/file-upload.md
```
[ ] Bugfix
[x] Feature
```
Documentation according to this PR https://github.com/nestjs/nest/pull/2496
```
[ ] Yes
[x] No
```
> docs(UploadFile): Add AnyFileInterceptor documentation

- content/techniques/sql.md
This PR adds minor typo fixes I noticed while walking through the database/sql documentation.
Thanks so much for your work in maintaining this!
```
```
The database/sql doc contains a small number of minor typos and grammar issues.
The database/sql doc should be slightly easier to read and understand.
```
```
> chore(sql): clarify sql doc language

- content/pipes.md
```
[ ] Bugfix
[x] Feature
```
`ParseUUIDPipe` docs is missing...
`ParseUUIDPipe` is present on the pipes docs
```
[ ] Yes
[x] No
```
> uuid pipe docs

- content/enterprise.md
> docs(consulting): update wording and fix errros

- .gitignore
- content/recipes/crud.md
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/recipes/crud/crud.component.ts
- src/app/homepage/pages/recipes/recipes.module.ts
Added a recipe of Nestjsx/crud usage
```
[ ] Bugfix
[x] Feature
```
New docs include a recipe of Nestjsx/crud usage.
```
[ ] Yes
[x] No
```
> Added a recipe of Nestjsx/crud usage

- content/pipes.md
- [ X] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[ X] Other... Please describe: fixed a count typo
```
Wrong Count
Correct Count
```
[ ] Yes
[X ] No
```
> docs(pipes) fixed count of built in pipes from two to three

- content/techniques/authentication.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fixed typo
```
Wrong Wording
Correct Wording
```
[ ] Yes
[x] No
```
> (fix) typo: stratgy => strategy

- content/exception-filters.md
@kamilmysliwiec Exception filters chapter proposed edits, for your review.
Addresses #531
> Exception filter update

- content/techniques/performance.md
@kamilmysliwiec Fastify chapter updates for your review.
- Cleaned up a little in general
- Should close #536
> docs(performance.md) update Fastify chapter

- compiler/markdown-compiler.ts
- src/app/homepage/homepage.component.scss
```
[ ] Bugfix
[x] Feature
```
Issue Number: #537 
Adds a `Edit Page`-button per Markdown page which leads directly to Github, where the user can edit the requested page.
```
[ ] Yes
[x] No
```
> feature(): add github link for each md page

- content/techniques/mvc.md
@kamilmysliwiec MVC chapter edits
- add description of `@Render()`
- light edits for grammar/style
> doc(mvc.md) - Describe @Render, more edits

- content/techniques/caching.md
@kamilmysliwiec Caching chapter: address cache disable warning - #478 (Nest #2401), Light editing for style/grammar
> docs(caching.md) @Res() warning, edits

- content/techniques/performance.md
@kamilmysliwiec Fastify chapter: clarify redirect handling
Reference (Nest#)1978, #463
> docs(performance.md) clarify fastify redirect

- .gitignore
- content/recipes/serve-static.md
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/recipes/recipes.module.ts
- src/app/homepage/pages/recipes/serve-static/serve-static.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Add Serve Static recipe

- content/techniques/authentication.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(authentication): add documentation to get current authenticated user with GraphQL

- content/pipes.md
@kamilmysliwiec Pipes chapter - add required @hapi/joi package install.
> docs(pipes.md) Add install of @hapi/joi

- content/controllers.md
- package-lock.json
- src/styles.scss
@kamilmysliwiec Controller page update re: issue #456 for your review.
> docs(controllers.md) Add note on @Res() per #456

- content/techniques/authentication.md
Update the link to the exception filters docs page and fix return type in one of the examples.
N/A
N/A
```
[ ] Yes
[X] No
```
> docs(authentication) URL and type fix

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Documentation
```
Wrong import `Joi` package after 069631fe3ed64f0628819a43c6fdcfe5324d45b7 commit 
👌
```
[ ] Yes
[X] No
```
> docs(configuration.md): fix import @hapi/joi

- content/exception-filters.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(exception-filters.md): fix typo in HttpException response

- content/techniques/validation.md
```
[ ] Bugfix
[ ] Feature
```
Docs update
```
[ ] Yes
[x] No
```
> docs(validation): Reword intro text for validation doc

- content/exception-filters.md
@kamilmysliwiec Exception-Filters improvements
- clarify how exceptions are constructed
- fix example to match code
> docs(exception-filters.md) clarify httpexceptions, fix example

- content/techniques/authentication.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Update authentication.md to mention type definitions

- content/fundamentals/provider-scopes.md
```
[x] Bugfix
[ ] Feature
[x] Other... Please describe: grammar?
```
```
[ ] Yes
[x] No
```
> fix: improved grammar of the sentence

- content/first-steps.md
@kamilmysliwiec Fixes minor typo in first-steps chapter :)
> docs(first-steps) minor typo

- content/techniques/authentication.md
@kamilmysliwiec Fix typo in auth doc.
Closes #574
> docs(authentication) fix typo

- content/components.md
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no API changes)
[x] Other... Please describe: Just doc polishing
```
```
[ ] Yes
[x] No
```
> Typo fix and style polishing

- content/techniques/authentication.md
@kamilmysliwiec Authentication chapter code example fix.  Add JwtModule import/register.
Closes #570
> docs(authentication) add import/register JwtModule

- README.md
@kamilmysliwiec add link to dev.to blog
> docs(readme.md) add blog link

- content/custom-decorators.md
- content/middlewares.md
- content/techniques/mvc.md
- package-lock.json
These broken links were found by the new dgeni compiler.
> docs(3 files) fix broken links in 3 files

- content/middlewares.md
Fix minor bug in middleware chapter
> docs(middleware) add required imports

- content/controllers.md
Small edits.
- add hints about decorators when first mentioned
- consistent use of casing for Response vs. response
> doc(controllers) small edits

- content/techniques/security.md
@kamilmysliwiec Clarification about csurf middleware requiring sessions or cookies.
Closes #572
> doc(security.md) note about csurf cookies/sessions

- content/microservices/basics.md
Fixed wrong usage of constructor perhaps due to pasting
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Typo in documentation
```
```
[ ] Yes
[x] No
```
> Remove typo constructors

- content/controllers.md
Docs for new `@Redirect()` decorator targeted for v6.6.0
> docs(controllers) @Redirect() decorator

- content/controllers.md
Formatting fix (embedded HTML vs. Markdown mixup)
> docs(controllers) fix code formatting

- content/controllers.md
A spelling error
```
[ ] Bugfix
[ ] Feature
[X ] Other... Please describe: spelling error
```
```
[ ] Yes
[ ] No
```
> fix(controllers.md): remove extra ')'

- content/middlewares.md
Add async/await hint.  Docs for nestjs/nest#2767
> docs(middlewares.md) add async/await hint

- content/fundamentals/async-components.md
> docs(async providers) light editing

- content/fundamentals/platform-agnosticism.md
Platform agnosticism chapter edits.
> docs(platform-agnosticism) minor edits

- content/fundamentals/dependency-injection.md
- package-lock.json
@kamilmysliwiec Custom providers chapter rewrite for your review
> docs(custom-providers) rewrite

- content/fundamentals/circular-dependency.md
Circular dependency chapter edits
> docs(circular-dependency) edits

- content/techniques/configuration.md
Configuration chapter edits.  Also refers to a config example which I've built, and will do a PR on @nestjs/nest shortly.
> docs(configuration.md) - tune up

- content/techniques/sql.md
Database chapter edits for grammar and style.  I'll make another deeper pass at this when I've had time to do more research and experimentation.
> docs(techniques/databsase) - light edits

- README.md
- content/controllers.md
- content/microservices/grpc.md
- content/microservices/rabbitmq.md
- src/app/common/social-wrapper/social-wrapper.component.html
- src/app/homepage/footer/footer.component.html
- src/app/homepage/header/header.component.html
- src/app/homepage/homepage.component.html
- src/app/homepage/menu/menu-item/menu-item.component.html
- src/app/homepage/pages/advanced/mixin-components/mixin-components.component.html
- src/app/homepage/pages/graphql/schema-stitching/schema-stitching.component.html
- src/app/homepage/pages/microservices/custom-transport/custom-transport.component.html
- tools/transforms/content-package/services/renderer/link.renderer.ts
- tools/transforms/templates/who-uses.template.html
> fix(links): fix external link issues

- content/application-context.md
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: documentation update
```
```
[ ] Yes
[X] No
```
> Added info about app.close()

- content/fundamentals/dynamic-modules.md
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/fundamentals/dynamic-modules/dynamic-modules.component.html
- src/app/homepage/pages/fundamentals/dynamic-modules/dynamic-modules.component.ts
- src/app/homepage/pages/fundamentals/fundamentals.module.ts
@kamilmysliwiec Proposed new Dynamic Modules chapter for your review.
Associated example PR on nest repo to follow soon.
> docs(dynamic-modules) - Create new Dynamic Modules chapter

- content/techniques/configuration.md
```
[x] Bugfix
[ ] Feature
```
Filename in code snippet section reads as "config/config.service.ts.ts"
Filename in code snippet displays w/o duplicate file extension: "config/config.service.ts"
```
[ ] Yes
[x] No
```
> docs (bugfix) Fix config filename typo

- content/modules.md
- src/app/homepage/pages/fundamentals/dynamic-modules/dynamic-modules.component.html
Updates Modules chapter to link to Dynamic Modules, plus a few minor edits.
Note: src/app/homepage/pages/fundamentals/dynamic-modules/dynamic-modules.component.html
file got included here.  I think maybe this generated file needs to get added to .gitignore?  I'm not completely sure how the page file generation works.
> docs(modules) update dynamic modules section

- content/fundamentals/dynamic-modules.md
Fix code snippet error.  Fixes #672
> docs(dynamic-modules) fix code snippet error

- content/techniques/sql.md
Database chapter update.  Nest is DB agnostic.
> docs(database) - Nest is db agnostic

- .gitignore
Add dynamic modules to .gitignore
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```
> docs(gitignore) add dynamic modules to gitignore

- content/techniques/configuration.md
Sample is actually for dynamic modules, not a full sample of config.
> docs(configuration) - remove obsolete reference to sample

- content/exception-filters.md
@kamilmysliwiec First part of the discussed improvement to docs for `ArgumentsHost`.  After I get your feedback on this, I'll make similar changes for consistency (and, e.g., elaborating on `ExecutionContext` in the Guards chapter, etc.) for the other platforms.
I think this could stand alone and be published now.  The only "loose end" is it does make sort of a "forward reference" to a discussion about cross-context filters, which of course doesn't exist yet :)
It also makes a few other minor tweaks.
> docs(exception filters) Improve ArgumentsHost

- content/guards.md
Minor edits.  Continuing with cleanup/improvements of `ArgumentsHost` / `ExecutionContext`.
> docs(guards.md) small edits to Execution Context

- content/microservices/basics.md
> docs(basics.md) - edits

- content/microservices/basics.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(msvc) update basics chapter

- content/cli/scripts.md
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/cli/cli.module.ts
- src/app/homepage/pages/cli/scripts/scripts.component.html
- src/app/homepage/pages/cli/scripts/scripts.component.ts
> docs(cli) new chapter on build/start cmds, npm scripts

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update documentation
```
There are two broken links in the CONTRIBUTING.md file.
Issue Number: #702 
No broken links anymore.
```
[ ] Yes
[x] No
```
> fix(links): fix broken links

- content/graphql/guards-interceptors.md
missing link of schema directives from apollo
```
[ ] Bugfix
[ ] Feature
```
Wrong link.
```
[ ] Yes
[X] No
```
> Missing links on guards-interceptors.md

- content/discover/who-uses.json
- src/app/homepage/pages/discover/who-uses/who-uses.component.ts
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
```
[ ] Yes
[ x] No
```
> rename framework.watch to frontendwatch.com

- content/techniques/authentication.md
Addresses #708 
Not closing #708 until we update samples to match.
> docs(authentication) fix routes

- content/cli/usages.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update documentation
```
Currently there is no description how to generate new modules, controllers, etc. without `.spec.ts` files.
Add `--no-spec` detail for `nest g` command.
```
[ ] Yes
[x] No
```
> docs(usages): update command option

- content/websockets/gateways.md
- src/app/homepage/pages/cli/scripts/scripts.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs() update gateways chapter (decorators, minor updates)

- content/cli/overview.md
- content/cli/workspaces.md
- package-lock.json
Mainly adds new `compilerOptions`.
Also addresses #731 (well, not FirstSteps, but in the CLI.  We can go back and do FirstSteps once this one is approved)
Also cleans up a few leftovers from first version.
> docs(CLI) updates

- content/cli/overview.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(cli): correct link to usage page

- content/fundamentals/provider-scopes.md
Relatively minor edits: clean up some wording and grammar.  Slight reorganization/section heading changes.
@kamilmysliwiec please review section on Controller Scope.  I broke it out separately, but the content should be mostly the same, though I did make one assertion that you should confirm: `For a request-scoped controller, a new instance is created for each inbound request, and garbage-collected when the request has completed processing.`
> doc(injection-scopes) minor edits

- content/techniques/file-upload.md
File upload chapter improvements.
> docs(File upload) improvements for grammar, clarity, details

- content/techniques/serialization.md
> docs(serialization) Light edits for grammar, clarity

- content/techniques/mongo.md
> docs(mongo) Edits for grammar and style

- content/techniques/authentication.md
- [X ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ X] Documentation
```
Mentioned in the documentaion the ability to change the local-strategy fields behavior.
> doc(authentication): minor change to local-strategy

- content/fundamentals/unit-testing.md
> docs(testing) - Edits for style and grammar.

- content/recipes/terminus.md
```
[x] Bugfix
[ ] Feature
```
The current sample code has an error about imports. 
The error is gone from the sample code.
```
[ ] Yes
[x] No
```
> docs(terminus): fix bad imports

- content/discover/who-uses.json
```
[ ] Bugfix
[ ] Feature
```
Documentation
```
[ ] Yes
[x] No
```
> added rosebayconsult on who is using nestjs

- content/techniques/mongo.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: redirect to correct example

- content/controllers.md
- content/custom-decorators.md
Related PR https://github.com/nestjs/nest/pull/3249
> docs(): add ip route param

- content/recipes/crud.md
I added typeorm in the crud recipe. Without the package the recipe does not work.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Fix a recipe
```
Copy Paste command does not work the project.
Copy/Paste command makes the project work.
```
[ ] Yes
[x] No
```
> Crud recipe: Missing typeorm

- content/custom-decorators.md
```
[X] Documentation
```
Related PR nestjs/nest#3113
> docs(apply decorators)

- content/techniques/caching.md
- [ ✓ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ✓ ] Feature
[ ✓ ] Other... Please describe: Updating docs for the CacheTTL decorator, as per: https://github.com/nestjs/nest/pull/2943
```
Issue Number: https://github.com/nestjs/nest/pull/2943
```
[ ] Yes
[✓] No
```
> docs(cache): update the docs to include the @CacheTTL() decorator

- content/graphql/subscriptions.md
If I have understood the explanation of [this issue](https://github.com/nestjs/graphql/issues/337#issuecomment-512555183) correctly.
The docs have to be changed accordingly.
```
[x] Bugfix
[ ] Feature
```
If I have understood the explanation of [this issue](https://github.com/nestjs/graphql/issues/337#issuecomment-512555183) correctly.
The docs have to be changed accordingly.
Issue Number: [#337](https://github.com/nestjs/graphql/issues/337)
The schema should be generated correctly in the code first approache
```
[ ] Yes
[x] …
```
> docs(graphql): Passing arguments to subscription filters

- content/recipes/mongodb.md
> Fixed typo

- src/app/homepage/header/header.component.html
- src/app/homepage/header/header.component.scss
- src/app/homepage/homepage.component.ts
- src/index.html
cc #428
```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[x] No
```
> feat: add search on the documentation

- .prettierrc
- content/recipes/swagger.md
- renovate.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs() update swagger to conform version 4

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(config) - edits

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(): update to use @nestjs/config module

- content/guards.md
```
[x] Bugfix
[ ] Feature
```
Under the `Putting it all together` section there is an unused import
Removed the unused import from the mentioned section
```
[ ] Yes
[x] No
```
> docs(guards): remove unused import

- content/techniques/task-scheduling.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> doc(task-scheduling) - edits (WIP)

- .gitignore
- content/techniques/task-scheduling.md
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/techniques/task-scheduling/task-scheduling.component.ts
- src/app/homepage/pages/techniques/techniques.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> content(): add a new task scheduling chapter

- content/techniques/configuration.md
```
[x] Bugfix
[ ] Feature
```
1. Missing ending bracket in ApiConfigService
2. Filename is incorrect - `config.service.ts`
1. Added missing ending bracket.
2. Updated filename to `app.module.ts`
```
[ ] Yes
[x] No
```
N/A
> Fixed missing bracket and updated filename

- content/techniques/queues.md
@kamilmysliwiec still a WIP.  But pushing in case you want to take a look.
> docs(queues) updates (WIP)

- content/techniques/configuration.md
```
[x] Bugfix
[ ] Feature
```
1. `allowUnknowns` is incorrect
1. Replaced `allowUnknowns` with `allowUnknown`
Note: Refer line [#141](https://github.com/nestjs/config/blob/master/lib/config.module.ts#L141) of `@nestjs/config` package
```
[ ] Yes
[x] No
```
N/A
> Fix validationOptions for ConfigModule

- content/microservices/grpc.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(grpc) edits (WIP)

- content/cli/usages.md
- content/cli/workspaces.md
```
[ ] Bugfix
[x] Feature
```
Adds docs for the new generateOptions, as seen in PR https://github.com/nestjs/nest-cli/pull/527
```
[ ] Yes
[x] No
```
> docs(cli): Add docs for new generateOptions conf

- content/techniques/configuration.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: nestjs/config#40
A new option `expandVariables` is now available.
```
[ ] Yes
[x] No
```
Please let me know if anything needs to be updated.
Thanks 😄
> Documentation for expandable variables

- content/techniques/performance.md
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(common): correct fastify adapter example

- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/homepage/header/header.component.spec.ts
- src/app/homepage/header/header.component.ts
- src/app/homepage/homepage.component.spec.ts
- src/app/homepage/homepage.component.ts
- src/app/homepage/menu/menu.component.spec.ts
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/page/page.component.ts
```
[x] Bugfix
[ ] Feature
```
`npm run test` fails.
```
[ ] Yes
[x] No
```
I changed `xit` to `it` for `HomeComponent` & `MenuComponent`. If you think that needs to be reverted, I'll do that.
> Bugfix: Fixed `npm run test` Errors

- content/controllers.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/pull/2980
Added "Sub-Domain Routing" documentation.
```
[ ] Yes
[x] No
```
> Sub-Domain Routing documentation

- content/techniques/task-scheduling.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/schedule/pull/33
Supply `CronExpression` enumerations
```
[ ] Yes
[x] No
```
> docs(task-scheduling): add a short note about CronExpression enum

- content/pipes.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Fix class-validator lib link in pipes.md: pleerock -> typestack

- content/fundamentals/circular-dependency.md
- content/fundamentals/module-reference.md
- content/fundamentals/unit-testing.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module-reference): suggested edits

- content/microservices/basics.md
- content/microservices/exception-filters.md
- content/microservices/grpc.md
- content/microservices/guards.md
- content/microservices/interceptors.md
- content/microservices/kafka.md
- content/microservices/mqtt.md
- content/microservices/nats.md
- content/microservices/pipes.md
- content/microservices/rabbitmq.md
- content/microservices/redis.md
- src/app/homepage/pages/faq/request-lifecycle/request-lifecycle.component.html
- src/app/homepage/pages/fundamentals/execution-context/execution-context.component.html
- src/app/homepage/pages/fundamentals/module-reference/module-reference.component.html
- src/app/homepage/pages/techniques/queues/queues.component.html
- src/app/homepage/pages/techniques/task-scheduling/task-scheduling.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
@kamilmysliwiec Sorry for dragging in upstream commits.  Let me know if you need me to fix this, or if you can cherry pick around it.
> docs(microservices) - suggested edits

- content/fundamentals/module-reference.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
Fixes bad link
> docs (module-reference) - fix link

- content/microservices/grpc.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
@kamilmysliwiec Just a few minor edits.
> docs(grpc.md) - minor edits

- content/techniques/authentication.md
```
[ ] Bugfix
[ ] Feature
```
package name is wrong
```
[ ] Yes
[x] No
```
> docs (wrong-package-name) - fix package name

- content/microservices/grpc.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(): add docs on grpc streaming

- content/techniques/configuration.md
> fix(docs): fix word in configuration.md

- content/custom-decorators.md
- content/faq/multiple-servers.md
- content/graphql/quick-start.md
- content/graphql/resolvers-map.md
- content/recipes/hot-reload.md
- content/websockets/exception-filters.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs() - suggested updates

- content/application-context.md
- content/faq/global-prefix.md
- content/faq/http-adapter.md
- content/faq/hybrid-application.md
- content/faq/multiple-servers.md
- content/graphql/guards-interceptors.md
- content/graphql/mutations.md
- content/graphql/scalars.md
- content/graphql/subscriptions.md
- content/recipes/cqrs.md
- content/recipes/crud.md
- content/recipes/documentation.md
- content/techniques/compression.md
- content/techniques/http-module.md
- content/techniques/security.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
Many small edits, primarily for consistent style and grammar.
> docs() - many small edits

- content/graphql/quick-start.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(graphql): update packages info

- content/techniques/sql.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Suggested updates

- content/custom-decorators.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: 
https://github.com/nestjs/nest/issues/3356
https://github.com/nestjs/nest/pull/3558
The user can now define type checks on Custom Decorators using generics,
```
[ ] Yes
[x] No
```
> docs(common): typed decorators through generics

- content/techniques/authentication.md
- content/techniques/task-scheduling.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> content(): auth improvements (inheritance, request scoped)

- content/techniques/security.md
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: docs update
```
```
[ ] Yes
[X] No
```
> docs: update amount of Helmet's middleware functions

- content/graphql/subscriptions.md
"With" was missing the "h"
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> very small typo

- content/graphql/scalars.md
"install" should be "installing"
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> small grammatical update

- content/graphql/quick-start.md
> fix(wording): seo

- content/recipes/swagger.md
```
[ ] Bugfix
[x] Feature
```
Add documentations for `enumName`
Issue Number: https://github.com/nestjs/swagger/pull/412
```
[ ] Yes
[x] No
```
> docs(swagger): add docs for enumName

- content/techniques/authentication.md
```
[x] Bugfix
[ ] Feature
```
At the end of the chapter 'Implement protected route and JWT strategy guards' in 'Authentication' there is a missing link, which points to nowhere.
Link now points to the correct url.
```
[ ] Yes
[x] No
```
> bugfix(docs): add missing example link

- content/cli/usages.md
- content/cli/workspaces.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: documentation
```
Issue Number: https://github.com/nestjs/nest-cli/issues/581
Add `watchAssets` option into the CLI section.
```
[ ] Yes
[x] No
```
> docs(cli): add doc for `watchAssets` in cli

- content/first-steps.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Doc updated
```
```
[ ] Yes
[x] No
```
> docs: update minimum node js version

- content/recipes/swagger.md
according to `SchemaObject` interface
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Doc updated
```
```
[ ] Yes
[x] No
```
> docs: replace min setting by minimum

- content/application-context.md
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe: Docs
```
```
[ ] Yes
[X] No
```
> docs(): fix typo

- content/graphql/quick-start.md
- content/graphql/resolvers-map.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
@kamilmysliwiec - this is WIP as I work through more testing of GraphQL.  I'll comment back when I think it's ready for review/merge.
> docs(graphql): suggested improvements

- content/graphql/interfaces.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Typo fix
```
N/A
```
[ ] Yes
[x] No
```
> fix(): Fixing a typo in GraphQL docs (interfaces)

- content/graphql/resolvers-map.md
- content/graphql/subscriptions.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(graphql chapter): suggested updates

- content/pipes.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/4393
Add `errorHttpStatusCode` in `ValidationPipe` or any built-in pipes to throw a different HTTP status code
```ts
new ValidationPipe({
errorHttpStatusCode: HttpStatus.UNPROCESSABLE_ENTITY
});
// Before
{
"statusCode": 400,
"message": ["email must be an email"],
"error": "Bad Request"
}
// After
{
"statusCode": 422,
"message": ["email must be an email"],
"error": "Unprocessable Entity"
}
```
```
[ ] Yes
[x] No
```
> docs(pipes): add exception code in validation pipe

- content/pipes.md
A simple change in Object schema validation documentation.
```
[x] Bugfix
[ ] Feature
```
The method `validate(value)` is accessible if the `schema` parameter is a `ObjectSchema` from `@hapi/joi`.
Import `@hapi/joi` and change de type of `schema` parameter in `constructor`
```
[ ] Yes
[x] No
```
Using `Typescript`.
> Suggest update in "Object schema validation"

- content/faq/hybrid-application.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(hybrid): fix for starting multiple connected apps

- content/techniques/mongo.md
Installing mongoose for Typescript use.
```
[ ] Bugfix
[x] Feature
```
Using Typescript, won't work correctly, causing the following message: 
> Could not find a declaration file for module 'mongoose'.
Installing `@types/mongoose` in devDependencies to use with Typescript.
```
[ ] Yes
[x] No
```
> Suggest update in mongo techniques

- content/graphql/scalars.md
```
[ ] Bugfix
[ ] Feature
Syntax error 
```
Syntax error in code example
Updated to fix syntax error
```
[ ] Yes
[x] No
```
> Syntax error in code example

- content/components.md
Added related providers topics that cant be found otherwise without reading the whole documentation.
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: Updated documentation
```
> Update components.md (providers)

- content/migration.md
- content/recipes/terminus.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> Add migration guide for terminus v7

- content/recipes/terminus.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(terminus) fix minor typo's

- content/graphql/subscriptions.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
Partially addresses https://github.com/nestjs/graphql/issues/753 by correcting an error and being more explicit about how the published event needs to correspond to the subscription result object.
Doesn't address the [mutation variant](https://github.com/nestjs/graphql/issues/753#issuecomment-611945956) of that issue as that seems like a corner case, and when I tried to explain it, I felt it was more confusing than helpful.
> docs(subscription.md) correction re: subscription handler name

- content/recipes/swagger.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(readme): Add missing api response decorators

- content/techniques/compression.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs improvement
```
Generic "see this package" instructions for making compression work with Fastify. According to fastify-compress docs, the plugin will auto-register. This isn't actually the case, at least in a Nest project. 
Fastify compresion integration is laid out just as explicitly as the default Express-based example. Docs are based on working functionality in an internal app.
```
[ ] Yes
[x] No
```
> Add more detail to Fastify compression instructions

- content/recipes/prisma.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: remove unavailable https://www.prisma.io/features url

- content/introduction.md
```
[x] Bugfix
[ ] Feature
[] Other... Please describe:
```
> Open your browser and navigate to `http://localhost:3000/`.
> Open your browser and navigate to [`http://localhost:3000/`](http://localhost:3000/).
```
[ ] Yes
[x] No
```
> fix(content/introduction): make link clickable

- content/components.md
```
[x] Bugfix
[ ] Feature
```
Cat interface snippet has no filename
Since it is referenced above as:
```ts
import { Cat } from './interfaces/cat.interface';
```
I name the snippet `interfaces/cat.interface.ts`
```
[ ] Yes
[x] No
```
> Overview>Providers: add filename for interface snippet

- content/graphql/guards-interceptors.md
```
```
Issue Number: https://github.com/nestjs/graphql/issues/760
```
[x] No
```
> docs(graphql): document fieldResolverEnhancers

- content/graphql/mapped-types.md
relate to nestjs/graphql#776
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> docs(@nestjs/graphql): add new type hepler

- content/recipes/swagger.md
Documentation for Cookie Authentication OpenAPI support in PR [@nestjs/swagger 650](https://github.com/nestjs/swagger/pull/650)
Issue: [@nestjs/swagger 649](https://github.com/nestjs/swagger/issues/649)
> OpenAPI 3 Cookie Authentication Support

- content/recipes/swagger.md
relate to nestjs/swagger#677
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> docs(@nestjs/swagger): add new type helper

- content/fundamentals/lifecycle-events.md
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation improvement
```
```
[ ] Yes
[ x ] No
```
----
I just added a small paragraph to show that those hooks won't be called as long you are not registering hooks. I had to try on my own because it was not explicit enough at the beginning for me 😅
> Improve lifecycle's documentation

- content/pipes.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1199 1199
Added `DefaultValuePipe` to the docs.
```
[ ] Yes
[x] No
```
> docs(common): add DefaultValuePipe docs

- content/pipes.md
```
[ ] Bugfix
[ ] Feature
Various improvements
```
> docs(pipes) - various improvements

- src/app/homepage/header/header.component.scss
```
[ ] Bugfix
[ ] Feature
[*] Other... Please describe:
```
Show search bar for smaller resolutions . Solved Issue #1182  
Issue Number: #1182 
```
[ ] Yes
[*] No
```
> Changed header css . Show search bar for smaller resolutions . Solved Issue#1182

- .github/workflows/lighthouse.yml
- lighthouserc.json
- src/app/homepage/footer/footer.component.html
- src/app/homepage/homepage.component.html
- src/app/homepage/newsletter/newsletter.component.html
- src/index.html
Resolves #971
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: add lighthouse ci check

- content/controllers.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Fixed incorrect JavaScript code example
```
The [Full resource sample](https://docs.nestjs.com/controllers#full-resource-sample) JavaScript code is incorrect and not working.
I fixed the JavaScript example code, now it works well.
```
[ ] Yes
[x] No
```
The incorrect JavaScript example code can be found here: https://docs.nestjs.com/controllers#full-resource-sample
> Fixed incorrect JavaScript code example

- src/app/homepage/header/header.component.scss
Fixed bug
Fixes issue #1293 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Fixed bug Solved Search bar issue. 

- content/custom-decorators.md
```
[ ] Bugfix
[ ] Feature
```
Says that decorators can be used in a class or a property
Added that can also be used in a method
```
[ ] Yes
[x] No
```
> Correct where decorators can be used

- content/techniques/security.md
Reverts nestjs/docs.nestjs.com#1284
> Revert "update helmet import"

- content/middlewares.md
Add types for the functional middleware example args
```
[ ] Bugfix
[ ] Feature
[x] Other: documentation enhancement
```
```
[ ] Yes
[x] No
```
> docs(middlewares.md) type functional args

- content/cli/usages.md
| `--tag`   | Update to tagged version (use `@latest`, `@<tag>`, etc) <br/>Alias `-wt` |  |
become
| `--tag`   | Update to tagged version (use `@latest`, `@<tag>`, etc) <br/>Alias `-t` |  |
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Fix a possible typo in nest update command options

- content/techniques/caching.md
Changed simple to simply in the different stores section of caching.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Fixing typo

- content/recipes/prisma.md
```
[x] Other... Please describe: Docs
```
```
[ ] Yes
[x] No
```
The default version of Prisma is now Prisma 2 so this was needed to make it less confusing I think.
> Update name of Prisma example to Prisma 1

- content/techniques/task-scheduling.md
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
```
[ ] Yes
[X] No
```
> docs(task-scheduling): remove closing bracket

- content/recipes/hot-reload.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update docs
```
Issue Number: https://github.com/nestjs/nest/issues/5068
```
[ ] Yes
[x] No
```
> docs(hmr) update webpack-node-externals option property name

- content/fundamentals/lifecycle-events.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Fix broken ref to anchor link in lifecycle events

- content/graphql/quick-start.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/graphql/pull/997
```
[ ] Yes
[x] No
```
> feat(): Add sortSchema property

- content/techniques/sql.md
refs nestjs/typeorm#151
```
[ ] Bugfix
[x] Feature
```
There is no documentation of how to work with EntitySchema.
Issue Number: nestjs/typeorm#151
```
[] Yes
[x] No
```
Documentation for nestjs/typeorm#427
> docs(sql): separating entity definition

- content/enterprise.md
- content/fundamentals/unit-testing.md
```
[x ] Bugfix
[ ] Feature
```
just correct HTML close tags
NO
```
[ ] Yes
[x ] No
```
> docs(): add missing <tr> close tag and close <img> tag properly

- content/techniques/configuration.md
```
[ ] Bugfix
[x] Feature
```
Adds docs for the `ConfigService<T>` generic argument for [PR](https://github.com/nestjs/config/pull/227)
> doc(config): add generic type explanation to config service

- content/techniques/authentication.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(authentication): edit correct install flag

- content/pipes.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Typos in documentation
```
```
[ ] Yes
[x] No
```
> docs(pipes): fixed various typos

- content/techniques/mvc.md
```
[x] Bugfix
[ ] Feature
```
Import Res decorator from @express/common
```
[ ] Yes
[x] No
```
> fix(content/techniques): Import Res decorator from @express/common

- content/techniques/security.md
```
[ ] Bugfix
[ ] Feature
```
The instructions in the documentation are insufficient if you are using `Fastify`.
Issue Number: https://github.com/nestjs/nest/issues/5195
The instructions are now complete.
```
[ ] Yes
[x] No
```
> docs(security/helmet): add how to use helmet with fastify

- content/pipes.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: typo
```
```
[ ] Yes
[x] No
```
> typo: extra closing parenthesis

- content/techniques/authentication.md
```
[X] Bugfix
[ ] Feature
```
Javascript example code for the [authentication](https://docs.nestjs.com/techniques/authentication) section has syntax errors.
Fix syntax errors in JS [authentication example code](https://docs.nestjs.com/techniques/authentication).
```
[ ] Yes
[X] No
```
I'm new to Nest so hopefully the decorator usage is correct, it at least works for me locally. Cheers!
> docs(auth): fix JS examples

- content/discover/who-uses.json
Update new company on who-uses.json
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
> docs(who-use.json): Update company on who-use.json

- content/techniques/mongo.md
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe: I fixed a typo, it was a duplicated word in the text after the example of raw mongoose schemas
```
```
[ ] Yes
[ x] No
```
> Typo fixed after raw schema example

- content/custom-decorators.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The decorator composition snippet only showed a TypeScript example.
I fixed the snippet to toggle between TS and JS and gave it an appropriate file name.
I also fixed a typo where there was an extra `"`.
```
[ ] Yes
[x] No
```
> docs: fix decorator composition snippet

- content/exception-filters.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
It shows a list of built-in exceptions, but `PreconditionFailedException` is missing.
It shows a complete list of built-in exceptions.
```
[ ] Yes
[x] No
```
> docs: add missing exception to built-in exception list

- content/middlewares.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The functional middleware snippet shows a TS/JS toggle button but the code doesn't change. It only shows TS.
The functional middleware snippet now properly switches between TS and JS code. The JS version has the types removed.
```
[ ] Yes
[x] No
```
> docs: add JS version of functional middleware snippet

- content/controllers.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
There's an existing explanation of HTTP method decorators for creating request endpoints.
I made the list of decorator methods exhaustive and explained `@All` a bit better.
```
[ ] Yes
[x] No
```
> docs: improve http method decorator explanation

- content/websockets/pipes.md
fix a typo, web sockets instead of microservice
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
```
[ ] Yes
[ ] No
```
> docs update pipes.md

- content/controllers.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Lack of brackets after `@Get` and `@Post` in the controller part of overview.
Issue Number: 1
Add brackets.
```
[ ] Yes
[x] No
```
> docs(controller): fix typo in overview part

- content/recipes/cqrs.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
> docs: fix a minor grammar mistake

- content/techniques/sql.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
Referenced page
https://docs.nestjs.com/techniques/database
> docs(changelog) Fix typo in users.module import path(sql.md)

- content/websockets/gateways.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Docs
```
Issue Number: nestjs/nest/issues/5525
`WsResponse` serialization is properly documented.
```
[ ] Yes
[x] No
```
> docs(gateways): add warning about wsresponse serialization

- content/openapi/introduction.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(): Add download swagger json hint for fastify

- content/first-steps.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The First Steps section doesn't describe all of the files that are generated in `src/`.
The table of "core files" is complete.
```
[ ] Yes
[x] No
```
Screenshot:
> fix: add missing core files in First Steps section

- content/recipes/hot-reload.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Added documentation for undocumented feature
```
Issue Number: nestjs/nest#711
```
[ ] Yes
[x] No
```
> Add HMR note for @nestjs/typeorm

- CONTRIBUTING.md
- content/techniques/mongo.md
```
[ ] Bugfix
[x] Feature
```
It is unclear how to use `ref` with `@Prop` decorator.
PR adds example of usage `ref` with `@Prop` decorator.
```
[ ] Yes
[x] No
```
> Mongoose @Prop decorator ref example

- content/techniques/configuration.md
```
[ ] Bugfix
[x] Feature
```
Add ConfigService Hint Description
```
[ ] Yes
[x] No
```
> feat(techniques): Add ConfigService Hint Description

- content/fundamentals/dependency-injection.md
```
[ ] Bugfix
[x] Feature
```
Use TypeScript Enums as token values
```
[ ] Yes
[x] No
```
> feat(content/fundamentals): Use TypeScript Enums as token values

- content/fundamentals/unit-testing.md
```
[x] Bugfix
[ ] Feature
```
Nest crashes with cryptic error messages when using Fastify with E2E testing.
Nest no longer crashes with the new configuration added.
```
[ ] Yes
[x] No
```
> docs(fundamentals/unit-testing): Add hint for Fastify configuration for E2E testing

- content/microservices/redis.md
```
[ ] Bugfix
[ ] Feature
[x] Other...Documentation update
```
Issue Number: #1300 
```
[ ] Yes
[x] No
```
> docs(redis): update Redis microservice option with client options

- content/recipes/sql-typeorm.md
- content/techniques/sql.md
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
> Added synchronize warning in database docs

- content/graphql/complexity.md
Documents this [PR](https://github.com/nestjs/graphql/pull/1088)
> docs(graphql): Complexity on Query and Mutation

- content/microservices/basics.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs update
```
```
[ ] Yes
[x] No
```
> docs(microservices) clarify applicability of @MessagePattern decorator

- content/graphql/federation.md
A rough, first draft
Examples need to be tested and some extra text would be nice
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Docs
```
> Docs: code-first federation

- content/recipes/serve-static.md
More clear ServeStaticModule configuration description in docs.
```
[ ] Bugfix
[ ] Feature
[-] Other... Please describe: Docs update
```
Issue Number: [#1153](https://github.com/nestjs/docs.nestjs.com/issues/1153)
```
[ ] Yes
[-] No
```
> docs(@nestjs/serve-static) update serve-static module description

- content/techniques/mongo.md
- content/techniques/sql.md
- [v] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[v] Other... Please describe: Documentation fix
```
Issue Number: #1442
Fixes #1442
```
[ ] Yes
[v] No
```
> Multiple database connections using getConnectionToken

- content/microservices/grpc.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/pull/5143#issuecomment-665585769
```
[ ] Yes
[x] No
```
> docs(microservices): add gRPC Metadata examples

- content/techniques/server-sent-events.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/pull/4842
```
[ ] Yes
[x] No
```
> doc(sse): Document sse feature 

- content/graphql/cli-plugin.md
- content/openapi/cli-plugin.md
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
```
[ ] Yes
[X] No
```
While implementing e2e tests for nest graphql server, I run into issue with compiling graphql schema using plugin.
I spent some time searching for a workaround and found it. Thought it is worth documenting.
>  docs(plugins) ts-jest integration docs for graphql and swagger

- content/openapi/cli-plugin.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The variable name used in the example description doesn't match the example code.
The variable name used in the example description matches the example code.
```
[ ] Yes
[x] No
```
> content(): wrong variable name

- content/graphql/enums.md
```
[ ] Bugfix
[x] Feature
[ ] Docs
```
Issue Number: https://github.com/nestjs/graphql/pull/1129
```
[ ] Yes
[x] No
```
> feat(): Add support for enum descriptions and value deprecation

- package-lock.json
- package.json
> docs(cli): adds resource schematic to usages.md - fixes #1551 

- content/techniques/mongo.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
[nestjs/mongoose#637](https://github.com/nestjs/mongoose/pull/637)
```
[ ] Yes
[x] No
```
Most of the content are copy from [mongoose](https://mongoosejs.com/docs/discriminators.html).
> docs(mongo): add mongoose discriminator document

- content/techniques/configuration.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Documentation for https://github.com/nestjs/config/pull/397
> docs(config): Add documentation for validate function

- content/techniques/queues.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: #1550
```
[ ] Yes
[x] No
```
Fix #1550
> docs(queue): separate processor process

- content/faq/errors.md
- src/app/homepage/menu/menu.component.ts
- src/app/homepage/pages/faq/errors/errors.component.ts
- src/app/homepage/pages/faq/faq.module.ts
This starts a documentation of common errors people may run into
when using the framework. The errors are written in a generic way
to hopefully allow for easily understanding the errors.
```
[ ] Bugfix
[X] Feature
```
No docs on errors that commonly happen (common from SO, Discord, and GitHub issues)
Docs now exist on _some_ errors.
```
[ ] Yes
[X] No
```
> docs(errors): adds docs for some common errors

- content/techniques/configuration.md
```
[ ] Bugfix
[x] Feature
[x] Docs
```
Adding doc how to add yaml file custom configuration
```
[ ] Yes
[x] No
```
> feat(yaml-config): adding yaml custom configuration

- content/techniques/task-scheduling.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: https://github.com/nestjs/schedule/issues/376
Add documentation about additionnal parameters of the Cron decorators.
```
[ ] Yes
[x] No
```
> docs(@nestjs/schedule): add documentation about additionnal parameters of the Cron decorator

- content/techniques/configuration.md
refs nestjs/config#121
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: nestjs/config#121
```
[ ] Yes
[x] No
```
> docs(config): add use cache

- content/graphql/scalars.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Documentation for https://github.com/nestjs/graphql/pull/1253
> docs(): add instructions on how to use custom scalar type mappings

- content/middlewares.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Type of the `next` parameter should be `NextFunction`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/index.d.ts#L107
Even eslint gives an error: **Don't use `Function` as a type. The `Function` type accepts any function-like value.**
```
[ ] Yes
[x] No
```
> docs(middleware): update logger middleware code example

- content/recipes/prisma.md
The docs for the Prisma recipe now use the new Prisma Migrate (which will be released tomorrow, Tuesday, Dec 8) instead of introspection.
> docs(prisma): use prisma migrate instead of instrospection

- content/techniques/events.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
This PR does the following thing:
- change the order of the sections in the `events` part. Now, first emitting events will be described, then listening to events
- the use of multilevel wildcards are explained. regular wildcards (`*`) are only one level deep!
https://github.com/nestjs/event-emitter/issues/25
Clarify the use of events and multilevel wildcards
```
[ ] Yes
[x] No
```
> [Docs]: Improve Events

- content/techniques/logger.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
doc for [pr](https://github.com/nestjs/nest/pull/5681)
> docs(common): timestemp inside LoggerSerivce can be overridden

- content/graphql/resolvers-map.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Missing word
Missing word is now included
```
[ ] Yes
[x] No
```
> docs(graphql): Fix missing type

- content/security/authorization.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The example starts out with a function-based example for the Read permission, then switches to Create (while the method being decorated is still `findAll` - not a create method even).
Example updated to use Read permission in all parts of the example
```
[ ] Yes
[x] No
```
> docs(authorization): Improve consistency in PoliciesGuard example

- src/app/homepage/pages/microservices/custom-transport/custom-transport.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Docs do not demonstrate using the `CustomStrategy` options when creating a microservice which misses out on some possible type safety and adds more clarity to the docs
```
[ ] Yes
[x] No
```
> docs(microservices): custom transport typings

- content/techniques/file-upload.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, multer module settings updated
> docs(file-upload): multer module settings updated

- content/fundamentals/unit-testing.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Current docs have a hint that refers to the `e2e` directory, not the `test` directory as generated by the CLI. Additionally it suggests a `e2e-test` suffix that won't work with the jest config generated by the CLI.
Docs reflect the CLI behaviour.
```
[ ] Yes
[x] No
```
> (docs) Update hint to reflect CLI generated files

- content/recipes/prisma.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Deprecated usage of generated Prisma types has been updated.
```
[ ] Yes
[x No
```
> docs(prisma): adjust imports in prisma recipe

- src/app/homepage/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The year has been updated from `2020` to `2021`
```
[ ] Yes
[x] No
```
> docs: update the year in footer

- content/security/authorization.md
From the context, I understood that a claim represents what the subject can do. Could you please accept the pull request if it's the case
```
[ ] Bugfix
[ ] Feature
[x ] Docs
```
```
[ ] Yes
[ x] No
```
> [Docs] : Update authorization.md

- content/recipes/terminus.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added link to examples for terminus
> docs(terminus): added link to examples for terminus

- content/techniques/sql.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, fix warning as this notice should be the same color as the one below, see screenshot
> docs(database): fix warning

- content/security/authentication.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Not exporting JwtModule in the tutorial.
Added JwtModule to avoid errors.
```
[ ] Yes
[x] No
```
> docs(authentication): update authentication.md

- content/microservices/exception-filters.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, correct this warning as it should be yellow orange like all warnings, instead it is red.
See screenshot
> docs(microservices): fix warning

- content/recipes/mongodb.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, it corrects the warnings as they are yellow-orange like the warnings and hints as they are blue
See screenshot
> docs(mongoose): fix warning and hint

- content/recipes/sql-typeorm.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, fix this warning should be yellow orange like all warnings, while the hints are blue
See screenshot
> docs(typeorm): fix warning and hint

- content/recipes/sql-sequelize.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, fix this warning should be yellow orange like all warnings, while the hints are blue
See screenshot
> docs(sequelize): fix warning and hint

- content/cli/workspaces.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, correct these warnings as they should be yellow orange like all warnings, instead they are red.
See screenshot
> docs(cli): fix warning

- content/security/authorization.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
I slightly updated casl example to show how to configure v5 to use classes. The behavior is different in comparison to v4
```
[ ] Yes
[x] No
```
> docs(authorization): updates casl example in accordance to the changes in v5

- content/migration.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The TS example for Terminus doesn't work.
The example now works.
```
[ ] Yes
[x] No
```
> docs(migration): missing controller in terminus example

- content/introduction.md
Please check if your PR fulfills the following requirements:`
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
No readability
Improves docs readability
```
[ ] Yes
[x] No
```
> Alternative installs should be on a separate session

- content/security/cors.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, text enhancement
> docs(cors): improvement

- src/app/homepage/footer/footer.component.html
- src/app/homepage/footer/footer.component.ts
fix issue https://github.com/nestjs/docs.nestjs.com/issues/1721
> update current date(year)

- content/techniques/events.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added link to example for event emitter
> docs(events): added link to example for event emitter

- content/techniques/file-upload.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added link to example for file upload
> docs(file-upload): added link to example for file upload

- content/techniques/server-sent-events.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, improvement for the example sse
> docs(sse): improvement for the example sse

- content/recipes/serve-static.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, rename subtitle `Summary` in `Example`
> docs(recipes): rename subtitle

- content/recipes/hot-reload.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added subtitle `Example`, as it is missing
> docs(hot-reload): added subtitle for example

- content/recipes/cqrs.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added subtitle for example cqrs, as it is missing.
> docs(recipes): added subtitle for example cqrs

- content/microservices/grpc.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added subtitle for example grpc, as it is missing.
> docs(microservices): added subtitle for example grpc

- content/faq/multiple-servers.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
P.s. NestJS ♥️
> docs(https): improvement

- content/faq/http-adapter.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(http-adapter): improvement

- content/application-context.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, rename `ApplicationModule` in `AppModule` 
P.s. NestJS ♥️
> docs(application-context): improvement

- content/graphql/quick-start.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added subtitle for example graphql code first
> docs(graphql): added subtitle for example graphql code first

- content/websockets/adapter.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(websockets): improvement

- content/security/authentication.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added subtitle for example authentication jwt.
> docs(authentication): added subtitle for example authentication jwt

- content/techniques/server-sent-events.md
As a first time learner about SSE, I read this doc and found this phrase confusing. I think this phrasing might be easier to understand
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
Documentation typo and hard-to-understand phrasing.
Fixing type, rephrasing.
```
[ ] Yes
[X] No
```
> docs(techniques): SSE typo & rephrasing

- content/graphql/resolvers-map.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
This PR, added apostrophe in graphql resolvers content
> docs(graphql): added apostrophe in graphql resolvers content

- content/techniques/caching.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added link to example for caching
> docs(caching): added link to example for caching

- content/techniques/serialization.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added link to example for serializer
> docs(serialization): added link to example for serializer

- content/microservices/rabbitmq.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
P.s. NestJS ♥️
> docs(microservices-rabbitmq): improvement

- content/microservices/redis.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(microservices-redis): improvement

- content/microservices/nats.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(microservices-nats): improvement

- content/microservices/kafka.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(microservices-kafka): improvement

- content/microservices/mqtt.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(microservices-mqtt): improvement

- content/graphql/resolvers-map.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
https://docs.nestjs.com/graphql/resolvers#generating-types
This PR, modify bracket location from little awkward sentence.
> docs: modify bracket location from little awkward sentence

- content/discover/who-uses.json
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
> docs(who-uses): add WeOptimeye company

- content/discover/who-uses.json
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
> docs(who-uses): add BeMum company

- content/graphql/quick-start.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added subtitle for example graphql schema first
P.s. NestJS ♥️
> docs(graphql): added subtitle for example graphql schema first

- content/application-context.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added link to example for application context
> docs(application-context): added link to example for application context

- content/security/cors.md
Refs nestjs/nest#6118
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: nestjs/nest#6144
```
[ ] Yes
[x] No
```
> docs(security): add info about CorsOptionsDelegate

- content/graphql/federation.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, improvement in the section `Federated example: Gateway`
> docs(graphql-federation): improvement

- content/recipes/cqrs.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
> docs: ✏️ update to use correct method name for events in cqrs

- src/app/homepage/homepage.component.scss
- src/app/homepage/homepage.component.ts
fix issue https://github.com/nestjs/docs.nestjs.com/issues/1790
> fix carbon

- content/controllers.md
It took me two years to discover the CRUD generator randomly. Should be worth mentioning it's existence on the controller's page imo.
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
```
[ ] Yes
[X] No
```
> Added CRUD generator to controllers page

- content/security/authentication.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added guards with multiple strategies
> docs(authentication): added guards with multiple strategies

- content/fundamentals/unit-testing.md
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
Issue Number: https://github.com/nestjs/nest/pull/6071
Docs for new `setLogger`method of TestModuleBuilder (https://github.com/nestjs/nest/pull/6071)
```
[ ] Yes
[X] No
```
> docs(fundamentals): updates testing to explain new setLogger method

- content/first-steps.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: https://github.com/nestjs/nest/issues/6465
```
[ ] Yes
[x] No
```
> docs: specify which nodeJs versions are supported (i.e. stable LTS)

- content/techniques/caching.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The docs don't talk about the current default ttl, a naive user might assume they don't need to worry about expiration, and have issues with getting their code to work.
Improved documentation.
```
[ ] Yes
[x] No
```
No
> Improve documentation on cache ttl

- content/migration.md
- content/recipes/terminus.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
- Adds a chapter about TypeOrmHealthIndicator
- Replaces the deprecated `DNSHealthIndicator` with `HttpHealthIndicator` to align with Terminus 7.1.0
> Add information about Terminus 7.1.0 and add TypeOrm Health Indicator docs

- content/techniques/validation.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: 
#1785
#1795 
Added mapped types section
```
[ ] Yes
[x] No
```
This PR, added mapped types section
P.s NestJS ♥️ 🙌
> docs(techniques): added mapped types section

- content/techniques/queues.md
```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added JOB_REF provider
> docs(queues): added JOB_REF provider

- content/microservices/grpc.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: #1776
N/A
```
[ ] Yes
[x] No
```
This PR, updated documented grpc sample
> docs(microservices): updated documented grpc sample

- content/security/rate-limiting.md
```
[ ] Bugfix
[x] Feature
```
No docs for the new `ThrottlerModule`
Docs exist for the new `ThrottlerModule`.
```
[ ] Yes
[X] No
```
Definitely gonna need a read through and a good update from @johnbiundo, but I wanted to get a first draft up so we could figure out where to go from here.
> docs(throttle): first draft of docs for the throttler module

- content/techniques/file-upload.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added types for UploadedFile argument
> docs(file-upload): added types for UploadedFile argument

- content/microservices/grpc.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/4799
```
[ ] Yes
[ ] No
```
> feat: update grpc docs

- content/techniques/task-scheduling.md
- package-lock.json
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: #6538
https://github.com/nestjs/nest/issues/6538
```
[ ] Yes
[x] No
```
> docs(common): fix task-scheduling docs misleading

- content/discover/who-uses.json
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
> docs(discover): add nemovote

- content/recipes/crud-generator.md
Related to https://github.com/nestjs/schematics/pull/610
> Renamed @Put to @Patch

- content/middlewares.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: https://github.com/nestjs/nest/issues/543#issuecomment-513530320
```
[ ] Yes
[x] No
```
The proposed solution is from the linked [issue comment](https://github.com/nestjs/nest/issues/543#issuecomment-513530320). Thanks for this change goes to @felixhayashi.
> docs(middlewares): Add hint for global middlewares and DI

- content/recipes/sql-typeorm.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, in the typeorm section in recipes, rename `ApplicationModule` to `AppModule` of this Hint.
> docs(recipes-typeorm): improvement

- content/recipes/sql-sequelize.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, in the sequelize section in recipes, rename `ApplicationModule` to `AppModule` of this Hint.
P.s. NestJS ♥️
> docs(recipes-sequelize): improvement

- content/recipes/mongodb.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, in the mongodb section in recipes, rename `ApplicationModule` to `AppModule` of this Hint.
> docs(recipes-mongodb): improvement

- content/techniques/validation.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
P.s. NestJS ♥️
> docs(validation): improvement

- content/techniques/caching.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
> docs(caching): improvement

- content/graphql/scalars.md
- content/techniques/logger.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, renaming `ApplicationModule` in `AppModule` in the following sections: graphql(`scalars`) and techniques(`logger`)
> chore(): improvements
