nestjs/docs.nestjs.com

src/app/homepage/pages/custom-decorators/custom-decorators.component.ts

If a reader copy/paste the example of custom-decorators, it require the reserved word "export" when it want use the custom-decorator (import from another file).

fix(custom-decorators): Missing export word

---

src/app/homepage/pages/pipes/pipes.component.ts

Hi,
I've just been through this part of the tutorial and noticed that a deprecated import was used.
Indeed, `HttpException` is now part of `@nestjs/common` instead of `@nestjs/core`.
Moreover, as a dedicated exception class now exists for this particular usecase (`BadRequestException`), I just thought it would be a good idea to use it.

Pipes: (fix) deprecated import of HttpException

---

src/app/homepage/pages/techniques/sql/sql.component.ts

`autoSchemaSync` option has renamed to `synchronize`
https://github.com/nestjs/typeorm/issues/3#issuecomment-354224898

Fix wrong ormconfig.json in sql docs

---

src/app/homepage/pages/components/components.component.html

I've removed the part about `emitDecoratorMetadata ` as I'm not sure why it's relevant in the `Components` docs. This is necessary for any kind of decorator, not just Component, right?
SO basically this is a requirement to use nestjs, not just the components.

update(docs): update components docs

---

src/app/homepage/pages/advanced/hierarchical-injector/hierarchical-injector.component.ts

ERROR in src/app/homepage/pages/advanced/hierarchical-injector/hierarchical-injector.component.ts(7,3): error TS1005: ',' expected.

fix compilation error

---

src/app/homepage/pages/recipes/passport/passport.component.ts

This is to avoid inconsistency between not providing a token & providing a bad token

Update callback to throw UnauthorizedException

---

src/app/homepage/pages/recipes/sql-typeorm/sql-typeorm.component.ts

The documentation as is (npm install --save typeorm mysql) will not work. autoShcemaSync has been changed to synchronize: http://typeorm.io/#/connection-options.

Changed autoSchemaSync to synchronize (new way according to typeorm)

---

src/app/homepage/pages/interceptors/interceptors.component.html

Since version 5, the `@Interceptor()` is deprecated and `@Injectable()` is expected.

Fix deprecated decorator for interceptors

---

src/app/homepage/pages/pipes/pipes.component.ts

```javascript
export class ParseIntPipe implements PipeTransform<string, number> {
async transform(value: string, metadata: ArgumentMetadata): number {
//                                                        ^ wrong type if is an async function
}
}
```
transform is a async function. The return type of an async function must be the global ```Promise<T>``` type.
I removed async in PR. Async function is redundant in this case.

Fixed ParseIntPipe

---

src/app/homepage/pages/controllers/controllers.component.html
src/app/homepage/pages/first-steps/first-steps.component.html
src/app/homepage/pages/introduction/introduction.component.html

👋. I've just started to go through the docs and wanted to first say, the documentation is awesome!
I noticed minor grammatical changes (as well as other small improvements) that can be made to improve readability, so here's the first PR I had in mind. This PR only covers the **Introduction**, **First Steps**, and **Controllers** pages.
There are also a few different things that I didn't introduce but thought might be useful to have as well. They are:
- Noting that the Nest CLI contains a series of build prompts before a project is scaffolded. This isn't mentioned in the Setup section of **First Steps**.
- Providing a small blurb (or a link to) to quickly reference what `NestFactory` is, in the Setup section of **First Steps**. The line as follows says: `It uses  NestFactory to create the …

Small grammatical improvements to Intro, First Steps, and Controller Pages

---

src/app/homepage/pages/techniques/mongo/mongo.component.html

```
[X] Bugfix
[ ] Feature
```
The Techniques/Mongo page seems to be refering to an ORM different than Mongoose (specifically TypeORM) but it mentions and links to Mongoose. Which makes it seem as if it's comparing Mongoose with itself.
Just changed some of the lines to refer to TypeORM instead of Mongoose, to make it more clear.
```
[ ] Yes
[X] No
```

docs(@nestjs/mongoose) Change 'Mongoose' to 'ORM' on some lines

---

src/app/homepage/pages/middlewares/middlewares.component.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: **Documentation update**.
```
The Middleware documentation for Routing Matching is the same as in Controllers, but the code example isn't the same.
It is easier to understand the example and the behaviour of the asterisk in route matching.
```
[ ] Yes
[x] No
```

(docs): Update code snippet to match example

---

src/app/homepage/pages/controllers/controllers.component.html

Great project! Very solid. Going through the docs and saw some minor typos/incorrect info. I will be going through the guide so will see what else I can help with.

[Controllers guide] Fix typos

---

src/app/homepage/pages/recipes/swagger/swagger.component.html

```
[ ] Bugfix
[ ] Feature
```
The `Multiple specifications` in the **swagger** section invite to the user to navigate to the
`http://localhost:3000/api/docs` to see the SwaggerUI for the `Dogs` endpoint but the specified URL is wrong. Seems to be a typo.
Set the URL to navigate to see the SwaggerUI for the Dogs to `http://localhost:3000/api/dogs`.
```
[ ] Yes
[x] No
```

docs: fix typo in swagger docs

---

package-lock.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/homepage/menu/menu.component.ts
src/app/homepage/pages/recipes/terminus/terminus.component.html
src/app/homepage/pages/recipes/terminus/terminus.component.ts
src/app/homepage/pages/recipes/terminus/terminus.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/terminus/issues/5
Added documentation for nestjs/termius
```
[ ] Yes
[x] No
```
Blockers:
- nestjs/terminus npm release

feat(docs): Add nest/terminus documentation

---

content/graphql/quick-start.md

autoSchemaFile should be mentioned in `forRoot` instead of `definitions`
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
corrected the doc
```
[ ] Yes
[ x] No
```

autoSchemaFile should be mentioned in forRoot

---

content/recipes/terminus.md

In the sample code provide, in app.module.ts code imports TerminusOptions,
but TS says that terminus-options.service has no exported members
TerminusOptions if we use the sample code above for terminus-options.service.ts
This commit fix it, the good import should be TerminusOptionsService.
```
[ x] Bugfix
[ ] Feature
```
In the sample code provide, in app.module.ts code imports TerminusOptions,
but TS says …

fix(terminus): bad TerminusOptions import

---

content/recipes/swagger.md

```
[x] Bugfix
```
Since nestjs/swagger#218, swagger-ui-express has to be installed manually when using express. When it is not installed, you get the message `The "swagger-ui-express" package is missing. Please, make sure to install this library ($ npm install swagger-ui-express) to take advantage of SwaggerModule.` This change should be reflected in the docs.
```
[ ] Yes
[x] No
```

Add required package swagger-ui-express to swagger install docs

---

content/controllers.md

Please check if your PR fulfils the following requirements:
```
[x] Bugfix
[ ] Feature
```
Clicking 'Status codes' anchor link on controllers page does not work correctly, attempting to take the user to https://docs.nestjs.com/#status-code
Clicking the link correctly takes user to the anchor point for status codes on the controllers page.
```
[ ] Yes
[x] No
```

docs(controllers) fix anchor link to Status codes on controllers page

---

content/first-steps.md

```
[ ] Bugfix
[ ] Feature
```
While skimiing through the `first-steps`in the documentation, I've found that it's written `main.ts.ts` in the file name which confused me.
This PR makes that `main.ts`.
Currently, in the `first-steps` the file name shows `main.ts.ts`
This PR removes the extra `.ts`, hence the file name will show `main.ts`
```
[ ] Yes
[x] No
```

docs(first-steps.md) remove extra extension from main.ts

---

content/techniques/http-module.md

The method `forRootAsync` does not exist on the class `HttpModule`. Fixing docs for the correct method: `registerAsync`
I'm not pretty sure. But maybe `forRootAsync` It's more consistent with other implementations
```
[ ] Bugfix
[ ] Feature
Documentation mismatch
```
```
[ ] Yes
[x] No
```

docs(http-module) fix method name

---

src/app/homepage/homepage.component.scss

```
[X] Bugfix
[ ] Feature
```
Issue Number: #361 
Solves the problem expressed on the issue.
Now when you using the keyboard and access the bookmark anchor is visible
> ![ezgif-2-7c2e1254cbbe](https://user-images.githubusercontent.com/7026066/56079950-cb742000-5dc0-11e9-81c8-ce84932280c3.gif)
```
[ ] Yes
[X] No
```

fix(page): see bookmark anchors when are focused

---

content/techniques/sql.md

```
[ ] Bugfix
[ ] Feature
```
From https://docs.nestjs.com/techniques/database
```typescript
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Photo } from './photo.entity';
@Injectable()
export class PhotoService {
constructor(
@InjectRepository(Photo)
private readonly photoRepository: Repository<Photo>,
) {}
async findAll(): Promise<Photo[]> {
return await this.photoRepository.find();
}
}
```
```typescript
import { Injectable } …
```

docs(sql.md): Update service

---

content/techniques/configuration.md

The semicolons in the .env file provided in the documentation are not
required. (The .env file is not a TypeScript or JavaScript file.)
Moreover, in the example provided, with the semicolon present, the value
for e.g. the DATABASE_USER environment variable will end up being the
string "test;", not "test". Presumably the latter is what is actually
intended.
```
[ ] Bugfix
[ ] Feature
```
The example code for setting up environment variables using a `.env` file misleading suggests that each line in the `.env` …

Remove semicolons from example .env file

---

content/techniques/validation.md

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Documentation
```
From reading the docs I understood that you need to use `forbidNonWhitelisted` INSTEAD of `whitelist` but then the NestJS server does not stop processing the request. To stop processing the request `whitelist` must be enabled AND `forbidNonWhitelisted` must be enabled too.
**Example:**
```ts
app.useGlobalPipes(new ValidationPipe({
forbidNonWhitelisted: true,
transform: true,
whitelist: true,
}));
```

docs(techniques): fix misunderstanding about "forbidNonWhitelisted"

---

content/websockets/adapter.md

Updated **Advanced (custom adapter)** section on the **WebSocket - Adapters** page.
* `empty` has now been deprecated and in place `EMPTY` has been implemented from the rxjs library.
* MessageMappingProperties is no longer in `@nestjs/common` and has been moved to `@nestjs/websockets`
* `tap` was imported from rxjs but never used

WebSocket Custom Adapter Docs - Updated

---

content/graphql/guards-interceptors.md

This PR makes a few changes to the prose of this doc in order to sound more natural :)
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
```
[ ] Yes
[X] No
```

docs(graphql): fix typo and prose

---

content/techniques/configuration.md

If we don't set NODE_ENV's value, it'll be undefined, then the service will try to read the `undefined.env` file which is supposed to be `development.env`, so its value needs to be `development` by default.
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
```
[ ] Yes
[X] No
```

the default value of NODE_ENV should be development

---

content/techniques/configuration.md

1. valid() no longer accepts Array types as inputs. Instead it expects allowed
values to be passed in as parameters.
2. validate() now has to be called on the schema instead of passing the schema
into the function.
```
[x] Bugfix
[ ] Feature
```
joi 16.0.0 introduces some breaking changes that make the code in the documentation fail.
Code no longer fails.
```
[ ] Yes
[x] No
```

docs(techniques/configuration): Adapt for joi 16.0.0

---

content/techniques/mongo.md

I'm not sure this is correct, but with `InjectModel()` I have got error
```
Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument at index [0] is available in the UsersModule context.
```
and I have discovered `InjectModel` is a decorator and found `getModelToken`, which works fine.
Improved JS example for `cats.service` in `techniques/mongo`.

Improved JS example in techniques/mongo

---

content/introduction.md

docs(introduction): add default URL for the local server
The documentation does not include what URL to use for the default development server. This information is also not part of the startup output. I had to look in the source code to figure out what port the server is using by default.
```
[ ] Bugfix
[ ] Feature
```
The introduction does not include the URL for the local development server.
```
[ ] Yes
[x] No
```

docs(introduction) add default URL for the local server

---

content/fundamentals/unit-testing.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update documentation
```
There is wrong link leads to `localhost:4200` instead of `docs.nestjs.com` in the `content/fundamentals/unit-testing.md` file.
Issue Number: #817 
The Links lead to correct page
```
[ ] Yes
[x] No
```

fix(testing): fix wrong link lead to localhost

---

content/techniques/hot-reload.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update documentation
```
There are two wrong links lead to `localhost:4200` instead of `docs.nestjs.com` in the `content/techniques/hot-reload.md` file.
Issue Number: #814 
The Links lead to correct page
```
[ ] Yes
[x] No
```

fix(hot-reload): fix wrong links from localhost to docs.nestjs.com

---

content/guards.md

```
[x] Bugfix
[ ] Feature
```
Duplicate word 'we' in Guard docs.
Removed one 'we'.
```
[ ] Yes
[x] No
```

docs(guards) remove duplicate word 'we'

---

src/app/homepage/homepage.component.html
src/app/shared/components/toc/toc.component.html
src/app/shared/components/toc/toc.component.ts
src/styles.scss

```
[ ] Bugfix
[x] Feature
```
Currently the toc component has two problems related with a11y (accessibility):
- Is not focusable
- Does not indicate where you are going to go (you can not the preview URL)
The new improvements are:
- The toc elements are focusable
- You can see where you are going to go (you can see the URL)
- When you select a title, the focus is transferred to the title to continue browsing
- The focus flow is changed
- ![image](https://user-images.githubusercontent.com/7026066/58147542-a5903580-7c20-11e9-9 …

feat(A11Y): improve a11y on toc component

---

content/microservices/basics.md

Other - documentation update
Update code example in docs, ApplicationModule fails, Nest CLI uses AppModule (which seems to be the correct import)

ApplicationModule changed to AppModule

---

content/techniques/sql.md

It isn't clear why using a glob path won't work properly with webpack. Adding text to specify that it is hot reloading what won't work and changing the link to a nestjs doc page.
Documentation

Specify warning for using a glob path in typeorm entities

---

content/techniques/mongo.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(mongodb): document new functionalities

---

content/graphql/guards-interceptors.md
content/graphql/mutations.md
content/graphql/resolvers-map.md
content/graphql/subscriptions.md
content/guards.md
content/pipes.md
content/recipes/mongodb.md
content/recipes/prisma.md
content/recipes/sql-sequelize.md
content/recipes/sql-typeorm.md
content/techniques/mongo.md

```
[ ] Bugfix
[ ] Feature
```
Currently, there are 37 locations across 11 files in the docs that use `return await`, which is [considered a bad practice](https://eslint.org/docs/rules/no-return-await). 
No use of `return await` in the docs
```
[ ] Yes
[x] No
```
Search and replace was done by VSCode.

docs(common): remove return await syntax

---

content/techniques/logger.md

Logger section contains relative link to fundamentals/injection-scopes, but we need root link, because otherwise it points to https://docs.nestjs.com/techniques/logger/fundamentals/injection-scopes

fix link for injection scopes

---

content/cli/workspaces.md
tools/transforms/content-package/services/renderer/link.renderer.ts

```
[x] Bugfix
[ ] Feature
```
If the developer uses `[Link](/my-link#test)` it would get compiled into `<a routerLink="/my-link%23test">Link</a>` (`routerLink` does not work with hashes).
Links with hashes will get compiled `<a href="/my-link#test">Link</a>`
```
[ ] Yes
[x] No
```
This PR was an attempt to remove all the "dangling links" Dgeni warnings. Unfortunately, these warnings seem to occur because of the "redirectTo" inside the Angular Router. Dgeni does not know that these URLs exist. This  can be …

fix: Markdown link render to work with hash

---

content/techniques/performance.md

```
[X] Bugfix
[ ] Feature
```
The adapter portion of the documentation refers to the `AppModule` as both `AppModule` and `ApplicationModule`.
Both examples use a consistent variable name - `AppModule`
```
[ ] Yes
[X] No
```

docs(performance): consistent variable naming for app module

---

content/graphql/resolvers-map.md

It looks a little strange that the argument is called `id`, although in fact it is a class that contains different properties, one of which is `id`.

improvement(docs): another argument name

---

content/interceptors.md

Add customizable logic to timeout interceptor.
Now, just before timeout is thrown, additional actions (like releasing resources) can be taken.
```
[ ] Bugfix
[ ] Feature
```
Extend sample timeout interceptor. Now can easily add additional logic before throwing `ReqestTimeoutException`.
```
[ ] Yes
[x] No
```

docs(interceptors):  Update interceptors.md, extend timeout interceptor

---

content/recipes/hot-reload.md

Fix webpack.config.js code for "Without CLI" option
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Error in documentation
```
Error when reproduce described steps
Application run successful in hot-reload mode.
```
[ ] Yes
[X] No
```

docs(hot-reload.md): Fixed error in code example

---

content/recipes/swagger.md

```
[ ] Bugfix
[ ] Feature
```
Currently if the import from './app.module is imported as {ApplicationModule} it shows as an error. It should be {AppModule} as like any other place.
```
[ ] Yes
[x] No
```

Changed import {ApplicationModule} to {AppModule}

---

content/fundamentals/unit-testing.md

the 'Request-scoped' link was missing character 's' in the end, causing link not to work.
```
[x] Bugfix
[ ] Feature
```
'Request-scoped' link is not working in 'Testing' section
'Request-scoped' link points to the correct section
```
[ ] Yes
[x] No
```
I closed previous PR because i thought i had commited change in one of the main branches. It appears that 'Suggest edits' link automatically creates new branch..

bugfix(docs): add missing character in link

---

content/recipes/swagger.md

This commit adds documentation for Open API Extensions via the `@ApiExtension` decorator as per 
[https://github.com/nestjs/swagger/pull/536](https://github.com/nestjs/swagger/pull/536).
```
[ ] Bugfix
[x] Feature
```
Issue Number: Adds docs for: [https://github.com/nestjs/swagger/pull/536](https://github.com/nestjs/swagger/pull/536)
Adds docs for `@ApiExtension` decorator.
```
[ ] Yes
[x] No
```

docs(swagger): add api extension to swagger docs

---

content/microservices/kafka.md

```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/3739
KafkaOptions includes support for the [kafka.js subscribe fromBeginning option](https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning).
```
[ ] Yes
[x] No
```
See related PR: https://github.com/nestjs/nest/pull/4146

docs(microservices): add subscribe option to kafka docs

---

content/websockets/adapter.md

```
[ ] Bugfix
[ ] Feature
```
Trying to import socket.io-redis with 
```
import * as redisAdapter from 'socket.io-redis';
```
results in:
```
const redisAdapter = redisIoAdapter(REDIS_CONNECT_CONFIG);
^
TypeError: redisIoAdapter is not a function
```
Changing it to 
```
import redisAdapter from 'socket.io-redis';
```
Works and the Nest server starts up correctly.
```
[ ] Yes
[x] No
```

import fix for new version of socket.io-redis

---

content/techniques/security.md

Explain how to use express-rate-limit when behind a reverse proxy or load balancer.
Fixes https://github.com/nestjs/docs.nestjs.com/issues/1065
Fixes https://github.com/nfriedly/express-rate-limit/issues/176
```
[ ] Bugfix
[ ] Feature
```
It may be unclear how to use the recommended rate-limiter when behind a proxy or load balancer.
Issue Number: #1065
The documentation explains the necessary configuration and provides a code sample
```
[ ] Yes
[x] No
```

docs(security): rate-limiting behind load balancers

---

content/techniques/sql.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Database documentation updated.
```
It shows `app.module.ts` filename for the code snippet but code itself reflects `app.service.ts` file
I changed `app.module` filename as `app.service`
```
[ ] Yes
[x ] No
```

docs(database): show app.service file to inject sequelize object

---

content/cli/usages.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest-cli/issues/587
Add `preserveWatchOutput` in CLI usage section. Description are getting from [typescript official docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
```
[ ] Yes
[x] No
```

docs(cli): add preserveWatchOutput in cli section

---

content/recipes/hot-reload.md

In a monorepo with multiple apps the paths should not be hardcoded:
- `entry: ['webpack/hot/poll?100', './src/main.ts']` should be `entry: ['webpack/hot/poll?100', './apps/appname/src/main.ts']`
- `new StartServerPlugin({ name: 'main.js' })` should be `new StartServerPlugin({ name: 'apps/appname/main.js' })`
Depending on which app has been started.
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Updated documentation
```
Hardcoded paths
Dynamic paths
```
[ ] Yes
[X] No
```

Update hot-reload.md to work with monorepo

---

content/recipes/swagger.md

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: documentation addition
```
There currently is no specific example of how to use NestJS Swagger annotations to annotate an API property that is a polymorphic array (i.e. an array whose members may be of different types). 
I propose to add an example that shows how to use a raw schema definition to annotate a polymorphic array, specifying the possible types that it may include.
```
[ ] Yes
[X] No
```

docs(): add polymorphic array swagger example

---

content/fundamentals/execution-context.md

Dear @kamilmysliwiec ,
this is the requested PR (see https://github.com/nestjs/graphql/issues/705 ) to update the docs and describe that you now can check for `argumentsHost.getType() === 'graphql'`.
All the best,
Johannes

docs: add info for gql argumentshost

---

content/cli/usages.md

Corrected command for generating an application within a monorepo. As stated [here](https://docs.nestjs.com/cli/monorepo) the correct one is `app` - while `application` seems to create a new nest-application with its own package.json
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Updated documentation
```
```
[ ] Yes
[X] No
```

Corrected command to generate new application

---

content/microservices/mqtt.md

Constructor in class [`ServerMqtt`](https://github.com/nestjs/nest/blob/107b243c8b7d00c428c4ab9740dad074ec4af89d/packages/microservices/server/server-mqtt.ts#L26) uses only `url` option. See also https://stackoverflow.com/a/57137251
Updated documentation
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

ServerMqtt uses `url` option only

---

content/techniques/mongo.md

```
[ ] Bugfix
[ ] Feature
[ X] Other... Please describe: Outdated documentation section.
```
I guess "useString" method existed before but it doesn't anymore. The async configuration section in mongo still uses it tough.

Mongo async config section uses "useString" method from configService

---

content/microservices/grpc.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Docs typo fix
```
- Invalid gRPC .proto file in within the streaming section (missing semicolons)
- Typo on RxJS ReplySubject -> ReplaySubject
- No typos
```
[ ] Yes
[x] No
```
N/A

docs(gRPC): fix typos with gRPC stream section

---

content/microservices/grpc.md
content/microservices/kafka.md
content/techniques/authentication.md
content/techniques/sql.md

```
[ ] Bugfix
[ ] Feature
```
Some classes are named inconsistently across and sometimes even within examples. For example, classes related to the `User` entity:
```
+ grep -ri UsersController content/
+ wc -l
6
+ grep -ri UserController content/
+ wc -l
4
+ grep -ri UsersService content/
+ wc -l
59
+ grep -ri UserService content/
+ wc -l
10
+ grep -ri UsersRepository content/
+ wc -l
12
+ grep -ri UserRepository content/
+ wc -l
1
```
Fix https://github.com/nestjs/docs.nestjs.com/issues/1176
According to @kamilmysliwiec, …

docs(content): Pluralise class names

---

content/techniques/sql.md

```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:
```
When using Type ORM Async configuration like shown [here](https://docs.nestjs.com/techniques/database#async-configuration), There is a TypeScript error because "port" needs to be of type `number` not `string`.
Port is now of type 'number' so no TypeScript Error
```
[ ] Yes
[ x] No
```

docs(content): Async configuration port type fix

---

content/fundamentals/unit-testing.md

This URL is broken: `docs.nestjs/com`. It should probably be:
```html
<a href="https://docs.nestjs.com/fundamentals/module-ref#resolving-scoped-providers">here</a>
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: Broken URL

---

content/websockets/adapter.md

Fixes multiple app instances in e2e tests not connecting properly to socket.io-redis by reinitialising redisIOAdapter on createIOServer.
```
[x] Bugfix
[ ] Feature
```
E2E tests on mulitple app instances connected via socket.io-redis do not connect properly and cannot receive messages. This is due to the apps sharing the same `redisAdapter` instance as shown in the docs. 
E2E tests on mulitple app instances connected via socket.io-redis now create their own `redisAdapter` instance and can communicate correctly.
```
[ ] Yes …
```

docs(content): fix e2e socket.io-redis tests for multiple app instances

---

content/graphql/quick-start.md

remove --save option from is no longer needed.
Source: https://blog.npmjs.org/post/161081169345/v500
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs update
```
```
[ ] Yes
[x] No
```

--save option no longer needed for npm > 5

---

content/techniques/security.md

with 
```js
import * as helmet from 'helmet';
```
we get an error 
```error TS2349: This expression is not callable.
Type '{ default: Helmet; contentSecurityPolicy(options: IHelmetContentSecurityPolicyConfiguration): RequestHandler<ParamsDictionary, any, any, ParsedQs>; ... 12 more ...; permittedCrossDomainPolicies(options?: IHelmetPermittedCrossDomainPoliciesConfiguration): RequestHandler<...>; }' has no call signatures
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

update helmet import

---

content/techniques/authentication.md

I had hard time to figure out why validate method is not invoked, I think a quick description about passport-local default behavior _looking for username and password field in the request body_ can help starter a lot
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Documentation 
```
```
[ ] Yes
[X] No
```

Updated -- authentication.md Clarify passport-local default behavior

---

content/graphql/scalars.md

Using the alias results in an error.
Therefore, it should be removed.
Importing the library directly resolves this issue.
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Fixing a documentation error
```
Using an alias throws an error.
Accessing the library directly without an alias.
```
[ ] Yes
[X] No
```

docs: Update scalars.md

---

content/faq/request-lifecycle.md

```
[ ] Bugfix
[ ] Feature
```
Docs update
Middleware execution order is not described when it comes to middleware bound across several modules.
Issue Number: #1248
The execution order or middleware is now described when working with middleware bound across several modules.
```
[ ] Yes
[x] No
```

docs(request-lifecycle): adds information about module bound mw

---

content/techniques/logger.md

```
[ ] Bugfix
[ ] Feature
```
Adds back in a small portion of [this commit](https://github.com/nestjs/docs.nestjs.com/commit/a70b7a36b6d5571390fdb489370490709a31ad0c#diff-8af34d7d4d6dc9a3e6868c745bd543bf)
that warns when a custom logger is used and `logger: false` is set,
that Nest cannot use the custom logger for the instantiation of the
server.
Currently there is no warning of using a custom logger when it comes to instantiating the Nest server.
Issue Number: #1270 
There is now a warning about using a custom logger when …

docs(logger): adds back warning of custom logger

---

content/recipes/prisma.md

Since prisma client appended the connect() and disconnect() methods with a $, the current docs throw a deprecation warning.
```
[ ] Bugfix
[ ] Feature
```
Prisma Client throws deprecation warnings on the connect() and disconnect() methods
No deprecation warnings
```
[ ] Yes
[x] No
```

docs(prisma) update deprecated methods

---

content/microservices/rabbitmq.md

Commit fixes anchor in queueOptions of the rabbitmq microservice docs.
Link now points to the right anchor `#channel_assertQueue` instead of  `#assertQueue`.
```
[ ] Feature
[X] Other: Docs
```
QueueOptions link only redirected to top of the page, not to a specific section.
QueueOptions link now redirects to the correct section, for better readability and reduced search effort.
```
[ ] Yes
[c] No
```

docs(microservices): fix anchor to queueOptions in rabbitmq docs

---

content/recipes/serve-static.md

Add a link to the serve-static npm module in the docs

docs: add link to the serve-static module

---

content/graphql/quick-start.md

I totally missed the text below, I think this change makes the default experience better, since that's express and also makes the fastify option stand out.
```
[ ] Bugfix
[ ] Feature
```
Easy to miss the installation of apollo server in quick start.
The default experience installs the correct thing, and the experience for those using fastify is highlighted.

fix(docs): Inline default apollo install

---

content/graphql/resolvers-map.md

```
[ ] Bugfix
[ ] Feature
```
In the Resolvers of  GraphQL part, there are typo error in some code blocks showing duplicated file extensions.
The name of the file(or path) displayed correctly
```
[ ] Yes
[x] No
```

docs(graphql): remove duplicated file extension in code block

---

content/controllers.md
content/custom-decorators.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The docs show request object decorators, but the table is incomplete in both places.
The request object decorator table is complete in both places. `HostParam` has been added and the shortcuts `@Req` and `@Res()` are mentioned.
```
[ ] Yes
[x] No
```
I skipped `UploadedFile` and `UploadedFiles` because they didn't seem to be directly off of Express. If they should be added, what should the corresponding platform-specific objects be for them?

docs: add missing request object decorators

---

.github/PULL_REQUEST_TEMPLATE.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
In the PR template, there's a list of PR types and it wasn't obvious what to pick for an update to a markdown file in `content/`. I checked past PRs and saw many people filling in `Docs` as a custom type.
Docs is now an option in that list.
Since this is a docs site, I think this is a little unclear. `docs` makes sense since the PR is updating the docs, but from the perspective of the docs site, perhaps it's considered a feature or bugfix. However, feature or bugfix could also be considered to be …

chore: add docs change type to PR template

---

content/techniques/compression.md

As Fastify v3 changed from named export to default export, the previous instruction doesn't work anymore.
More information here: https://github.com/nestjs/nest/issues/5552
```
[X] Bugfix
[ ] Feature
[ ] Docs
```
Issue Number: 5552
Fix the instruction.
```
[ ] Yes
[X] No
```

Updated import from fastify-compress

---

content/techniques/task-scheduling.md

The seconds argument of setTimeout and setInterval should be in milliseconds instead, and the type should be number instead of string.
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
the expected argument called 'seconds' and has the type string.
the argument called 'milliseconds' and has the type number
```
[ ] Yes
[X] No
```

docs(task-scheduling): change seconds argument

---

content/techniques/logger.md

```
[ ] Bugfix
[x] Feature
```
I was trying to integrate [`nestjs-pino`](https://github.com/iamolegga/nestjs-pino) (json logger) in my app in the best possible way, and struggled a little bit since nestjs docs don't quite clearly explain how to best use custom logger in your app services.
The example with transient scopes seems strange to me because why would I inject custom logger to my services if I am already setting it as globally default using `app.useLogger`. If I am switching loggers, I would have to do search and …

Improve docs about using Logger

---

content/openapi/introduction.md

[x] Document
People unfamiliar with OpenAPI may fail to realize other ways to use the `OpenAPIObject` object (at least in my own case).
It is clearer that one could save the OpenAPI document as a file, rather than serving it over HTTP with `SwaggerModule.setup`.
[ ] Yes
[x] No
The use I described in this patch worked in my project but I'm not very confident though. Can somebody confirm this usage?

mention another way to consume OpenAPIObject document

---

content/techniques/authentication.md

Direct link to the http://www.passportjs.org/packages/ raises `404 Not Found`.
There isn't any direct non-404 link to passportjs strategies page from what I see.
So the goal of this PR is to just fix that 404 issue. Strategies list is pretty trivial to find from the landing page.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
Referenced page
https://docs.nestjs.com/techniques/authentication

Fix 404 link for passportjs strategies

---

content/techniques/mongo.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
https://github.com/nestjs/docs.nestjs.com/blob/master/content/techniques/mongo.md#hooks-middleware
In most cases users wants to access the document which located in `this` of the function. If we pass there anonymous function like in this example it will lose context and can confuse users.
In official mongoose examples used `function()` instead of `() => {}`
https://mongoosejs.com/docs/middleware.html#pre
Now
Function wouldn't lose context and mongoose document will be …

docs(@nestjs/mongoose): rm anonymous functions in .pre hooks

---

content/openapi/introduction.md

Removed trailing semi colon as this causes compiler issues when a user copy and pastes the sample.
- [X ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[X ] Docs
```
If a user copy and pastes the example from the OpenAPI Swagger docs they will get compiler issues as the current code is :
```
const document = SwaggerModule.createDocument(app, options, {
operationIdFactory: (
controllerKey: string,
methodKey: string
) => methodKey; …
```

docs(openapi): Removed trailing ";"

---

content/discover/who-uses.json

Added datenlotse company to who uses json file
```
[ ] Bugfix
[ ] Feature
[ X ] Docs
```
Datenlotse not beeing listed under who uses body
Datenlotse beeing listed under who uses body
```
[ ] Yes
[ X ] No
```
I am the lead backend developer at datenlotse and we are using nest.js almost exclusively for our new projects

docs(who-uses): add datenlotse company

---

content/security/helmet.md

```
[ ] Bugfix
[ ] Feature
[X] Docs
```
`import * as helmet from 'helmet'` errors, it should be `import helmet from 'helmet'`. 
Error:
```
Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
```
```
[ ] Yes
[X] No
```

fix(security/helmet): fix import statement

---

content/techniques/events.md

```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
Issue Number: #1576 
N/A
```
[ ] Yes
[x] No
```
This PR, added warning for event subscribers which cannot be subject to the scope of the request

docs(events): added warning for event subscribers 

---

content/fundamentals/unit-testing.md

This adds a section on how to replace `APP_*` token providers in testing. This follows the description by @kamilmysliwiec in https://github.com/nestjs/nest/issues/4053 . I've used the solution in my project and it worked great.
Thanks to @jmcdo29 who pointed me to that issue when I was struggling with this.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: https://github.com/nestjs/nest/issues/5821
more docs
```
[ ] Yes
[x] No
```

Add a section for overriding APP_* token providers

---

content/techniques/logger.md

Explain the use of the `NO_COLOR` environment variable to disable color in the default logger.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Minor improvement to the documentation regarding logging.
```
[ ] Yes
[x] No
```

docs(logger): Explain how to disable color

---

content/openapi/introduction.md

Change options on second argument to config, and further exemplify the options assignin it to a separated variable for added clarity
Closes [1652](https://github.com/nestjs/docs.nestjs.com/issues/1652)
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
We describe how to use swagger like this, which can lead to confusion when later on the docs we present [options](https://docs.nestjs.com/openapi/introduction#document-options). SwaggerModule.createDocument second argument is [called …

docs(swagger): change options to config so it matches types

---

content/techniques/file-upload.md

```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, added warning which specifies that "FileInterceptor()" is not compatible with third party cloud providers

docs(file-upload): added warning for cloud providers

---

content/security/helmet.md
content/techniques/performance.md

add warnings
apollo-server-fastify does not have full support for fastify v3 which
results in the playground not loading. Added a warning to either use
unstable apollo-server-fastify version that supports v3 or express.
Playground also uses CDN which requires a change to CSP if using helmet.
Added a warning containing required policy additions.
https://github.com/nestjs/nest/issues/6180
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: [Nest#6180](https://github.com/nestjs/nest/issues/6180)
Add warning advising of …

docs(fastify,helmet,apollo): add warnings

---

content/techniques/configuration.md

```
[x] Docs
```
Two links to the old Joi site are broken.
The links point to the new documentation site  (and to the Joi changelog, rather than an issue comment).
```
[x] No
```

docs(configuration): update broken Joi links

---

content/openapi/cli-plugin.md

```
[ ] Bugfix
[ ] Feature
[ ] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, fixes the hints as they are yellow orange like the warnings, instead they must be blue

docs(openapi): fix hint

---

content/websockets/gateways.md

Added warning about @nestjs/platform-socket.io depending on socket.io v2.3
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
Issue Number: nestjs/nest/issues/5676
N/A
```
[ ] Yes
[X] No
```

docs(websockets): Add socket io version warning

---

content/openapi/introduction.md

docs: corrected snippet for the options constant in the openapi introduction.md file.
- **contains an extra round bracket '**)**'.**
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The snippet for generating operation names like `createUser` instead of `UserController_createUser` does not work.
removing the round bracket solved the syntax error  
```
[ ] Yes
[x] No
```

docs: corrected snippet for options by removing the extra round brace at the end

---

content/graphql/unions-and-enums.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The name doesn't match the example output.
It does. 😄

docs(graphql): Fix union name typo

---

content/openapi/other-features.md

docs: corrected snippet for openapi other-features.md file.
- The current snippet is missing the import for the CatsModule
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
the above line I missing. This would lead to the following error
```
Cannot find name 'CatsModule'.ts(2304)
```
Added the import for CatsModule
solving the error 
```
Cannot find name 'CatsModule'.ts(2304)
```
```
[ ] Yes
[x] No
```

docs : added the missing import for CatsModule in other-features.md of the openapi

---

content/recipes/prisma.md

Prisma 2 CLI renamed from `@prisma/cli` to `prisma`
Ref: https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-the-prisma-layer-mysql
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```

docs: Prisma 2 CLI renamed from `@prisma/cli` to `prisma`

---

content/graphql/resolvers-map.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
https://docs.nestjs.com/graphql/resolvers#object-types
In capture image, SDL example's file name is "schema.gql.ts". I think SDL is not ".ts" file extension. 
Additionally, in the above example, as below image doesn't have file name.
Also, as below image, markdown code block's language is graphql.
This PR, remove graphql schema file name from SDL.

docs: remove graphql schema file name from SDL

---

content/pipes.md

Move the reminder closer to the docs about validation, so it's less easy to miss. I was implementing the example in my project, before I read a built-in solution is available. By moving it closer to the validation chapters on this page, less people will miss it when they stop reading as the subject changes to transformations.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```

docs(pipes): move docs on built-in validationpipe

---

content/components.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The docs contain misleading information about the role that an `@Injectable` decorator plays.  The `providers` section of the documentation, which is one of the first sections a new nest user will read, explicitly states several times that the `@Injectable` decorator is what differentiates a regular javascript class from that of a nest `provider`.  This has been proven to not be the case from @ericmorand 's comment [here](https://github.com/nestjs/nest/issues/6081#issuecomment-778063839 …

docs(components): clarify the use of Injectable decorators

---

content/components.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
This is a follow up to #1754 - I accidentally missed a line.
Remove an additional line that incorrectly states the `@Injectable` decorator is what makes a class a `provider`.
```
[ ] Yes
[x] No
```

docs(components): Remove misleading line about Injectables

---

content/fundamentals/unit-testing.md

Demonstrate using Fastify's .inject method, instead of supertest, which only works for Express.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
e2e test code in the docs does not work when using fastify
the correct way to write e2e tests for fastify is documented
```
[ ] Yes
[x] No
```

docs(testing): fix wrong documentation for fastify e2e tests

---

content/recipes/prisma.md

`PostModel` should reference to `author` instead of `User`.
```js
TS2345: Argument of type '{ title: string; content: string; User: { connect: { email: string; }; }; }' is not assignable to parameter of type 'PostCreateInput'.   Object literal may only specify known properties, and 'User' does not exist in type 'PostCreateInput'.
```
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```

`PostModel` should reference to `author` instead of `User`

---

content/techniques/sql.md

In the case of forRoot connection, the'name' item in forRoot becomes the connection name of nestjs.
However, in the case of forRootAsync connection, apart from the'name' item that exists inside forRoot, the'name' item of forRootAsync exists.
You must specify the conneciton name in the'name' item of forRootAsync to use the code described in the document.
Here is my example:
```typescript
@Module({
imports: [
TypeOrmModule.forRootAsync({
imports: [MyConfigModule],
useExisting: ASPDBConfig,
name: 'ASP',
}),
TypeOrmModule.forRootAsync({
imports: [MyConfigModule],
useExisting: InCompanyDBConfig,
name: 'InCompany',
}),
ApplicationModule,
],
providers: [],
})
export class EntryModule {}
@Module({
imports: [TypeOrmModule.forFeature([Document, Unit], 'ASP')],
providers: [NTSSendService], …
```

docs(sql): adding hint of injection token with typeorm async Connection options

---

content/techniques/configuration.md

docs: improved section about using a config.yaml
Regarding the  [documentation about configuration](https://docs.nestjs.com/techniques/configuration#custom-configuration-files):
An instruction is given about how to use a YAML file as config file. However, the section about configuring the 'nest-cli.json' to include the config.yaml in the dist is wrong/to vague.
I included a more clear explanation of how to make the 'nest-cli.json' work (tribute to jmcdo29 to figuring it out)
```
[ ] Bugfix
[ ] Feature
[X] Docs
```
Issue …

docs: improved section about using a config.yaml

---

content/openapi/introduction.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
When using `addBearerAuth`, 
`persistAuthorization` option is so important when using `addBearerAuth`. On each refresh, it removes authorization keys. It's better to have this option (and others) in documentations.
```
[ ] Yes
[x] No
```

docs(openapi): add more docs for swagger setup method

---

content/recipes/hot-reload.md
package-lock.json
package.json

Supercedes https://github.com/nestjs/docs.nestjs.com/pull/1568
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/1554, https://github.com/nestjs/nest/issues/5928, https://github.com/nestjs/nest-cli/pull/1000
Docs are now up to date for Yarn 2 and Webpack 5.
Until https://github.com/nestjs/nest-cli/pull/1000 is merged, you'll need to do `webpack@5.9.0` instead of `webpack`. See that PR for repro steps following these docs
```
[ ] Yes
[x] No
```

Update hot reload docs for Webpack 5 and Yarn 2

---

content/techniques/streaming-files.md
src/app/homepage/menu/menu.component.ts
src/app/homepage/pages/cli/scripts/scripts.component.html
src/app/homepage/pages/microservices/custom-transport/custom-transport.component.html
src/app/homepage/pages/techniques/streaming-files/streaming-files.component.ts
src/app/homepage/pages/techniques/techniques.module.ts

```
[ ] Bugfix
[ ] Feature
[X] Docs
```
There's no documentation for a new feature being implemented ([nest#5278](https://github.com/nestjs/nest/pull/5278))
There's now docs showing how files can be streamed back without interfering with the interceptor's post-controller logic.
```
[ ] Yes
[X] No
```
Looks like some of the compiled output from degni got modified. Let me know if you want me to remove that or keep it. Looks like it shouldn't modify the final output to the webpage

docs(streams): adds docs for streaming files with `StreamableFiles`

---

content/security/rate-limiting.md

- [ X ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ X ] Bugfix
[ ] Feature
[ ] Docs
```
Small bugs that I found at the graphql rate-limiting code snippet.
'gql' should be 'gqlCtx'  and 'req, ctx.req,' shoud be ' req: ctx.req' 
Replace 'gql' with 'gqlCtx' and 'req, ctx.req' with 'req: ctx.req'
```
[ ] Yes
[ X ] No
```

docs(rate-limiting): fix graphql code snippet bugs

---

src/app/homepage/homepage.component.scss

small fix, did not notice the line separating the content
before
after fix

minor fix carbon banner

---

content/microservices/grpc.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
```
[ ] Yes
[x] No
```
This PR, updated as it provides a warning about the `subscribe` method, saying it is deprecated.

docs(grpc): improvement

---

content/recipes/prisma.md

Prisma Migrate entered General Availability as of version 2.19.0. 
That means you no longer need to add `--preview-feature` flag when running `prisma migrate` commands.
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
```
[ ] Yes
[x] No
```
- [Prisma 2.19.0 Release](https://github.com/prisma/prisma/releases/tag/2.19.0)
- [Blog post about Prisma Migrate enters GA](https://www.prisma.io/blog/prisma-migrate-ga-b5eno5g08d0b)

docs(prisma): Prisma Migrate entered GA and preview-feature flag is no longer needed

---

content/techniques/validation.md

```
[ ] Bugfix
[ ] Feature
[X] Docs
```
Docs don't tell users that an `import type` on a DTO will result in ValidationPipe not running, since type only imports are erased at compilation time and thus can't be introspected.
Add a hint to the docs, warning users to avoid `import type` for DTOs. Developers should add tests to their controllers verifying input validation anyways, so it's OK (although not ideal) to keep the current behavior and just add a docs hint.
```
[ ] Yes
[X] No
```

docs: Add ValidationPipe hint on not using `import type` for DTOs

---

content/techniques/sql.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
By now, the default value of synchronize option is `true`, references:
https://github.com/nestjs/sequelize/blob/master/lib/interfaces/sequelize-options.interface.ts#L26
https://github.com/nestjs/sequelize/blob/master/lib/sequelize-core.module.ts#L151
Sync with
```
[ ] Yes
[x] No
```

docs(sequelize): fix synchronize default value

---

content/techniques/file-upload.md

the type is `Array<Express.Multer.File>`, verified on a local repo
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
N/A
N/A
```
[ ] Yes
[x] No
```
Just found the docs were out of date w.r.t. file uploads, so helping out here

Update to docs w.r.t. @UploadedFiles()

---

content/microservices/basics.md

```
[x] Docs
```
The link is invalid and redirects the user to the docs homepage.
Directs the user to the `Fundamentals > Custom providers` page.
```
[ ] Yes
[x] No
```

docs(microservices): fixed custom provider markdown link

---

content/application-context.md

Since the doc is about *Standalone applications*, it's more accurate to use `createApplicationContext()` method.
[x] Docs
[x] No

Improper example codes.

---

content/microservices/exception-filters.md

Update the warning for using global exception filters in hybrid apps. They do actually work, if you `inheritAppConfig: true` when connecting the microservice.
```
[x] Docs
```
```
[ ] Yes
[x] No
```

fix(microservices): update global exception filter warning for hybrid app

---

content/techniques/caching.md

I was a bit confused when I first read these docs what units the cache TTL is in. I expected milliseconds, and had to read the cache-manager docs to confirm.
Reference: https://www.npmjs.com/package/cache-manager
```
[ ] Bugfix
[ ] Feature
[ x] Docs
```
```
[ ] Yes
[x ] No
```

Make it clear that the cache TTL is in seconds.

---

content/components.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
As provider is decorated with @Injectable() decorator, it's more important that provider can be injected, not that it can inject other dependencies (because, i.e. controllers can do it as well).
I propose this small change, which can make this part of providers description more clear.
`The main idea of a provider is that it can inject dependencies` to `The main idea of a provider is that it can be injected as  dependency`
```
[ ] Yes
[X] No
```

docs(providers): changes part about main idea of provider.

---

content/security/authorization.md

change authorId type from string to number
- [ x ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[x] Docs
```
Casl factory sample code doesn't work due ti Author.authorId and Iser.id type mismatch
Casl factory sample code works after change
```
[ ] Yes
[x] No
```

docs(authorization): change authorId type from string to number

---

content/techniques/caching.md

```
[ ] Bugfix
[ ] Feature
[x] Docs
```
The documentation says to set the `ttl` to `null` should disable the cache. The TS types do not allow it to be null, and I found that actually setting it to null does not disable the cache expiration.
Setting the ttl to `0` works to disable the cache expiration.
https://github.com/BryanDonovan/node-cache-manager/issues/107
https://github.com/BryanDonovan/node-cache-manager/issues/147
```
[ ] Yes
[x] No
```

docs(caching): update docs for disabling cache expiration

---

content/techniques/sql.md

Add documentation for the new connectionFactory feature in @nestjs/typeorm.
Issue Number: [@nestjs/typeorm#927](https://github.com/nestjs/typeorm/issues/927)
Changes were made to allow `keepConnectionAlive` to behave better in a serverless environment (no breaking changes) and to allow a custom `connectionFactory` to be used. (PR in that repository coming up after this PR is created.)

docs(@nestjs/typeorm): add documentation for connectionFactory feature

---

content/graphql/quick-start.md

Nest 8 is not intended to run with apollo-server-express@3.x.x but this open version command will install apollo-server-express@3 and break the startup [1]
as @kamilmysliwiec suggested it should use version 2
[1] https://github.com/nestjs/graphql/pull/1627

Update apollo-server-express version to nest8

---

content/techniques/validation.md

In order to use the built-in `ValidationPipe` we must install `class-validator class-transformer`
otherwise, we will get errors like:
`ERROR [PackageLoader] The "class-validator" package is missing. Please, make sure to install this library ($ npm install class-validator) to take advantage of ValidationPipe.`
therefore, we should add the following to the docs:
`npm install --save class-validator class-transformer`
`nest new test-app`
`nest g res cats`
(choose rest, choose crud)
add to main.ts:
`app.useGlobalPipes(new ValidationPipe());`
`nest start --watch`
we get:
`ERROR [PackageLoader] The "class-validator" package is missing.`
`npm install --save class-validator …

Missing npm install command for ValidationPipe

---

content/openapi/cli-plugin.md

Add instruction on how to clear the jest cache folder in case changes are not picked up
fixes: https://github.com/nestjs/swagger/issues/1326

docs(@nestjs/swagger): jest troubleshooting info

---

content/techniques/server-sent-events.md

The documentation had no reference to the MessageEvent interface being in the `@nestjs/common` package.
Also, fixed a typo where the word "and" was included in the monospace block alongside `map`.
Typo in the SSE section of the documentation, where the word "and" was contained in the monospace block next to the `map` function from RxJS, as well as a failure to mention that the MessageEvent interface is contained in the `@nestjs/common` package.
The hint box now has the proper reference to the interface being in the package, typo is also fixed.

docs(sse): Referenced the MessageEvent interface and fixed a typo

---

content/graphql/resolvers-map.md

The current generic Paginated GraphQL type is typed as `any`.
The updated generic Paginated GraphQL type is fully typed, check this CodeSandbox for an example, note how TypeScript knows the edges and nodes are of the `PostModel` type.
https://codesandbox.io/s/modest-brook-pl3fq?file=/src/graphql/post.ts

docs(graphql): updates generic Paginated GraphQL type to be fully typed instead of typed as any

---

content/cli/usages.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: documentation/feature
```
Docs only shows npm and yarn.
Docs will show pnpm as well.
```
[ ] Yes
[x] No
```
Related to [https://github.com/nestjs/nest-cli/pull/788](https://github.com/nestjs/nest-cli/pull/788). Obviously, this should be accepted and released only once the related nest-cli PR is accepted and released.

docs(cli): added pnpm to cli usages page

---

content/openapi/cli-plugin.md
src/app/homepage/pages/microservices/custom-transport/custom-transport.component.html

There are no information relating to `dtoKeyOfComment` and `controllerKeyOfComment` CLI plugin options. 
This PR adds the information for `dtoKeyOfComment` and `controllerKeyOfComment`
Ref https://github.com/nestjs/swagger/issues/1515

docs(openapi): add docs about missing cli plugin options

---

content/graphql/directives.md

Issue Number: #2021
Adds note to GraphQL Directives documentation to the effect that `@graphql-tools/utils@^8` is not compatible.

docs(graphql): SchemaDirectiveVisitor requires @graphql-tools/utils@^7

---

content/graphql/scalars.md

`GraphQLTimestamp` is an integer in the current version implementation, not a string. The doc should reflect the current version. The wording is taken from the scalar's description property.
The range of values is limited by [`Number.MIN_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER) (`-(2^53 - 1)`) and [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (`2^53 - 1`).
Thus the current implementation has a bigger range than a 32-bit integer.
The current doc version states that `GraphQLTimestamp` is a string.
The new doc version …

Update scalars.md: GraphQLTimestamp is integer

---

content/recipes/prisma.md

Prisma 3 no longer exports ```Prisma.UserOrderByInput```, but rather ```Prisma.UserOrderByWithRelationInput```.

Update prisma.md for Prisma 3

---

content/faq/serverless.md

Following the guide https://docs.nestjs.com/faq/serverless#example-integration with commonjs2
Without ...options.output, the nestjs cli commands break
Errors are thrown with the NestJS cli
```
Error: Cannot find module '/Users/user/Desktop/monorepo/dist/apps/app/main'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
at Function.Module._load (internal/modules/cjs/loader.js:730:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
at internal/main/run_main_module.js:17:47
```
The NestJS cli works with the custom config

docs(serverless): fix custom webpack example with commonjs2 from crashing cli

---

content/recipes/router-module.md

Currently, document `/recipes/router-module` doesn't have URL to `Versioning` page.
I added missing URL to `Versioning` Docs page.

docs(recipes/router-module): add missing 'versioning' hyperlink

---

content/websockets/gateways.md

It adds the way the user can import the file in case of a manual creation, so that it doesn't get lost in the process.
> ## PR Checklist
> Please check if your PR fulfills the following requirements:
> 
> * [x]  The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
> 
> ## PR Type
> What kind of change does this PR introduce?
> 
> * [ ]  Bugfix
> * [ ]  Feature
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Refactoring (no functional changes, no api changes)
> * [ ]  Build related changes
> * [x]  Docs
> * [ ]  Other... Please describe:
> 
> ## What is the current behavior?
> Issue Number: N/A
> 
> ## What is the new behavior?
> Added warning for Http Health Indicator
> 
> ## Does this PR introduce a breaking …

docs(gateway): add gateway file import to module

---

content/recipes/sql-typeorm.md

The [SQL (TypeORM)](https://docs.nestjs.com/recipes/sql-typeorm#sql-typeorm) documentation requires user to install `mysql`.
In this manner, users may get errors during DB configuration, because of inproper dependency installation.
Now the documentation requires `mysql2` instead of `mysql` 
[Database](https://docs.nestjs.com/techniques/database) documentation correctly requires `mysql2`.
Therefore, outdated **SQL (TypeORM)** section sould be updated.

docs(sql-typeorm) need to require mysql2 instead of mysql

---

content/recipes/prisma.md

The definition of `bootstrap` needs to be changed and then called normally.

docs(prisma) : Correct the sample code for Issues with enableShutdownHooks

---

content/websockets/gateways.md

The gateways documentation has a broken link to socket options [socket options](https://socket.io/docs/server-api/)
This PR replaces the broken link with the one at [Server.options](https://socket.io/docs/v4/server-options/)

docs: fix broken socket options link in gateway docs

---

content/modules.md

Isn't clear that we can use the `provide` value of providers on `exports` list of `@Module()`. We can figure out this by looking on types definitions tho 
Also, I changed the HTML table to markdown

docs(modules): clarify about `exports` array of `@Module()` options

---

content/techniques/configuration.md

No documentation regarding the feature that will be introduced in `@nestjs/config` after merging https://github.com/nestjs/config/pull/676
<details>
<summary>screenshots</summary>
</details>

docs(): add new feature of ConfigService on configuration page

---

content/techniques/configuration.md

Sometimes people complains about typescript errors on `@nestjs/config` v1 just because they have no clue that this package requires typescript version 4.1 or higher

docs: add notice regarding the TS version of `@nestjs/config`

---

content/techniques/caching.md

No documentation regarding the feature added in https://github.com/nestjs/nest/pull/8592
I didn't put any hint on how users can find the valid store configuration type because I think there's no standard way besides looking into store's source like I've done for `cache-manager-redis-store` (looking at `@types/cache-manager-redis-store`'s source)

docs: cover `CacheModule#register` (and so on) optional type argument

---

content/techniques/logger.md

In the code example, we use `super.methodName.apply(this, arguments)` to call a parent class method from a child class.
The `.apply()` is unnecessary when we use `super`. So, we can just call `super.methodName(...arguments)` in the child class.

docs(logger.md): remove `.apply()` in the code example

---

content/fundamentals/unit-testing.md

Otherwise you'd get:
> Jest did not exit one second after the test run has completed.
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
Generated file (`app.e2e-spec.ts`) doesn't have the `app.close()` call. 
Has it been fixed in newer versions?
chill, just a docs update

docs(unit-testing): call app.close() afterEach in Fastify e2e test example

---

content/microservices/mqtt.md
content/microservices/nats.md

It's not a good idea, connections are closed on OnApplicationShutdown so this would leave a lot of lingering connections.

docs(msvc): remove hint to request-scope msvc client

---

content/recipes/prisma.md

The current link targets the old repo which states in its [readme](https://github.com/fivethree-team/nestjs-prisma-starter#instructions): "This repository has moved to notiz-dev/nestjs-prisma-starter!". The PR links to the currently maintained repo.
Treat it as a typo that is fixed.
- [-] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
-> I edited the typo on github website and was not allowed to choose the correct branch name there. Sry for not exactly following your standards
Link to old outdated repo
Link to current repo

docs ->prisma fix deprecated link

---

content/graphql/subscriptions.md

When using subscriptions with graphql-ws package, passing additional context values are different from subscription-transport-ws package
When using graphql-ws, the current document on graphql  subscriptions' context passing seems to suggest that your additional  context values should directly return from `onConnect` callback and access it from the `context` callback.  but in fact in graphql-ws package, returning an object from `onConnect` callback is an optional payload that will send back to client via `ConnectionAck` message.
When using graphql-ws package, the correct way to pass additional context value is through `extra` field.

docs(graphql): graphql-ws context value example

---

package.json

Building docs with production env with `--prod` flag in `ng build` command
Using the `--configuration production` flag in `ng build` command.
This is done because `--prod` flag is deprecated:
> Deprecated: Use --configuration production instead.
>
> Shorthand for "--configuration=production". Set the build configuration to the production target. By default, the production target is set up in the workspace configuration such that all builds make use of bundling, limited tree-shaking, and also limited dead code elimination.
>
> From [Angular Docs - `ng build` options](https://angular.io/cli/build#options)

fix(build): replace --prod (deprecated) with --configuration production in npm script

---

content/techniques/sql.md

I didn't find any mention on docs regarding this [custom repository](https://docs.nestjs.com/techniques/database#custom-repository) limitation: we can't use NestJS's DI on them.
I just bring [this comment from SO](https://stackoverflow.com/a/65227341/5290447).

docs: clarify on custom repository limitation in sql.md

---

content/faq/serverless.md

I think the second line of serverless npm packages should be installed in dev env.
Fix for npm commands

npm command fix

---

content/security/authentication.md

slight error in the payload.
it returns a "message" field and not an "error" field
Curl response payload has incorrect key of "error".
Fix the curl response payload to correct key of "message"

docs(authentication): fix curl response payload

---

content/security/rate-limiting.md

There is a typo in the XFF header
```diff
- X-Forward-For
+ X-Forwarded-For
```
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

docs(security): typo in X-Forwarded-For header

---

content/techniques/performance.md

I've searched the entire project, and hopefully, this is going to be the last broken Fastify link 😄
Thanks for the patience!

docs(performance): broken fastify guide link

---

content/techniques/caching.md

The latest `redis` NPM package does not have the `ClientOpts` type.
I've replaced the `ClientOpts` with `RedisClientOptions` type which is exported here:
https://github.com/redis/node-redis/blob/46b831c92282d16d5b224effa20cf8dc6002fd8c/packages/client/lib/client/index.ts#L18

docs(caching): fixed invalid redis typings

---

content/faq/serverless.md

Updates service property to be a string representing the service's name instead of an object;
Updates runtime to the latest LTS version supported by AWS λ
The current example for `serverless.yml` is outdated. 
The service property as it is now throws the following error when `sls offline` is called:
```sh
Error:
Object notation for "service" property is not supported. Set "service" property directly with service name.
```
And since February 2021, [AWS λ is supporting Node.js 14.x runtime](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/).
Accordingly to the [Serverless Deprecations](https://www.serverless.com/framework/docs/depreca …

docs(faq/serverless): update `serverless.yml` example

---

content/graphql/federation.md

@nestjs/mercurius is missing
`@nestjs/mercurius` is missing

Added Missing Package

---

content/fundamentals/unit-testing.md

I currenly have Jest  v27.2.5 and it does not have `mockResolveValue`, but has the same functionality method `mockResolvedValue`.
- [ x] Docs
Code in documentation has an error in method, i guess, because as of Jest 27.2.5 does not have `mockResolveValue` method
The new behavior does not through an error when pasting the code following the tutorial
- [ x] No

Updated jest function

---

content/recipes/mikroorm.md

The serialization technique (`ClassSerializerInterceptor`) in the docs is misleading for MikroORM users, since this ORM wraps all entity relations in reference objects, making class-transformer blind regarding wrapped entities. So it's fairly easy for a newcomer to get confused (well, I was 😅 ).
Add a section in the MikroORM recipe to warn about this, and suggest using the MikroORM serialization API which provide a way to hide, expose and transform properties too.

docs(mikroorm): add a caveat about serialization

---

content/application-context.md

The following grammatical adjustments are related to `Getting started section`, found in the `standalone-applications` [page](https://docs.nestjs.com/standalone-applications);
1. Replace the word `modules` with `module's `
2. Replace the word `from` with `to`

docs: adjust grammatical error

---

content/openapi/decorators.md

`@nestjs/swagger` version [5.0.0](https://github.com/nestjs/swagger/releases/tag/5.0.0) added a new decorator to exclude controllers.
But the documentation doesn't have that on the list.
I've added it to the list.
I also had to format the markdown table cause the decorator had an extra character!
Sorry if it's a bit confusing while reviewing 😄 (it's on the line 20)

docs(swagger): added missing ApiExcludeController decorator

---

content/fundamentals/dynamic-modules.md

Currently we don't have guidelines or documentation around `forRoot`, `forFeature` and `register`.
I've added in a segment about forRoot, forFeature, and register. I've seen
this question pop up several times on Discord, in GitHub Issues, and in
StackOverflow. I figured it was time for us to try and codify a reason
for the naming. Of course, there's no hard rule here, but the guideline
is suggested and it could become community standard which would be a big
win for the mental load of creating and using new modules.

feat: mention the different registration methods

---

content/techniques/compression.md

Fastify plugin registration happens asynchronously and should be awaited.
Inspired by #2266 😄

docs(compression): fastify plugin registration should be awaited

---

content/recipes/terminus.md

The code block for writing the health controller exists, but there isn't a sample regarding its module.
I've added the code block.

docs(terminus): replaced AppModule with the HealthModule

---

src/styles.scss

A incorrect css property was causing a warning when running the documentation

refactor(styles): rename incorrect css property

---

content/fundamentals/lazy-loading-modules.md

I tried to use all the lifecycle hooks methods in a module (and its service) that was lazy loaded but none of them was called. But I didn't find any mention on the docs site regarding that behavior.
<details><summary>demo</summary>
```ts
// app.service.ts
@Injectable()
export class AppService {
constructor(private readonly lazyModuleLoader: LazyModuleLoader) {}
async getHello(): Promise<string> {
const { LazyModule } = await import('./lazy.module');
const moduleRef = await this.lazyModuleLoader.load(() => LazyModule);
const lazyService = moduleRef.get(LazyService);
return lazyService.getHello();
}
}
```
```ts
// app.module.ts
@Module({
imports: [],
controllers: [AppController], …
```

Clarify that lifecycle doesn't apply to lazy loaded modules

---

content/techniques/mongo.md

docs: Incomplete MongoDB documentation
Missing 'export' keyword from **MongooseConfigService class** on https://docs.nestjs.com/techniques/mongodb

Missing MongoDB documentation 'export' keyword

---

content/graphql/subscriptions.md

The `context` object isn't part of the `subscriptions` object.

docs(graphql): context not in subscription object

---

content/graphql/complexity.md

The example imports a module from the wrong package.
The docs example code is updated to match the working example in https://github.com/nestjs/nest/tree/master/sample/23-graphql-code-first
The existing example will error with the following message:
```
❯ npm start
> nest-typescript-starter@1.0.0 start
> nest start
src/common/plugins/complexity.plugin.ts:1:29 - error TS2305: Module '"@nestjs/graphql"' has no exported member 'Plugin'.
1 import { GraphQLSchemaHost, Plugin } from "@nestjs/graphql";
~~~~~~
Found 1 error(s).
```
This same change was made in the samples a few months ago: https://github.com/nestjs/nest/commit/d8ba5d16e6e9abcc3c7e1dbe3951bbeee6d0044b#diff-5b15 …

docs(graphql): Fix incorrect import

---

content/first-steps.md

no mention on the `abortOnError` flag. I didn't realise that this option exists and took me some time to understand why `NestFactory.create` was exiting the app instead of rejecting the promise
clarify that the process will abort on error by default

docs: add hint on abort on error behavior

---

content/recipes/sql-typeorm.md

Use new syntax to create database connection in typeorm introduced in [0.3.0](https://typeorm.io/changelog#030httpsgithubcomtypeormtypeormpull8616-2022-03-17)
Syntax used is deprecated since typeorm version 0.3.0.
Uses new syntax.

docs(typeorm): Adapt to new typorm syntax

---

content/microservices/basics.md

I don't see any good reason to transform the returned observable to promise as all the other examples of `this.client.send` are using Observables, so I just remove the deprecated `toPromise` call

docs(microservices): drop deprecated `toPromise` from snippets

---

content/techniques/caching.md

The documentation takes into account that cache-manager-redis-store supports redis v4, thus leading the reader to believe that they are setting the host and port when this is not read.
Issue Number: #2324
It informs the actual parameters that are taken into account and explains to the reader why he should download redis major 3 version.

docs(caching): update redis custom host and port

---

content/graphql/quick-start.md
package-lock.json

If you follow the docs you will install mercurius version 10 which is only compatible with fastify version 4, and @nestjs/platform-fastify uses version 3.
It installs version 9.

docs(graphql): fix mercurius version at 9

---

content/fundamentals/unit-testing.md

Added type import for MockFunctionMetadata.
Example with auto-mocking has no import for necessary types.
https://docs.nestjs.com/fundamentals/testing#auto-mocking
Copy-pasting of examples should work without any code changes.

docs(tests): added missing import for auto-mocking

---

content/security/csrf.md

Fastify plugin registration happens asynchronously and should be `await`-ed.
Inspired by #2266 😄

docs(security): fastify-csrf plugin registration should be awaited

---

content/guards.md

Guides people incorrectly that Guards execute after `each` registered middleware.
Changed that from `each` to `all`.

docs(guards): resolve confusion in the hint

---

content/fundamentals/dynamic-modules.md
content/modules.md

docs(): add configurable module builder instructions

---

content/fundamentals/provider-scopes.md

docs(): durable providers feature

---

content/techniques/file-upload.md

This Docs change is related to this [PR](https://github.com/nestjs/nest/pull/9718) which adds FileValidators

docs(file-upload): add file validators section

---

content/faq/errors.md

Fix the typo from NetJS to NestJS and use a gramatically correct preposition.
The docs in the [FAQ (common errors page)](https://docs.nestjs.com/faq/common-errors) have the following line: 
> self-injections are not allowed on NetJS.
The docs in the [FAQ (common errors page)](https://docs.nestjs.com/faq/common-errors) have the following line: 
> self-injections are not allowed in NestJS.

docs(faq/common-errors): fix typo in the `Common errors` block

---

content/pipes.md
content/techniques/configuration.md
content/techniques/serialization.md

Currently referencing `class-transformer` methods named with `class`. They have since deprecated these methods in favor of more accurately named `instance` methods. Current example: `plainToClass`.
Post fix example: `plainToInstance`
https://github.com/typestack/class-transformer/issues/235

docs(fix): Updates references to deprecated class-transformer methods

---

content/recipes/hot-reload.md

A new version of run-script-webpack-plugin was released, which contains an autoRestart flag, which should be set to false for HMR
With the latest version of run-script-webpack-plugin, it was completely restarting the server on every single code change, completely negating HMR
HMR actually works

docs: add autoRestart: false to RunScriptWebpackPlugin

---

content/cli/usages.md

Missing docs for [#1699](https://github.com/nestjs/nest-cli/pull/1699) and [#1668](https://github.com/nestjs/nest-cli/pull/1668) 
Docs has been updated

Docs v9.0.0 changes

---

content/techniques/mvc.md

https://www.npmjs.com/package/point-of-view says "point-of-view@6.3.0 has been deprecated. Please use @fastify/view@7.0.0 instead."
When installing point-of-view a deprecation warning is shown.
No deprecation warning.

docs(mvc): point-of-view has been deprecated

---

content/cli/usages.md
content/first-steps.md
content/introduction.md
content/migration.md

- people complaining about not being able to use `nest update` anymore in v9
- issue: closes #2368
- mention in the migration guide that the command `update` was removed from `@nestjs/cli@9`
- add docs on `--strict` flag of `nest new` command

 docs: add nestjs cli change on migration guide & docs on `--strict`

---

content/recipes/hot-reload.md

The options `keepConnectionAlive` in TypeORM is deprecated (see screenshot)
Link package `@nestjs/typeorm`: https://github.com/nestjs/typeorm/blob/master/lib/interfaces/typeorm-options.interface.ts#L31

docs(recipes): update hot-reload.md

---

content/fundamentals/dependency-injection.md

the constant in the documentation is named as `connectionFactory`. but the object which is provided is a provider not a factory. the factory is in the provider after the `useFactory` key
renamed constant name to `connectionProvider`

Update connectionFactory constant to connectionProvider

---

content/fundamentals/dynamic-modules.md

Fixed `reuturns` to `returns` on line 401
Typo/wrong spelling of `reuturns`
Correct spelling `returns`

Fixed spelling in dynamic-module.md

---

content/fundamentals/provider-scopes.md

Fixed omission of `to` on line 110
Omitted word `to` on line 110
Omitted word `to` is now present

Fixed omission in provider-scopes.md

---

content/recipes/nest-commander.md

Docs are outdated, don't work with `nest-commander` 3+.
Changed `CommandRunner` from `interface` to `abstract class`
See commit [d6ebe0e](https://github.com/jmcdo29/nest-commander/commit/d6ebe0ede2e0e366d0669c80f2d376be9e8345e3) or [Usage](https://nest-commander.jaymcdoniel.dev/docs/features/commander/)

docs(nest-commander): Update outdated docs to meet latest

---

content/techniques/file-upload.md

Typo in header, I believe `Multiple files` should be `Multiple fields`.
Multiple files topic is already handled before this section.
- Header now displays `Multiple fields`.
Header change so existing hyperlinks might break.
Referees should update their references.

docs(file-upload): Fix typo Multiple Fields.

---

content/techniques/caching.md

The `node-cache-manager` repo was moved to a new parent account on GitHub.

docs(caching): fix github link to point to the moved repo location

---

content/techniques/http-module.md

I'm submitting this PR on behalf of `hacktoberfest`. (Could the maintainers add the Hacktoberfest label at this repo?)
The docs explain how to use the HttpModule, but it lacks examples of using HttpService with rxjs features. So with this PR I propose to add an full example on how to proper use HttpService, with a plus of error handling.
I'm proposing this because the stack overflow/google answers weren't good enough and I was only able to finish my work after I asked for help in the discord channel. 
The docs will have a full example on how to use HttpService

Add http-module use example

---

content/techniques/caching.md

An error was encountered while following the example.
- VScode
- typeorm 0.3.0
- "cache-manager": "^5.1.1",
- "cache-manager-ioredis": "^2.1.0",
- "cache-manager-redis-store": "^3.0.1",
error: Argument of type '{ ttl: number; }' is not assignable to parameter of type 'number'.ts(2345) 
solution: vscode suggestion
I'm a Nest, Ts beginner and the bug is giving me a hard time. 🫠

docs(caching): fix cacheManager.set, get property

---

content/techniques/file-upload.md

add a warning for FileTypeValidator to be clear about its unsuitability for safer file type validation.
Issue Number: #2497

docs: add a warning for FileTypeValidator

---

content/techniques/caching.md

My fault for being a bit sloppy on #2493 and missing the other outdated repo links for `node-cache-manager`. Apologies for not getting this in the original PR.

docs(caching): another fix to point cache-manager to new repo

---

content/techniques/sql.md

`typeorm@0.3` [no longer](https://github.com/typeorm/typeorm/releases/tag/0.3.0) has `@TransactionRepository()`, `@TransactionManager()`, `@Transaction()` decorators, so there's no reason to mention them here
I've also renamed the _transactions_ sections because before we got the same name in the summary list, which I found confusing

docs(sql): drop mention on typeorm transaction decorators

---

content/techniques/mongo.md

Currently, techniques/mongodb doc uses intersection type for defining the mongoose document interface.
```ts
import { Document } from 'mongoose';
export type CatDocument = Cat & Document;
```
it was okay before mongoose@6.3.2 but after that, they replaced the use of `this` with generics(`T`) in many `Document` methods so it infers incorrectly now.
```ts
// before
toObject(options?: ToObjectOptions): LeanDocument<this>;
toObject<T = DocType>(options?: ToObjectOptions): T;
// latest
toObject<T = LeanDocument<DocType>>(options?: ToObjectOptions): Require_id<T>;
// from: https://github.com/Automattic/mongoose/commit/659436de47d55aaa0a984b8f4cc99232c5ca8a16
```
```ts
type CatDocument = Cat …
```

docs(mongo): change the way to define the mongoose document interface

---

content/faq/errors.md

Merge this after https://github.com/nestjs/nest/pull/10558

docs(faq): update unknown dependency error msg

---

content/techniques/sql.md

If you only provide `name` property in `forRootAsync` options, and not in returned options from `useFactory`, module `onApplicationShutdown` will throw error like
```
Nest could not find DataSource element (this provider does not exist in the current context)
```
This is because the `getDataSourceToken` call uses the options returned from `useFactory`, not the `forRootAsync` definition.
Issue Number: related to #2177
No errors on application shutdown
Unlikely to be an issue most applications run into, but we use in-process integration tests that create and shutdown an app instance for each test suite and this was failing.

docs: clarify solution in #2177

---

content/faq/errors.md

add the following solution for `"Cannot resolve dependency" error`:
For **pnpm** Workspaces, set `@nestjs/core` as a peerDependencies in your other module and `"dependenciesMeta": {"other-package-name": {"injected": true}}` in the app package.json where the module is imported. see: [dependenciesmetainjected](https://pnpm.io/package_json#dependenciesmetainjected)
Only provide solution for yarn
Now provide a solution for pnpm <3
Hum I'm not really sure if I'm doing the whole PR process correctly if I'm missing something I will gladly correct it.

docs(faq): add pnpm solution for `"Cannot resolve dependency" error`

---

content/pipes.md

The current documentation for Pipes's "validation" use case reads
> **validation**: evaluate input data and if valid, simply pass it through unchanged; otherwise, throw an exception when the data is incorrect
"when the data is correct" is redundant, as it's already been implied with "otherwise."
The redundancy is removed.

docs(pipes): remove redundant wordings

---

content/techniques/caching.md

Proposal: 
- Added warning to point out that the `CacheModule` works with both `v4` and `v5` versions of the `cache-manager`
- Added warning that mentions that `cache-manager` v5 uses milliseconds but v4 uses seconds and since documents were written for v4 at that time.
see screenshot here: 
If you use a version of NestJS less than v9.2 and install `cache-manager` v5 it gives the following error:
See also Discussion Discord (https://discord.com/channels/520622812742811698/1064176338996580424)

docs(cache): added warning for cache manager compatibility

---

content/microservices/grpc.md

https://developers.google.com/protocol-buffers => https://protobuf.dev
The link to protocol buffers is <https://developers.google.com/protocol-buffers>, which is deprecated.
Change link to <https://protobuf.dev>

docs(grpc): The link to protocol buffers is deprecated

---

content/security/authentication.md

Update de secret value used as example in order to avoid programmers to use it on production code
I've found a few companies using the example code without modifying the secret value, regardless the warning on the page.
I think that it is a honest mistake, because the current value seems like a enum value.
The goal of this modification is to use a more semantic value, informing to the the programmer that the secret value must be changed and kept safe.

docs(authentitcation): update the example secret

---

content/recipes/cqrs.md

Isn't clear where the `@Saga()` decorator came from

docs(cqrs): mention that `@Saga()` came from `@nestjs/sqrs`

---

content/techniques/sql.md

id converted to a number which is at findOne method because it shows error like 
`(property) id?: number | FindOperator<number>
Type 'string' is not assignable to type 'number | FindOperator<number>'.ts(2322)`
also, id is the number at the given example
https://github.com/nestjs/nest/blob/master/sample/05-sql-typeorm/src/users/users.service.ts#L26

docs(sql.md) update type of parameter of findOne method

---

content/security/rate-limiting.md

I have update WsThrottlerGuard following new methods: https://github.com/nestjs/throttler#working-with-websockets
I have update `WsThrottlerGuard ` following this [pull](https://github.com/nestjs/throttler/pull/1304)

fix: Update rate-limit websocket docs

---

content/faq/errors.md

I opened [this](https://github.com/nestjs/nest/issues/11038) issue a few hours ago which describes the problem I was having with running NestJS in watch mode.
I was asked by @micalevisk to add information about this problem to the "Common errors" page, and this is it.

docs(common errors): added new section

---

content/graphql/quick-start.md

Pointing to the Yoga integration next to the other integrations.
Just in time after it was updated to the latest NestJS 9 and Yoga v3! 
https://the-guild.dev/blog/graphql-yoga-nestjs-v9

docs(integrations): Linking the NestJS Yoga integration to GraphQL docs

---

content/techniques/queues.md

The code snippet in the [Event Listeners](https://docs.nestjs.com/techniques/queues#event-listeners) of Queues was missing an import for the `OnQueueActive` decorator.
Adds the missing import.
N/A

FIX: Add missing import for OnQueueActive in Snippet

---

content/microservices/kafka.md

When I was getting some error logs trying connect to the kafka server, I saw that the library added a "-server" or "-client" suffix to the value of the clientId property.
Well, in the documentation there is a very generic "HINT" on how to change this...
"Kafka client and consumer naming conventions can be customized by extending ClientKafka and KafkaServer in your own custom provider and overriding the constructor."
But looking at node_modules i found a property called "posfixId" in the file responsible for initializing the connection to the kafka server, which appeared to be responsible for prefixing of clientId value, so I put this setting in my configuration object in main.ts with an empty value, like "".
And it worked fine (the suffix was removed), so i think it would be nice to make …

docs(Kafka): adding postfixId property in kafka client options

---

content/techniques/sql.md

In the docs there is a section that says that to do Sequelize multiple connections, we must use `@InjectDataSource` to inject the named connection. However, the module `@nestjs/sequelize` don't has this import. Actually, `@InjectDataSource` is an annotations for TypeORM.
https://docs.nestjs.com/techniques/database#multiple-databases-1
To fix the issue, I replaced `@InjectDataSource` for `@InjectConnection` that is the correct annotation.

docs: example of sequelize injection for a named connection

---

content/faq/raw-body.md

N/A
This pull request updates the documentation for registering a different parser dynamically with Express and Fastify Body Parsers. The current documentation does not mention that only json and urlencoded parsers are registered by default. The updated documentation clarifies that if you want to register a different parser on the fly, you need to do so explicitly, and provides an example of how to register a text parser.

docs(raw-body): registering a different parser dynamically

---

content/faq/raw-body.md

I noticed a lot of questions on how `.useBodyParser` works in the original issue that was opened about this feature.
- Some devs mentioning that they cannot find the `.useBodyParser` method because they forget to type their application as `NestExpressApplication` or `NestFastifyApplication`. This is now a `warning` block.
- I added the reason for adding `.useBodyParser`: to allow registering body parsers with their own options, while respecting the `rawBody: true` application option.
See questions in https://github.com/nestjs/nest/issues/10471

docs(raw-body): add examples and explainers for body parser limits with `app.useBodyParser`

---

content/devtools/overview.md

Updated to need to call `fs.writeFileSync`
```ts
// error TS2304: Cannot find name 'writeFileSync'.
bootstrap().catch((err) => {
writeFileSync('graph.json', PartialGraphHost.toString() ?? '');
process.exit(1);
});
writeFileSync('./graph.json', app.get(SerializedGraph).toString());
```
```ts
import * as fs from 'fs';
fs.writeFileSync('graph.json', PartialGraphHost.toString() ?? '');
fs.writeFileSync('./graph.json', app.get(SerializedGraph).toString());
```

docs(devtools): change writeFileSync to fs.writeFileSync

---

content/faq/global-prefix.md

When passing paths to exclude to `app.setGlobalPrefix`, it's not mentioned that the string to `exclude` (either the raw `string` or `path` in `RouteInfo`) is internally handled using [path-to-regexp](https://github.com/pillarjs/path-to-regexp). In particular it doesn't make clear path-to-regexp's [lack of wildcard handling](https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x), meaning that strings containing wildcards or even conventional regexps (e.g. `auth/*`, `auth.*` etc) will not work. This was a major headache to figure out on my project, and we can very close to giving up on using `useGlobalPrefix` entirely.
Points this out in a hint, similar to the route …

docs(global-prefix): add path-to-regex hint

---

tools/transforms/nestjs-package/processors/cleanGeneratedFiles.ts

[rimraf v4 recently removed support for glob patterns](https://github.com/isaacs/rimraf/issues/249), then subsequently added them back, but requiring the `{ glob: true }` in the options passed to rimraf API methods. My understanding is, on POSIX-compliant OSs, it'll use the native shell handling of glob patterns anyway, but on Windows, now needs to passed this option for it to use the [node-glob](https://github.com/isaacs/node-glob), which handles glob patterns on Windows.
As mentioned in the below issue, the `rimraf.sync` call in `cleanGeneratedFiles.ts` will error with "Illegal characters in path." when the `${OUTPUT_PATH}/{docs,*.json}` glob is passed in, apparently only on Windows (I'm on Windows 11 and get the exact same …

fix(docs): asset cleaning errors on windows

---

content/recipes/automock.md

Example matches old api.
New `@automock/jest` api requires a `use` mock. See [this](https://github.com/sahellebusch/nestjs-cats-example/blob/automock-example/src/cats/cats.service.spec.ts) working example.
None.

docs(automock): update code example to match  api

---

content/cli/scripts.md

[The current cli build script documentation states that the build script is a wrapper around the tsc compiler or the webpack compiler](https://docs.nestjs.com/cli/scripts#build) but in webpack's documentation it's said that it uses tsc in it's ts-loader.
The documentation states that the build script for monorepos is a wrapper for webpack's bundler that uses ts-loader.
I'm fairly new to proper js development environment and this is my first PR. The build script doc got me uncertain and led me on a tangent to read webpack's doc again to be sure I was not mistaken. To be honest, reading the other PRs made me think mine is not really necessary, but please, give feedback.

docs(build): add clarification

---

content/controllers.md

Without specifying the variable 'params' as type 'any' I received the following error on a fresh project while following the documentation:
```typescript
findOne(@Param() params): string {
```
```
error TS7006: Parameter 'params' implicitly has an 'any' type.
```

Update controllers.md (type 'params' as 'any')

---

content/cli/usages.md

add documentation about this feature introduced in `@nestjs/cli` 9.4: https://github.com/nestjs/nest-cli/pull/2011

docs(cli): add hint on manual restart for tsc watch mode

---

content/techniques/cookies.md

Previous import statement causes error. Wildcard should be removed to use cookie-parser middleware as shown in the document like " app.use(cookieParser()) ".
- [👍] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
Current import statement that is written in the document like:
```javascript
import * as cookieParser from 'cookie-parser';
// somewhere in your initialization file
app.use(cookieParser());
```
causes error like:
Just changing document like:
```javascript
import cookieParser from 'cookie-parser';
// somewhere in your initialization file
app.use(cookieParser());
```
and it causes no error.
None.

docs(techniques):cookie-parser import changed

---

content/graphql/quick-start.md

Removed unknow `debug` property from GraphQLModule. `TS2345: Argument of type '{ driver: typeof ApolloDriver; debug: boolean; playground: false; }' is not assignable to parameter of type 'ApolloDriverConfig'.`

docs: remove unknown property

---

content/recipes/swc.md

Error when running `vitest` with an existing `.swcrc` as outlined in the `swc` recipe.
As it stands, both the `swc` and `vitest` recipes work great in their own right. When used together however, the module type needs to be explicitly set in `vitest.config.ts`. Otherwise it will be inherited from the `.swcrc`, which leads to an error `Cannot find module...`.
No error when running `vitest` with an existing `.swcrc` as outlined in the `swc` recipe.
Thanks for adding these useful recipes.

docs(vitest): explicitly specify swcrc option to avoid conflict with vite

---

content/techniques/sql.md

Another attempt to clarify that one nestjs itself wasn't made _for_ typeorm
From time to time people bring questions related to typeorm because isn't clear that `@nestjs/typeorm` isn't `typeorm`

docs(techniques): minor semantical change on typeorm integration section

---

content/security/authentication.md

```shell
$ nest start
src/auth/auth.service.ts:9:16 - error TS7006: Parameter 'username' implicitly has an 'any' type.
9   async signIn(username, pass) {
~~~~~~~~
src/auth/auth.service.ts:9:26 - error TS7006: Parameter 'pass' implicitly has an 'any' type.
9   async signIn(username, pass) {
~~~~
Found 2 error(s).
```

Fix misleading response and TypeScript errors in authentication docs

---

README.md

Proposal:
- Removed travis links not used and not working in readme ( see screenshot )

chore(): removed travis links not used in readme

---

content/migration.md

Adding a note that NestJS doesn't include an `update` command and to use npm-check-updates per Member recommendation.
The reason why I'd like to add this is I was recently looking to upgrading from V9 to V10 and figured the CLI included an `update` command but it was [removed](https://github.com/nestjs/nest-cli/pull/1699). Looking into this more it was recommended by @kamilmysliwiec to [use npm-check-updates](https://github.com/nestjs/nest-cli/issues/321). I figured others would benefit from this like I did by adding it to the Migration guide.
If no one thinks this is useful like I did, we can close this.
There is no current `update` command and it's recommended to use `ncu`.
A note …

docs(migration): Adding a section for upgrading packages

---

content/openapi/operations.md

Ensure that when creating a reusable decorator `SwaggerModule` will create a definition for the used model by adding it as an extra model in the definition of the decorator.
The guide on creating reusable pagination decorators can fail if the dto is not defined anywhere else. 
Adding the referenced model within `ApiExtraModels` ensures that the model definition will always be generated.

docs(openapi) fix reusable custom decorator explanation

---

content/graphql/field-middleware.md

Added warning section. This section describes that FieldMiddleware can be applied only ObjectType. After update docs, we know it does not apply to other types.
related issue: 
- https://github.com/nestjs/graphql/issues/2446
- https://github.com/nestjs/graphql/issues/2751

docs(graphql): add warning section for field middleware

---

content/controllers.md

The original issue describing that was opened in the main nest repository, after discussing it was closed and I was oriented to address this in here.
Issue Number: [Wildcard must be the last character in the route](https://github.com/nestjs/nest/issues/11543)
Try it out on: [Minimum reproducible repository](https://github.com/pedroluiznogueira/nestjs-minimum-reproducible-route-wildcards)
A detailed explanation of the behavior is:
While following the documentation on section [Controllers - Route Wildcards](https://docs.nestjs.com/controllers#route-wildcards).
The provided example does not work as expected, when using `fastify` as the underlying http adapter.
```typescript
@Get('ab*cd') …
```

docs(route-wildcards): add warning to route wildcards section

---

content/techniques/sql.md

Change file name in code snippet from entity to model to persist consistency in file names in Relations section in In Sequelize Integration
Change `entities` word to `models` in Relations section in In Sequelize Integration
File name in Relations in Sequelize Integration is `user.entity` instead of `user.model` which is not persistent naming since it was introduced as `user.model` above
When introducing Relations in Sequelize Integration the word `entity` is used instead of `model` which is confusing for those who read the TypeORM integration. 
File naming is persistent  where in sequelize `user.model` is used instead of `user.entity`
When introducing Relations in …

docs(sequelize): fix wrong file name and relation name in sequelize

---

content/techniques/cookies.md
content/techniques/task-scheduling.md

- referencing `ScheduleRegistry` instead of `SchedulerRegistry` in one place.
- using default import instead of named one for `cookie-parser`, which is not supported unless you have `esModuleInterop: true`
- fix the wrong reference & align code snippets a bit more with others doc pages
- change the import statement for `cookie-parser` to follow the defaults of https://github.com/nestjs/typescript-starter `tsconfig.json`

docs(techniques): fix wrong reference to `SchedulerRegistry` class & fix import statement for `cookie-parser`

---

content/recipes/prisma.md

Current Prisma guide needs to be updated as custom `enableShutdownHooks` method has not been necessary since Prisma 3, and now the example doesn't compile since Prisma 5.
This leads to confusion for users: https://github.com/prisma/prisma/issues/20171
Release notes: https://github.com/prisma/prisma/releases/tag/5.0.0
The outdated section is removed.
This section has not been relevant since the introduction of the library engine as the default in Prisma 3. Now, in Prisma 5, the code example does not compile anymore since the `beforeExit` event was removed from Prisma Client (except when generating the client with the binary engine type, which most users should not do unless they have …

fix: remove outdated section about shutdown hooks with prisma

---

content/fundamentals/lifecycle-events.md

to me, isn't that clear that we can have lifecycle methods when using `useFactory` and `useValue`
use the word 'provider' as it sounds better than 'injectable' because, for example, `useValue` providers aren't _injectables_ as we cannot inject providers into them
I didn't know that we can use lifecycle hooks methods on those non-class-based providers as well until I tested it out lol

docs(fundamentals): minor rewording to clarfiy that lifecycle hooks works on any kind of provider

---

content/faq/serverless.md

the article mentioned in our docs ([this one](https://javascript.plainenglish.io/serverless-nestjs-document-your-api-with-swagger-and-aws-api-gateway-64a53962e8a2)) is now behind a paywall. I don't think this can be taken as a good resource anymore. Also, that article could be out-of-date and we won't know unless we pay for it _lol_

docs(faq): replace nestjs+swagger article by a gh issue

---

src/app/app-routing.module.ts
src/app/shared/guards/redirect.guard.ts

Proposal:
- Refactor the guard `redirect`, because as of Angular version 15.x interface `CanActivate` has been deprecated (see screenshot),  in the future it will be removed and they have turned the guard configuration from class to function(arrow function). 
For others information see here: https://angular.io/guide/deprecations#router-class-and-injectiontoken-guards-and-resolvers

refactor(): update redirect guard

---

content/techniques/cookies.md

at 9.0.4 we should return a callback, or we've got a ts error:
TS2345: Argument of type 'typeof fastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback  | FastifyPluginAsync  | Promise{ default: FastifyPluginCallback ; }> | Promise...>'.
for @nestjs/platform-fastify 10.0.2 and fastify/cookies 9.0.4 we should return a callback inside register, or we've got a ts error:
TS2345: Argument of type 'typeof fastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback  | FastifyPluginAsync  | Promise{ default: FastifyPluginCallback ; }> | Promise...>'.
it's about register cookies plugin for nest fastify plattform

Updated cookies.md with register signature

---

src/app/common/social-wrapper/social-wrapper.component.html
src/app/homepage/footer/footer.component.html
src/index.html

Issue Number: 
https://github.com/nestjs/docs.nestjs.com/issues/2843
Proposal:
- Updated the version of font awesome, with the update to version `6.4.2` also includes new icons such as the latest Twitter icon.  😉

chore(): updated the version of font awesome

---

content/faq/hybrid-application.md
content/microservices/basics.md

Issue Number: #2835
There is currently no documentation on how to deal with an application which starts up multiple microservice servers but does *not* handle HTTP requests which has led to a couple cases of confusion where people are not properly starting up their application fully (see linked ticket for incidences).
Clarified how to handle a hybrid application which is HTTP+Microservice vs one which is Microservice+Microservice

docs(microservices): clarify hybrid application startup

---

content/pipes.md

Noticed that SRP abbreviation was not correct.
Update wording

docs(pipes): update wording

---

content/openapi/introduction.md

https://github.com/nestjs/swagger/pull/2544
Documentation new parameter `customSwaggerUiPath`

feat(introduction): add `customSwaggerUiPath`

---

content/faq/keep-alive-connections.md
src/app/homepage/menu/menu.component.ts
src/app/homepage/pages/faq/faq.module.ts
src/app/homepage/pages/faq/keep-alive-connections/keep-alive-connections.component.ts

Issue Number: #2840
Adds a page explaining the usage and behavior of `forceCloseConnections` option on `NestApplication`.

docs(faq): add docs for `forceCloseConnections` option

---

content/techniques/compression.md

This adds notes on  Brotli compression options and provides an example.
Closes issue #2834
Issue Number: #2834
Added documentation regarding Brotli performance.

Docs(/techniques/compression):  Brotli compression performance

---

content/techniques/events.md

- too few information about event-listener options
event listener options object updated at [feat: add suppress errors option](https://github.com/nestjs/event-emitter/pull/936)
i think need more information to users who use events.

docs(events): add events listener options

---

content/security/rate-limiting.md

docs(rate-limiting): update WsThrottlerGuard example for v5

---

content/recipes/automock.md

As Automock releases version 2.0, it is recommended that the Automock recipe documentation be updated.
- Since Automock now allows additional adapters, the '@automock/adapters.nestjs' package must be installed.
- Provide more illustrative examples
- Fix repository URL and link to online documentation.

docs(recipes): update automock recipe for v2.0

---

content/fundamentals/unit-testing.md

Removed a warning about global enhancers with a link to a workaround in Github as the workaround is the very next section

Remove redundant warning

---

content/openapi/operations.md

Mistake "Could not resolve reference" in swagger api if you use an [example with PaginatedDto](https://docs.nestjs.com/openapi/operations) 
Now there will be no error in the swagger api like "Could not resolve reference"
Now there will be no error in the swagger api like "Could not resolve reference"

fix(openapi): passed `PaginatedDto` to `ApiExtraModels` in `ApiPaginatedResponse` decorator

---

content/pipes.md

- For TS, use ZodSchema interface instead of ZodObject as `value` type (this way satisfying all zod schemas constructions. For example, when using `refine()` the schema type become `ZodEffects` instead of `ZodObject`)
- For Both, returns the parsed value of the schema, this way applying the zod `strip()`, equivalent to class-transform `whitelist`.
- For JS, fixes Pipe name (there was a missing "e" at the end of the name) and removes unused ZodObject import

docs(pipes): improve zod examples

---

content/devtools/ci-cd.md

It hasn't been mentioned explicitly in [GitHub Logs and Usage](https://github.com/logos), but based on _"Do not use the **GitHub** name..."_, and all the references of their legal name in [Wikipedia/GitHub](https://en.wikipedia.org/wiki/GitHub), it's actually `GitHub` as opposed to `Github`.

docs(devtools/ci-cd): change 'Github' to 'GitHub'

---

content/faq/request-lifecycle.md

Based on the sentence before it, _"to a controller if the decorator **precedes** a controller class"_, I believe this was supposed to be `precedes`, not `proceeds`.

docs(faq/request-lifecycle): change 'proceeds' to 'precedes'

---

content/techniques/file-upload.md

Add a notion about the possibility to make the file presence optional
It just adds a notion about the possibility to make file presence optional. I've been struggling a bit with this and I couldn't fild any information about this feature on file upload page.

docs: update file-upload.md with additional hint (make file optional in file upload)

---

content/openapi/introduction.md

it should be yaml instead of json.
```js
/**
* Path of the YAML API definition to serve.
* Default: `<path>-json`. */ 
yamlDocumentUrl?: string;
```
changed to 
```js
/**
* Path of the YAML API definition to serve.
* Default: `<path>-yaml`. */ 
yamlDocumentUrl?: string;
```

docs(update): 📝 open api setup option

---

content/microservices/grpc.md

Actually
https://github.com/youngkiu/nest/blob/7f00840c074ba5a5f233f73ef6c8456115abd7c1/packages/microservices/constants.ts#L11, I wanted to suggest modifying `GRPC_DEFAULT_URL`,
Since it was clearly stated as Default in the document, I thought there was an intention to do this.
So, I suggest modifying the example in the document.
In the case of servers, it is often built and used as a docker image.
`0.0.0.0:50051` seems more appropriate as an example than `localhost:50051`.
In particular, in the case of gRPC in the target group of the AWS load balancer, 
since the success code of the health check is [12(UNIMPLEMENTED)](https://grpc.github.io/grpc/core/md_doc_statuscod …

docs(microservices): Update ip address:port for a gRPC Docker server

---

content/exception-filters.md

the [exception-filters](https://docs.nestjs.com/exception-filters#throwing-standard-exceptions) documentation describes that the JSON response body contains two properties: 'statusCode' and 'message', but the demo code in `cats.controller.ts'` uses the property 'status'.
the object properties used in the example remain consistent with the documentation, replace 'status' with 'statusCode'

docs(exception-filters): replace status with statusCode

---

content/exception-filters.md

In #2988 status has been changed to statusCode, but it's inconsistent with an example:
I think it should be changed back to 'status,' or 'status' in the aforementioned example should be changed to 'statusCode.' It doesn't matter which. The case that @wilsonyiyi mentioned is irrelevant here. The docs say that we can pass an object, and there is no mention that it has to own a property called 'statusCode'.
> To override just the message portion of the JSON response body, supply a string in the response argument. To override the entire JSON response body, pass an object in the response argument. Nest will serialize the object and return it as the JSON response body.
Object properties used …

docs(exception-filters): correct status property

---

content/interceptors.md

The term "type" is being replaced with "class" to accurately reflect that an actual class instance is being passed for instantiation.
By making this adjustment, the code now accurately reflects that an actual class instance is being passed for instantiation.

docs(interceptors): replace 'type' with 'class'

---

content/faq/serverless.md
content/fundamentals/lazy-loading-modules.md
src/app/homepage/pages/fundamentals/fundamentals.module.ts

The current documentation contains `-` in lazy loading across the docs.
The new docs don't contain the hyphen anymore, apart from where it refers AngularJS. For reference, see MDN https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

docs: update lazy loading by removing the hyphen

---

src/app/homepage/menu/menu.component.ts

"Standalone Apps" menu is not highlighted when the "Standalone applications" page is open (https://docs.nestjs.com/standalone-applications).
The menu item is highlighted when the "Standalone applications" page is open.

fix: change standalone apps menu path to fix highlighting when active

---

content/graphql/federation.md

it's deprecated in favor of either:
- @apollo/subgraph
- @apollo/composition

remove reference to @apollo/federation

---

content/fundamentals/module-reference.md

it doesn't seems too clear that `ModuleRef#get` by default won't found providers registered and exported by imported modules
https://deploy-preview-3045--docs-nestjs.netlify.app/fundamentals/module-ref#retrieving-instances
help to avoid confusion as this one: https://github.com/nestjs/nest/issues/13726

docs(fundamentals): reword the default behavior of `ModuleRef#get`

---

content/recipes/prisma.md

docs: add explicit provider registration of new services in prisma recipe

---

content/techniques/caching.md

Since cache manager's In-memory store uses `lodash.clonedeep` internally, it can only store values of types supported by 'lodash'.
- Property descriptors, setters, getters, and similar metadata-like features are not duplicated. For example, if an object is marked readonly with a [property descriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor), it will be read/write in the duplicate, since that's the default. [mdn-Structured_clone_algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)
```ts
import { ObjectId } from "bson"; // import package to test invalid type which …
```

docs(caching): add note about of cache-manager

---

content/openapi/introduction.md

Docs weren't complete on exposing json spec with using only @nestjs/swagger
This documentation change adds an option that wasn't documented before for exposing json spec file with swagger. The documentation made it seem like it's only possible with other extensions however there is an option with just `@nestjs/swagger` to expose the document. 
I've been looking on how to do this for a while and couldn't find a working solution anywhere so I think this would be useful.
Cheers

docs(@nestjs/swagger): add description on how to expose swagger json file

---

content/websockets/gateways.md

When `namespace` options is used inside `@WebSocketGateway` decorator,
`@WebSocketServer()` will inject namespace instance instead server instance.
But it's not explained now.
For clear explanation, I added that information.

docs: get namespace instance

---

content/microservices/mqtt.md

- [X ] Docs
- [X ] No
The current state of the documentation refers to creating a custom transporter to set a QoS other than 0 on subscriptions created with the `@MessagePattern` decorator. The option added in the PR has not been documented, yet.

docs(mqtt): description on how to set qos on subscriptions

---

content/microservices/kafka.md

The documentation suggests to setup a separate ClientKafka, which does not share the same connection as ServerKafka.
Update documentation to use KafkaContext to get the active consumer and commit offsets with it.

docs(microservices/kafka): Update commit offsets to use KafkaContext

---

content/techniques/configuration.md

docs: Update configuration.md

---

content/controllers.md
content/devtools/ci-cd.md
content/microservices/redis.md

Currently the observable streams url point to: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html. However if you're on that site and click home it will bring you to their newer doc site. 
Also a few things are currently misspelled.
Updating the link to point to the latest observable docs here: https://rxjs-dev.firebaseapp.com/guide/observable. 
Also, fixing some misspellings. 
N/A

Update RxJS Observable URL to newer version + Fix some spelling mistakes

---

content/techniques/queues.md

The existing documentation was not updated correctly for the newer BullMQ package, and does not cover all use cases provided by the new package.
Docs updated to work with BullMQ.
This matches the documentation that is found in the official BullMQ docs: 
https://docs.bullmq.io/guide/nestjs#processor
https://docs.bullmq.io/guide/nestjs/queue-events-listeners
As well as the code behaviour and comments:
https://github.com/nestjs/bull/blob/master/packages/bullmq/lib/decorators/on-worker-event.decorator.ts
https://github.com/nestjs/bull/blob/master/packages/bullmq/lib/decorators/on-queue-event.decorator.ts

docs(queues): correct event listener example for BullMQ

---

content/modules.md

- Added `"illustrative-image"` class css for dark mode in the illustrative-image `"shared module"` so that it is in line with other images when there is dark mode ( see screenshot )

fix: update image color for dark mode in the "shared module" section.

---

content/openapi/introduction.md
content/openapi/other-features.md
content/openapi/types-and-parameters.md

NestJS does not use the new feature of lazy initialization of Swagger, which adds some time to startup.
Associated with https://github.com/nestjs/swagger/pull/2392
Now, by default, we use always the lazy initialization in favor of the initialization speed.

docs(openapi): prefer lazy over eager creation of the document

---

content/deployment.md

- [ X ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
- [ X ] Docs
- [ X ] No

chore: fix typo

---

content/openapi/types-and-parameters.md

Provide examples to users on how to set example and examples keys in the @ApiProperty annotation
Currently the documentation does not have any indication of how to use the `example` or `examples` keys in the `@ApiProperty(...)` annotation.
This PR adds an example for the `example` and an example for the `examples` keys to the documentation to help show how to use them.
N/A - This is a pretty straightforward PR.

docs(oas/swagger): provide examples of the example and examples keys

---

content/techniques/logger.md

docs(logging): add logging with timestamp enabled

---

content/techniques/caching.md

Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/2689 
Closing this PR: https://github.com/nestjs/docs.nestjs.com/pull/2691
Updating the cache configuration with Redis

docs(caching): updating the cache configuration with redis

---

content/microservices/basics.md

No docs for TLS over TCP support.
Issue Number: [6745](https://github.com/nestjs/nest/issues/6745)
Pull Request: [7516](https://github.com/nestjs/nest/pull/7516)
Added ``TLS support`` section to ``Basics`` page in ``Microservice`` section.

feat(microservice): add TLS over TCP support

---

content/fundamentals/lifecycle-events.md

I didn't found so clear that if we don't call `app.init()`/`app.listen()`, few lifecycle hooks won't be triggered, as we have for `app.close()` already
a minor note to clarify the expected triggering behavior of init phase hooks

docs(fundamentals): clarify triggering behavior of init phases

---

content/controllers.md

Change Cache-Control header to no-store
Docs suggests for `Cache-Control` header the value `none`. This is not a valid value.
Setting the `Cache-Control` header to value `no-store`. This is valid according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

docs(controllers): change Cache-Control header to no-store

---

content/openapi/introduction.md

In the docs the types `SwaggerDocumentOptions `  and  `SwaggerCustomOptions` are outdated compared to the actual types in the nestjs swagger module
Update the types to match exactly whats in the repo

docs(openapi): align types in intro page with code updates

---

content/techniques/queues.md

It's very unobvious that `defaultJobOptions` apply to jobs being scheduled only sometimes.
If you schedule jobs via a `FlowProducer`, these defaults don't have any effect.
I'd love to fix that, but before we tackle that, I think it's best and easiest to point out the current behaviour in the docs.
See https://github.com/taskforcesh/bullmq/issues/1034 for more in-depth explanation of this problem.

docs(queues): warn that `defaultJobOptions` don't always work

---

content/components.md

The documentation now contains more descriptive link text, improving clarity and accessibility for users.
This commit updates the documentation to replace generic link text with more descriptive and meaningful phrases. The changes enhance clarity and improve accessibility for users, particularly those using screen readers. 
- Replaced "here" with specific descriptions in multiple sections, including references to custom providers, dependency injection, injection scopes, and modules.
- Ensured that all hyperlinks provide clear context, making navigation more intuitive for readers.
These improvements align with best practices for documentation and contribute to a better …

docs(components): improve link text for clarity and accessibility

---

content/graphql/mutations.md
content/graphql/resolvers-map.md
content/graphql/subscriptions.md

I am proposing these changes to prevent the confusion that I had when I read the doc and add a hint to prevent a common pitfall that you might face in your app. 
Closes https://github.com/nestjs/docs.nestjs.com/issues/3149
- `nullable`: for specifying whether a field is nullable (in SDL, each field is non-nullable by default); `boolean`  is rephrased like this: `nullable`: for specifying whether a field is nullable (in `@nestjs/graphql`, each field is non-nullable by default); `boolean`.
- And a hint is added (though I am not quite sure if I did a good job at phrasing it).
n/a

fix: better wording + adding a hint about typing nullable fields

---

src/app/shared/components/theme-mode-toggle/theme-mode-toggle.component.html
src/app/shared/components/theme-mode-toggle/theme-mode-toggle.component.ts

Currently, the Nest.js documentation site does not respect the user's system preferences regarding the color scheme (light or dark). As a result, opening the site in a new browser or in an Incognito session always defaults to light mode, ignoring the system preferences.
Manually toggling the theme will save the current theme in `localStorage`, so the next time the user opens the site, it will remain the same.
The new behavior respects the user's system preferences. If their preferred color scheme is dark, the Nest.js site will default to dark mode, and similarly, if their preferred color scheme is light, it will be in light mode. It now also listens for changes in the …

feat: respect user's preferred color scheme (dark mode repair)

---

content/openapi/types-and-parameters.md

Issue Number: [support description](https://github.com/nestjs/swagger/issues/2671)
Document support for descriptions in `@ApiSchema`
- documents the changes done here: https://github.com/nestjs/swagger/pull/3198/

docs(@nestjs/swagger): document description support in @ApiSchema

---

content/introduction.md

The current introduction.md, visible upon visiting "https://docs.nestjs.com/", contains an extraneous "-" character. Additionally, it would appear the "A" in "Architecture" should not be capitalized.
Though this is certainly not a big issue, I think fixing it in this specific scenario may be justified since the introduction serves as many people's first impression of NestJS.
The "Philosophy" section of the introduction.md reads, ". . .none of them effectively solve the main problem of - **Architecture**."
The "Philosophy" section of the introduction.md reads, ". . .none of them effectively solve the main problem of  **architecture**."
N/A

docs(introduction): Casing and remove extraneous "-" from introduction.md

---

content/recipes/prisma.md

The links to the REST & GraphQL Prisma examples 404 since the [locations were changed](https://github.com/prisma/prisma-examples/pull/7161/files).
This PR will permalink to the new example locations.
N/A

docs(prisma): fix 404'ing GitHub links to `prisma-examples`

---

content/graphql/complexity.md

Import from a deprecated lib.
Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/3167
- Import from `@apollo/server`.
- Prettier converted single quote to double quote.
- I had to pass context type to `GraphQLRequestListener`.
N/A.

chore: remove deprecated import

---

src/app/shared/components/copy-button/copy-button.component.ts

Fixes #3177 
Bug
Currently, It is copying and then not restoring back to copy icon after some timeout
Issue Number: #3177 
Now, I have added the setTimeout to 2s to toggle back to copy icon.

fix: Copy Icon is not restoring back from right tick ,when Copied

---

content/cli/overview.md
content/cli/usages.md
content/cli/workspaces.md
content/controllers.md
content/exception-filters.md
content/first-steps.md
content/microservices/basics.md
content/microservices/kafka.md
content/microservices/mqtt.md
content/microservices/nats.md
content/microservices/rabbitmq.md
content/microservices/redis.md
content/middlewares.md
content/migration.md
content/pipes.md
content/recipes/cqrs.md
content/techniques/caching.md
content/techniques/configuration.md
content/techniques/logger.md

release: version 11.0.0

---

content/migration.md
content/recipes/terminus.md

Documentation update for Terminus v11, related https://github.com/nestjs/terminus/issues/2570, https://github.com/nestjs/terminus/pull/2571

docs: add terminus v11 migration guide

---

content/graphql/resolvers-map.md

There is often confusion as to why adding `| null` or even `| null | undefined` to nullable fields or args in resolver definitions causes an error. This change attempts to help make this "way" of keeping the types with GraphQL nullable fields or args distinct a bit more clearer and to point to what is expected by the developer, when working with nullable fields.  
Scott

docs(resolvers-map): add notes about missing non-value types for nullable fields and args

---

content/techniques/queues.md

Related to this [PR](https://github.com/nestjs/bull/pull/2038) 
added docs for `BullMQ`'s manual registration option.

docs: added docs for bullmq's manual registration option

---

content/guards.md

**Updated the usage of Reflector#createDecorator to use the correct instance method in the custom decorator example.**
Updated the usage of `Reflector#createDecorator` to correctly use the instance method `Reflector.prototype.createDecorator` in the example for creating a custom `@Roles` decorator.

fix: corrected typo in the Reflector.createDecorator method usage

---

content/recipes/swc.md

Vitest does not automatically resolve TypeScript path aliases (`src/`), unlike Jest, which uses `moduleNameMapper`. 
This can lead to dependency resolution errors when running tests
Issue Number: https://github.com/nestjs/nest/issues/14653
- Updated the SWC documentation to include a fix for Vitest path alias resolution.
- Added `resolve.alias` configuration in `vitest.config.ts` to ensure correct module resolution.
- Explained why Vitest requires explicit path alias configuration, improving clarity for users.
- Ensured consistency with Jest’s `moduleNameMapper` behavior.
This PR improves the official documentation by adding an alias resolution configuration to prevent common Vitest …

docs(swc): add vitest alias resolution configuration

---

content/openapi/introduction.md

Currently, the Swagger documentation does not provide a clear explanation of how the ui and raw options work independently. Users might assume that disabling the Swagger UI (ui: false) also disables JSON/YAML documentation or vice versa.
This PR is an document update for the changes below.
https://github.com/nestjs/swagger/pull/3185
https://github.com/nestjs/swagger/commit/675a0272ca3d60db716ee97bf17012dddfe38637
- Added a new section under Setup options explaining how ui and raw interact.
- Provided an example configuration demonstrating a case where the UI is disabled but JSON definitions remain available.
- Clarified Swagger UI and JSON/YAML accessibility behavior …

docs(swagger): add ui/raws description, hint

---

content/techniques/mongo.md

Fixa misleading type annotation error in the subdocuements section of the documentation when defining a type override for the parent document
In the documentation page for Mongoose [here](https://docs.nestjs.com/techniques/mongodb#subdocuments). The Subdocuments section the example shown for how to define a subdocument has a small error that is misleading and causes typescript to complain (rightfuly so). Here is the misleading bit:
```ts
export type PersonDocumentOverride = {
name: Types.Subdocument<Types.ObjectId & Name>;
};
```
The correct example is taken directly from the mongoose docs [here](https://mongoosejs.com/docs/6.x/docs/typescript/subdocuments.html) where …

docs (mongo): update in subdocuments

---

content/techniques/queues.md

The BullMQ queue example contains two issues:
1. Undeclared loop variable `i` in `for` loop
2. Incorrect `job.progress()` method instead of `job.updateProgress()`
- Declares loop variable with `let i`
- Uses correct `job.updateProgress()` method

docs(queues): fix undeclared loop variable and progress method in example

---

content/openapi/introduction.md
content/recipes/async-local-storage.md
content/recipes/cqrs.md
content/recipes/prisma.md
content/recipes/swc.md

This PR standardizes class naming to the plural form, as recommended in #1176.
Changes:
- Updated `UserService` to `UsersService` in `prisma.md` and other similar cases.
Fixes #1176
Fixes #3220

docs: use plural names instead of singular

---

content/openapi/cli-plugin.md

Updates the outdated `@nestjs/swagger/plugin` CLI options table to reflect the latest changes introduced in https://github.com/nestjs/swagger/pull/3151.
- Added `skipAutoHttpCode` option to `cli-plugin.md`
- Updated the options table with `skipAutoHttpCode`
- Provided an example JSON configuration for `nest-cli.json`
Issue Number: #3221
This PR updates the documentation to reflect the new `skipAutoHttpCode` option introduced in [#3151](https://github.com/nestjs/swagger/pull/3151)
- The `@nestjs/swagger/plugin` now supports disabling automatic `@HttpCode()` annotation by setting `"skipAutoHttpCode": true`.
- The CLI Plugin documentation has been updated to include this option in the …

docs(cli-plugin): update documentation for skipAutoHttpCode option

---

content/techniques/mongo.md

Clarify how to get better typesafety when using `mongoose.Schema.Types.ObjectId` as a type in `@Prop()`
I want clear up some documentation that I think is confusing to people that are new to typescript / nestjs / mongoose.
I think it was not clear enough what the correct type should be if people choose to not populate the references on mongoose schemas.
I added some examples and comments about how you might go about adding `mongoose.Schema.Types.ObjectId`s to the schemas if you don't plan on always populating those.
Thank you for a lovely library.

docs(techniques): Make the use of ObjectId less ambiguous

---

content/microservices/basics.md

This update clarifies the use of `AsyncMicroserviceOptions` for configuring microservices dynamically using the `ConfigService` when the injection context is available post-instantiation. The addition addresses scenarios requiring flexible configuration setup.
Issue Number:
- https://github.com/nestjs/nest/pull/12622
It is a long-standing question on StackOverflow that has been flagged for a solution, but the respective solution or explanation is absent in the official NestJS documentation. https://stackoverflow.com/questions/66605392

docs(microservices): add note on using AsyncMicroserviceOptions

---

content/techniques/file-upload.md

New version of the FileTypeValidator implemented in https://github.com/nestjs/nest/pull/14881 no longer has a limitation that the file contents are removed.
This updates the documentation to match.

Update file-upload.md for secured FileTypeValidator

---

content/security/rate-limiting.md

Fix incorrect filename extension in "trust proxy" example under Security > Rate Limiting
The example hardcodes the ".ts" suffix when referencing the "main" file, resulting in incorrect filenames like "main.ts.ts" or "main.ts.js". This commit removes the fixed suffix to ensure correct file resolution based on the context.
The updated example now aligns with the behavior of other code examples in the documentation by dynamically adjusting the filename between ".js" and ".ts", depending on the context. This prevents incorrect filenames like "main.ts.ts" or "main.ts.js" and ensures consistency across the documentation.

fix(docs): remove hardcoded ".ts" suffix from main file reference in trust proxy example

---

content/openapi/operations.md

The type of `file` is not specified.
Added the type explicitly for clarity.

docs(openapi): add explicit type for single file upload

---

content/microservices/basics.md

Updated a typo in the microservices documentation page.

fix: update typo in microservices docs

---

content/controllers.md

The `@Controller()` decorator can take an `host` option, not `hosts` :)

docs(controllers): fix typo

---

content/microservices/kafka.md

docs(changelog): change from prodocuer to producer
It fixes a typo in the documentation for kafka
The word producer is misspelt as prodocuer
Fixed the typo

docs(changelog): fix typo prodocuer to producer

---

content/techniques/events.md

Documentation is indicating a synchronous method call with unnecessary `await` keyword.
Documentation is a little more "accurate", as a synchronous function does not need `await` keyword during call.

docs(events): Remove await from eventEmitter.emit example

---

content/fundamentals/unit-testing.md

unit-testing.md referenced MockFunctionMetadata, which was removed in version 30 of jest-mock. This commit changes references of MockFunctionMetadata to MockMetadata, updating it to work with the newer versions of jest-mock.
unit-testing.md refers to MockFunctionMetadata, which has been removed in jest-mock version 30.
Issue Number: #15309 (in @nestjs/nest)
unit-testing.md now refers to MockMetadata, allowing the example code to proceed.

fix(unit-testing.md): unit-testing.md to use MockMetadata from jest-mock 30+

---

content/microservices/kafka.md

typos method
`ClientKafkaProxy#send`
`ClientKafkaProxy#emit`
`ClientKafkaProxy.send`
`ClientKafkaProxy.emit`

docs: fix kafka typos

---

content/recipes/terminus.md

docs: fix typo in healthchecks section

---

content/techniques/caching.md

The documentation incorrectly states that the `Cache` class is imported from `cache-manager` while the `CACHE_MANAGER` token is imported from `@nestjs/cache-manager` package.
Clarifies that both the `Cache` class and `CACHE_MANAGER` token are imported from the `@nestjs/cache-manager` package.
This is a minor documentation fix to improve accuracy and clarity for developers using NestJS caching.

docs: fix import clarification for Cache and CACHE_MANAGER

---

.github/workflows/lighthouse.yml
src/styles.scss

This PR bumps GitHub action workflows to their latest versions.
It also fixes a typo on the way.

Bump GitHub action workflows
